### ISSUE TITLE
Automatic mentorship for "Two-Fer"

### ISSUE THREAD

**Issue by jfrank94** [exercism/exercism#4704] opened 2019-02-14 15:49 UTC
Two days ago I submitted my solution for Two-Fer which I didn't request mentorship for. No one has responded since then hence why I'm on here. I don't want to mark it as complete as I would like to do the side exercises for this problem.

**Comment by guygastineau** [comment] 2019-02-22 12:49
FYI, you can do the side exercises even after you have clicked to complete an exercise.

**Comment by christopherchateau** [comment] 2019-02-27 20:46
I'm having the same issue with the 'wordy' challenge on the javascript track. My only concern is it showing up as a challenge I've solved. Did a mentor eventually approve your solution jfrank? Is there a way to avoid this in the future? All my other challenges were immediately marked as completed, no clue why this one randomly needed mentor approval.

**Comment by iHiD** [comment] 2019-02-28 12:36
Could you post solution ids pls?

**Comment by jfrank94** [comment] 2019-02-28 15:16
@christopherchateau My solution(s) were eventually approved. It took about 2-4 days. It would be great if automatic mentorship would be taken off as a functionality so that this wouldn't be an issue for future users of the platform. 

@iHiD My solution ID for Two-Fer is 45058de6cd7d446b95595bc2a6178a0a.

**Comment by iHiD** [comment] 2019-02-28 22:32
@jfrank94 Thanks for updating

> It would be great if automatic mentorship would be taken off as a functionality so that this wouldn't be an issue for future users of the platform.

This isn't a deliberate thing. I have no idea how or why it's happening on your solutions - it doesn't for 99.9% of solutions. Thanks for the id but I need one that is "fresh" so I can try and understand what's happened. If the same situation happens again, please post the id and I'll try and check straight away.

**Comment by jfrank94** [comment] 2019-02-28 22:35
@iHiD In that case, it happened again for "Acronym" 6db634230838461c898acdd7db92a5b3 and "High Scores" 0bcce78aba914f7ca685277c921d52bf. I'm not sure why this keeps happening almost every time? My settings do not seem out of the ordinary.

**Comment by iHiD** [comment] 2019-02-28 22:36
Thanks. I'll track it down now :)

**Comment by iHiD** [comment] 2019-02-28 22:39
OK. So you're in mentored mode. If you're in mentored mode, then all core exercises automatically go to a mentor and block you until a mentor looks at it. That's not a bug - it's how it's designed.

If you don't want that behaviour, you can use independent mode.

**Closed by iHiD** 2019-02-28 22:39 UTC
Labels: type/mentoring-support
