### ISSUE TITLE
Some exercises don't count as completed while they are completed

### ISSUE THREAD

**Issue by Gautzilla** [exercism/exercism#6231] opened 2022-02-07 12:29 UTC
In my C# track, I have 0 available exercises while 105 are still locked. I completed all my available exercises:

![1](https://user-images.githubusercontent.com/72027971/152786869-eed104e6-aed6-4a39-92f6-ff8560898d73.png)

It seems that some completed exercises don't count as such. If I take a look at the _locked_ **Accumulate** exercise, it needs the completion of 2 exercises to be unlocked: **Tracks on Tracks on Tracks** and **Log Analysis**. 
If I compare the main page of these two exercises, I got the following:

![2](https://user-images.githubusercontent.com/72027971/152788058-7b1afbde-6d9e-4e0a-a1a9-7afe903f883c.png)

While **Log Analysis** displays that it is completed, it is not the case for **Tracks on Tracks on Tracks**. Maybe that's part of the problem?

@ErikSchierboom maybe you have an idea of what's causing the trouble here?

**Comment by ErikSchierboom** [comment] 2022-02-08 10:24
@Gautzilla For some reason, the database has your `tracks-on-tracks-on-tracks` solution listed as not being completed, even though you've published it. I'm trying to track down the issue.

**Comment by Gautzilla** [comment] 2022-02-08 10:27
@ErikSchierboom Thanks for having a look! 

I guess it might be the same for the `Need for Speed` exercise. Could you check that out?

**Comment by ErikSchierboom** [comment] 2022-02-08 13:21
@Gautzilla There was indeed an issue in the database caused by a bug when iterations were deleted whilst the solution was published. We've manually set the publish data to null in the database of the solution that encountered this bug (there were 64). In practice this means that you'll now should be able to complete the exercise again and that everything should then work well.
The bug in the website will be fixed in https://github.com/exercism/exercism/issues/6231

**Comment by Gautzilla** [comment] 2022-02-08 13:24
@ErikSchierboom That's all good, the two exercises were now marked as _in progress_, I marked them as _complete_ and it indeed unlocked more exercises. Great job!

**Comment by ErikSchierboom** [comment] 2022-02-08 13:31
It'll be automatically closed once #2374 is merged. Let it open for now, as we technically haven't fixed the underlying issue yet :)

**Closed** 2022-02-08 13:45 UTC
