### ISSUE TITLE
Time when a comment was posted in a mentoring discussion is wrong

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5771] opened 2021-09-04 17:43 UTC
The times at the side of comments appear to be the time of the latest comment in the thread, regardless of when they were actually posted 

---

![grafik](https://user-images.githubusercontent.com/20866761/132103657-efe6c973-2222-4011-888c-98175ef9bafc.png)

---

![grafik](https://user-images.githubusercontent.com/20866761/132103665-9f4a0143-a2fa-4baf-9012-5122a29de9c2.png)

---

#### Steps to reproduce:

- Mentor a solution where the student commented on their iteration after submitting it
- Watch the time change afterwards

**Comment by iHiD** [comment] 2021-09-04 23:54
I sort of vaguely saw something like this, but I don't really get it, and can't reproduce.

> The times at the side of comments appear to be the time of the latest comment in the thread, regardless of when they were actually posted

Would this not mean all the times were the same?

---

Could you give me some more info pls?

**Comment by SaschaMann** [comment] 2021-09-05 00:52
They are all the same for me. In the screenshots above the first one is the time when the iteration was posted. I can try to screencap it tomorrow if that'd help.

**Comment by iHiD** [comment] 2021-09-05 01:06
Please. I'm thoroughly confused 🙂

**Comment by SaschaMann** [comment] 2021-09-05 12:06
Screenshots will have to do due to data limits:
After starting mentoring: (note **4 min ago**)

![grafik](https://user-images.githubusercontent.com/20866761/132125861-1d58bc07-5e75-4a29-9248-74f1b25455d4.png)

After commenting: (**now**)

![grafik](https://user-images.githubusercontent.com/20866761/132125870-32173aa6-0b02-4e4c-a3e6-9e9ab04c0c61.png)

A few min later after a refresh:

![grafik](https://user-images.githubusercontent.com/20866761/132125953-41866b4b-666f-4258-9983-ef80dabd3a23.png)

After another comment (I have no idea what this means or where it comes from):

![grafik](https://user-images.githubusercontent.com/20866761/132125964-0c5e1510-64d1-40a1-b659-a1fa799ba603.png)

After another refresh:

![grafik](https://user-images.githubusercontent.com/20866761/132125970-1818ba3e-f504-47c2-bbc3-c6549fd1e5a3.png)

After a student comment:

![grafik](https://user-images.githubusercontent.com/20866761/132126089-9ec3e817-e6bf-42f4-8c4f-33b9923ce1e8.png)

Waiting a bit:

![grafik](https://user-images.githubusercontent.com/20866761/132126132-fb15136f-e4ef-4a51-be65-9b8d0c60acd8.png)

Posting another comment:

![grafik](https://user-images.githubusercontent.com/20866761/132126144-81e3f033-2642-4fae-9120-a7b506c0069e.png)

---

The initial comment (which I think is a response to a question?) is set to the time of the first mentoring comment. The rest seems to work as expected.

Refreshing etc. does not fix it.

Example conversation: https://exercism.org/mentoring/discussions/ed9e22f412d6421184ccc35277606a69

**Comment by iHiD** [comment] 2021-09-05 12:33
Thanks :)

**Comment by iHiD** [comment] 2022-05-10 17:37
I feel like this is either fixed or it's referenced in another issue I went through with @ErikSchierboom. Going to assign to Erik to work out 🙂

**Comment by ErikSchierboom** [comment] 2022-05-12 13:36
This was fixed in https://github.com/exercism/website/pull/2545

**Closed by ErikSchierboom** 2022-05-12 13:36 UTC
Labels: type/bug
