### ISSUE TITLE
Broken link on https://exercism.lol/docs/tracks

### ISSUE THREAD

**Issue by bobahop** [exercism/exercism#5901] opened 2021-08-21 22:28 UTC
![docs_error_1b](https://user-images.githubusercontent.com/32035397/130336300-003d0ed0-80f4-43f8-b85e-ebe8d6f640ae.JPG)
![Docs_error_1](https://user-images.githubusercontent.com/32035397/130336303-4470df1e-cc12-49a7-8793-a66de49532fe.JPG)

**Comment by iHiD** [comment] 2021-09-15 17:23
Closing as duplicate of https://github.com/exercism/exercism/issues/5680

**Closed by iHiD** 2021-09-15 17:23 UTC
Labels: priority/high
