### ISSUE TITLE
Gopher's Gorgeous Lasagna missing go.mod

### ISSUE THREAD

**Issue by elshize** [exercism/exercism#5881] opened 2021-09-13 00:52 UTC
I'm not a Go expert but it seems to me like there should be a `go.mod` file in the exercise directory after the download, but it's missing (at least it's missing when I download it):

```
module lasagna

go 1.13
```

At least when I added it, I was able to run `go test`, so there's that :wink:

**Comment by elshize** [comment] 2021-09-13 01:02
It actually is missing from Annalyn's Infiltration, too.

**Comment by junedev** [comment] 2021-09-13 03:01
Thanks for reporting, there is already an issue for this in the Go track repository: https://github.com/exercism/go/issues/1490
There you can read more about why the issue is happening and how to work around it until a fix is merged.

**Comment by angelikatyborska** [comment] 2021-09-13 06:04
I'll close this because it's a duplicate. Also looking at https://github.com/exercism/go/issues/1490 it seems like the problem has been fixed an hour ago 🙂

**Closed by angelikatyborska** 2021-09-13 06:04 UTC

**Comment by elshize** [comment] 2021-09-13 11:11
Thanks guys, didn't think to search for it in `exercism/go` as opposed to here, hence the duplication. Thanks for pointing me in the right direction!
