### ISSUE TITLE
"Your Iterations" tab not consistent with my submissions

### ISSUE THREAD

**Issue by MSoup** [exercism/exercism#5814] opened 2021-09-06 04:49 UTC
As per the below screenshot, I've submitted two iterations, but it shows Iteration 1 (which failed wrongly) as being the latest. 

<img width="1310" alt="Screen Shot 2021-09-06 at 13 35 35" src="https://user-images.githubusercontent.com/19704779/132161908-e123aa53-5972-49ad-8e4f-53ea13b6c348.png">

**Comment by ErikSchierboom** [comment] 2021-09-07 06:21
I've moved this to exercism/exercism, as the problem does not look to be dart-specific.

**Comment by googlymog** [comment] 2021-11-18 07:14
I have the exact same issue, the iteration shown is not the latest one.  This can be remedied by hitting refresh on the browser, but that is annoying.  I have replicated this using Chromium (Ubuntu 20.04) and Google Chrome and Microsoft Edge (Windows 10).

**Comment by iHiD** [comment] 2021-11-18 11:12
I think this is a duplicate of https://github.com/exercism/exercism/issues/6052 which we thought was now fixed. @kntsoriano Any further ideas?

**Comment by kntsoriano** [comment] 2021-11-18 11:41
@iHiD I'll take a look at this. I'm assuming that the queryCache isn't loading or something like that.

**Comment by iHiD** [comment] 2021-11-18 11:45
Thanks man :)

**Closed** 2022-03-21 19:09 UTC
Labels: type/duplicate
