### ISSUE TITLE
Dark mode for the website

### ISSUE THREAD

**Issue by Pika-Pool** [exercism/exercism#6372] opened 2022-05-21 12:25 UTC
A dark mode option for the website would be awesome

**Comment by kytrinyx** [comment] 2022-05-21 14:20
Thanks for the suggestion, @Pika-Pool. This is on the roadmap, and will be implemented once we are able to prioritize it.

I'm closing this as a duplicate of #6286 #6275 #6002 #5748 #5436.

**Closed by kytrinyx** 2022-05-21 14:20 UTC
Labels: type/duplicate
