### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by asikuna** [exercism/exercism#6386] opened 2022-05-29 20:24 UTC
I love using Exercism, especially at night, but there's no dark mode. Are there plans for one, and can one be (relatively) easily implemented?

**Comment by kytrinyx** [comment] 2022-05-30 05:50
Yes, there are plans for one. It will be implemented once we are able to prioritize it.

I'm closing this as a duplicate of https://github.com/exercism/exercism/issues/6386 https://github.com/exercism/exercism/issues/6286 https://github.com/exercism/exercism/issues/6275 https://github.com/exercism/exercism/issues/6002 https://github.com/exercism/exercism/issues/5748 and https://github.com/exercism/exercism/issues/5436.

**Closed by kytrinyx** 2022-05-30 05:50 UTC
Labels: type/duplicate
