### ISSUE TITLE
Pangram and Robot name exercises in the C# track aren't available

### ISSUE THREAD

**Issue by Joerg9** [exercism/exercism#4345] opened 2018-09-13 13:35 UTC
I've unlocked the bonus exercises for the first exercise "Hello World". When I hover over the bonus exercises "Pangram" and "Robot name" it says unlocked but I can't reach them. 

When I try to open the link to these bonus exercises in a new page I get an error page: … can't find this page …

**Comment by guygastineau** [comment] 2018-09-16 14:12
You can try to download it with the cli.  This has worked for me when an exercise won't unlock on the website UI.

**Comment by Joerg9** [comment] 2018-09-16 14:38
Thanks you for your reply. 
I've already tried to download it via the cli but then it says that I do not have permission.

**Comment by iHiD** [comment] 2018-10-03 17:37
This is a duplicate of https://github.com/exercism/exercism/issues/3867 (although you had no way of knowing that :))

**Closed** 2018-10-03 17:37 UTC
