### ISSUE TITLE
Python image is overlaying on Python track when windows is resized

### ISSUE THREAD

**Issue by felipewhitaker** [exercism/exercism#6310] opened 2022-03-30 01:56 UTC
I believe the image already tells the whole story. 

<img width="713" alt="image" src="https://user-images.githubusercontent.com/36129486/160735020-6f1286f3-3bba-4abd-ab43-150842515079.png">

I would suggest fixing the image to be on top of the statistics.

**Comment by iHiD** [comment] 2022-03-30 13:39
Thanks. The website is currently not responsive. Closing as a duplicate of https://github.com/exercism/exercism/issues/6036

**Closed by iHiD** 2022-03-30 13:39 UTC
