### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Braden-077** [exercism/exercism#6500] opened 2022-08-16 18:44 UTC
I think there should be an implementation of dark mode in Exercism! It may be a tough challenge, but I think it could be great for a User Experience and Interface!

**Comment by iHiD** [comment] 2022-08-16 19:37
Closing as duplicate of https://github.com/exercism/exercism/issues/5436

While I appreciate the issue, please do look for existing issues before opening new ones: https://github.com/exercism/exercism/issues?q=is%3Aissue+is%3Aclosed+dark+mode

**Closed** 2022-08-16 19:38 UTC
