### ISSUE TITLE
New lessons and bonus appear but can’t access any of them

### ISSUE THREAD

**Issue by macta** [exercism/exercism#4205] opened 2018-08-08 17:51 UTC
Since reporting #4180, changes were made that made new lessons appear in the total count, as well as there names, however when I click on them, no details appear to let me download them in the Pharo track. The config.json seems correct?

**Comment by macta** [comment] 2018-08-08 19:43
I just noticed that text on the page where I have completed hello-world reads strangely - is it missing a number?

“Carry on coding. You have that you have not yet completed on this track. Why not try a new challenge?

Choose next exercise”

**Comment by macta** [comment] 2018-08-09 11:51
How do we get traction on some of these things - the Exercism platform seems quite flakey and there aren't any obvious tools to help me debug it? 

Possibly this is relate to beta tracks (although I think beta just means its not visible in the main menu and should work the same?)

**Comment by macta** [comment] 2018-08-09 12:34
I have found a workaround (that now works) - if you leave the track (and lose your progress) when you come back in it now unlocks properly. This can make this issue slightly less urgent - but there is a problem none-the-less

**Comment by iHiD** [comment] 2018-08-09 13:58
As I've said on Slack, the platform isn't flakey. You're just hitting one very specific problem which is that when maintainers add new exercises or change things in their configs, the tracks are updated, but users don't automatically get things unlocking  etc. This isn't simple. For a track where 100,000 people might have unlocked that exercise, we currently have to create 100,000 database records for that. In your situation where you're the only person testing the track, it seems simple but at a larger scale, it's not.

I totally appreciate this is frustrating for you, and I'm genuinely sorry for that, but there's no magic bullet other than me finding the better part of a day to write some software to solve this.

> “Carry on coding. You have that you have not yet completed on this track. Why not try a new challenge?

This is the other thing we discussed, which is that there are a couple of odd things when a track is fully completed. But as this also effects almost no users, it's a lower priority.

As far as I can tell, this is a duplicate of https://github.com/exercism/exercism/issues/3867 - Can I close it as one?

**Comment by macta** [comment] 2018-08-10 10:47
Yes it’s a duplicate.

This was far worse for new tracks particularly given the related bug that leaving a track didn’t reset things either.

You got us back on track via slack - so this is a bit of historical frustration now - that said if you want to grow the number of tracks you need to pay attention to these kinds of edge cases to smooth the path for new dev’s

**Closed** 2018-08-11 17:42 UTC
