### ISSUE TITLE
track repos: `description`: some are blank

### ISSUE THREAD

**Issue by ee7** [exercism/exercism#6361] opened 2022-05-12 17:10 UTC
The `description` appears in places like:
- https://github.com/exercism
- https://github.com/search?q=topic%3Aexercism-track+org%3Aexercism
- the top right of a language track repo, e.g. https://github.com/exercism/ruby

```sh
curl -sSfL 'https://api.github.com/search/repositories?q=topic:exercism-track+org:exercism&per_page=100' \
    | jq '.items | [.[] | {name,description}] | sort_by(.description)'
```

At the time of writing, there are 25 tracks with a blank `description`. Can we set them? 
```json
[
  {
    "name": "05ab1e",
    "description": null
  },
  {
    "name": "ada",
    "description": null
  },
  {
    "name": "arm64-assembly",
    "description": null
  },
  {
    "name": "babashka",
    "description": null
  },
  {
    "name": "ballerina",
    "description": null
  },
  {
    "name": "clojurescript",
    "description": null
  },
  {
    "name": "forth",
    "description": null
  },
  {
    "name": "gleam",
    "description": null
  },
  {
    "name": "gnucobol",
    "description": null
  },
  {
    "name": "io",
    "description": null
  },
  {
    "name": "j",
    "description": null
  },
  {
    "name": "nix",
    "description": null
  },
  {
    "name": "pharo-smalltalk",
    "description": null
  },
  {
    "name": "qsharp",
    "description": null
  },
  {
    "name": "reasonml",
    "description": null
  },
  {
    "name": "red",
    "description": null
  },
  {
    "name": "shen",
    "description": null
  },
  {
    "name": "solidity",
    "description": null
  },
  {
    "name": "system-verilog",
    "description": null
  },
  {
    "name": "tcl",
    "description": null
  },
  {
    "name": "vlang",
    "description": null
  },
  {
    "name": "wren",
    "description": null
  },
  {
    "name": "x86-64-assembly",
    "description": null
  },
  {
    "name": "z3",
    "description": null
  },
  {
    "name": "zig",
    "description": null
  }
]
```

The others:

```json
[
  {
    "name": "abap",
    "description": "Exercism exercises in ABAP"
  },
  {
    "name": "bash",
    "description": "Exercism exercises in Bash."
  },
  {
    "name": "csharp",
    "description": "Exercism exercises in C#."
  },
  {
    "name": "cpp",
    "description": "Exercism exercises in C++."
  },
  {
    "name": "c",
    "description": "Exercism exercises in C."
  },
  {
    "name": "cfml",
    "description": "Exercism exercises in CFML."
  },
  {
    "name": "ceylon",
    "description": "Exercism exercises in Ceylon."
  },
  {
    "name": "clojure",
    "description": "Exercism exercises in Clojure."
  },
  {
    "name": "coffeescript",
    "description": "Exercism exercises in CoffeeScript."
  },
  {
    "name": "common-lisp",
    "description": "Exercism exercises in Common Lisp."
  },
  {
    "name": "coq",
    "description": "Exercism exercises in Coq."
  },
  {
    "name": "crystal",
    "description": "Exercism exercises in Crystal."
  },
  {
    "name": "d",
    "description": "Exercism exercises in D."
  },
  {
    "name": "dart",
    "description": "Exercism exercises in Dart"
  },
  {
    "name": "delphi",
    "description": "Exercism exercises in Delphi Pascal."
  },
  {
    "name": "elixir",
    "description": "Exercism exercises in Elixir."
  },
  {
    "name": "elm",
    "description": "Exercism exercises in Elm."
  },
  {
    "name": "emacs-lisp",
    "description": "Exercism exercises in Emacs Lisp."
  },
  {
    "name": "erlang",
    "description": "Exercism exercises in Erlang."
  },
  {
    "name": "fsharp",
    "description": "Exercism exercises in F#."
  },
  {
    "name": "factor",
    "description": "Exercism exercises in Factor."
  },
  {
    "name": "fortran",
    "description": "Exercism exercises in Fortran."
  },
  {
    "name": "free-pascal",
    "description": "Exercism exercises in Free Pascal"
  },
  {
    "name": "gnu-apl",
    "description": "Exercism exercises in GNU APL."
  },
  {
    "name": "go",
    "description": "Exercism exercises in Go."
  },
  {
    "name": "groovy",
    "description": "Exercism exercises in Groovy."
  },
  {
    "name": "haskell",
    "description": "Exercism exercises in Haskell."
  },
  {
    "name": "haxe",
    "description": "Exercism exercises in Haxe."
  },
  {
    "name": "idris",
    "description": "Exercism exercises in Idris."
  },
  {
    "name": "java",
    "description": "Exercism exercises in Java."
  },
  {
    "name": "javascript",
    "description": "Exercism exercises in JavaScript."
  },
  {
    "name": "julia",
    "description": "Exercism exercises in Julia."
  },
  {
    "name": "kotlin",
    "description": "Exercism exercises in Kotlin."
  },
  {
    "name": "lfe",
    "description": "Exercism exercises in Lisp Flavoured Erlang (LFE)."
  },
  {
    "name": "lua",
    "description": "Exercism exercises in Lua."
  },
  {
    "name": "mips",
    "description": "Exercism exercises in MIPS Assembly."
  },
  {
    "name": "nim",
    "description": "Exercism exercises in Nim."
  },
  {
    "name": "ocaml",
    "description": "Exercism exercises in OCaml."
  },
  {
    "name": "objective-c",
    "description": "Exercism exercises in Objective-C."
  },
  {
    "name": "php",
    "description": "Exercism exercises in PHP."
  },
  {
    "name": "plsql",
    "description": "Exercism exercises in PL/SQL."
  },
  {
    "name": "perl5",
    "description": "Exercism exercises in Perl 5."
  },
  {
    "name": "raku",
    "description": "Exercism exercises in Perl 6."
  },
  {
    "name": "pony",
    "description": "Exercism exercises in Pony."
  },
  {
    "name": "prolog",
    "description": "Exercism exercises in Prolog."
  },
  {
    "name": "purescript",
    "description": "Exercism exercises in PureScript."
  },
  {
    "name": "python",
    "description": "Exercism exercises in Python."
  },
  {
    "name": "r",
    "description": "Exercism exercises in R."
  },
  {
    "name": "racket",
    "description": "Exercism exercises in Racket."
  },
  {
    "name": "ruby",
    "description": "Exercism exercises in Ruby."
  },
  {
    "name": "rust",
    "description": "Exercism exercises in Rust."
  },
  {
    "name": "scala",
    "description": "Exercism exercises in Scala."
  },
  {
    "name": "scheme",
    "description": "Exercism exercises in Scheme."
  },
  {
    "name": "sml",
    "description": "Exercism exercises in Standard ML."
  },
  {
    "name": "swift",
    "description": "Exercism exercises in Swift."
  },
  {
    "name": "typescript",
    "description": "Exercism exercises in TypeScript."
  },
  {
    "name": "unison",
    "description": "Exercism exercises in Unison"
  },
  {
    "name": "vbnet",
    "description": "Exercism exercises in VB.NET."
  },
  {
    "name": "vimscript",
    "description": "Exercism exercises in Vim script."
  },
  {
    "name": "wasm",
    "description": "Exercism exercises in WebAssembly"
  },
  {
    "name": "powershell",
    "description": "Exercism exercises in Windows PowerShell."
  }
]
```

**Comment by kytrinyx** [comment] 2022-05-12 18:00
Thanks @ee7, I'll go ahead and whip something up to fix this.

**Comment by kytrinyx** [comment] 2022-05-12 18:59
This is now fixed. I reran the `jq` command above, and confirmed that there are now no `null` descriptions.

**Closed by kytrinyx** 2022-05-12 18:59 UTC
Labels: x:size/small, type/bug, area/track-maintenance

**Comment by kytrinyx** [comment] 2022-05-13 07:49
Thank you so much for noticing that; I should have checked the punctuation when I made the update.

I will make them all consistent—I vaguely prefer ending with a period since a description is intended to be a full sentence or paragraph.

**Comment by kytrinyx** [comment] 2022-05-13 07:55
I've also updated the bootstrap script in `request-new-language-track` to include the period.

**Comment by kytrinyx** [comment] 2022-05-13 08:00
Okay this should now be good:

```
$ curl -sSfL 'https://api.github.com/search/repositories?q=topic:exercism-track+org:exercism&per_page=100' \
    | jq -r '.items | .[].description' \
    | sort
Exercism exercises in 05AB1E.
Exercism exercises in ABAP.
Exercism exercises in ARM64 Assembly.
Exercism exercises in Ada.
Exercism exercises in Babashka.
Exercism exercises in Ballerina.
Exercism exercises in Bash.
Exercism exercises in C#.
Exercism exercises in C++.
Exercism exercises in C.
Exercism exercises in CFML.
Exercism exercises in Ceylon.
Exercism exercises in Clojure.
Exercism exercises in ClojureScript.
Exercism exercises in CoffeeScript.
Exercism exercises in Common Lisp.
Exercism exercises in Coq.
Exercism exercises in Crystal.
Exercism exercises in D.
Exercism exercises in Dart.
Exercism exercises in Delphi Pascal.
Exercism exercises in Elixir.
Exercism exercises in Elm.
Exercism exercises in Emacs Lisp.
Exercism exercises in Erlang.
Exercism exercises in F#.
Exercism exercises in Factor.
Exercism exercises in Forth.
Exercism exercises in Fortran.
Exercism exercises in Free Pascal.
Exercism exercises in GNU APL.
Exercism exercises in Gleam.
Exercism exercises in GnuCOBOL.
Exercism exercises in Go.
Exercism exercises in Groovy.
Exercism exercises in Haskell.
Exercism exercises in Haxe.
Exercism exercises in Idris.
Exercism exercises in Io.
Exercism exercises in J.
Exercism exercises in Java.
Exercism exercises in JavaScript.
Exercism exercises in Julia.
Exercism exercises in Kotlin.
Exercism exercises in Lisp Flavoured Erlang (LFE).
Exercism exercises in Lua.
Exercism exercises in MIPS Assembly.
Exercism exercises in Nim.
Exercism exercises in Nix.
Exercism exercises in OCaml.
Exercism exercises in Objective-C.
Exercism exercises in PHP.
Exercism exercises in PL/SQL.
Exercism exercises in Perl 5.
Exercism exercises in Perl 6.
Exercism exercises in Pharo.
Exercism exercises in Pony.
Exercism exercises in Prolog.
Exercism exercises in PureScript.
Exercism exercises in Python.
Exercism exercises in Q#.
Exercism exercises in R.
Exercism exercises in Racket.
Exercism exercises in ReasonML.
Exercism exercises in Red.
Exercism exercises in Ruby.
Exercism exercises in Rust.
Exercism exercises in Scala.
Exercism exercises in Scheme.
Exercism exercises in Shen.
Exercism exercises in Solidity.
Exercism exercises in Standard ML.
Exercism exercises in Swift.
Exercism exercises in SystemVerilog.
Exercism exercises in Tcl.
Exercism exercises in TypeScript.
Exercism exercises in Unison.
Exercism exercises in V.
Exercism exercises in VB.NET.
Exercism exercises in Vim script.
Exercism exercises in WebAssembly.
Exercism exercises in Windows PowerShell.
Exercism exercises in Wren.
Exercism exercises in Z3.
Exercism exercises in Zig.
Exercism exercises in x86-64 Assembly.
```
