### ISSUE TITLE
Exercism notification area shows a different and incorrect number for when I submitted a solution

### ISSUE THREAD

**Issue by george-silva** [exercism/exercism#5914] opened 2021-09-15 20:18 UTC
Hello all! Congratulations on the lovely, lovely project.

I have been doing Clojure exercises and it's been a blast. I noticed an inconsistency between the notifications on the top right area and when I actually submitted a solution.

I submitted a solution a few hours ago, but the notifications show several hours ago.

See screenshot

![Screenshot from 2021-09-15 17-15-20](https://user-images.githubusercontent.com/863039/133503364-0a03398f-6a35-4fdd-aded-b56ca5593573.png)

Take a look, particularly at the `Log Levels` problem. The notification shows `18 h ago`, while the actual submission was just a few hours.

**Comment by angelikatyborska** [comment] 2021-09-16 06:38
This is a duplicate of https://github.com/exercism/exercism/issues/5620, please follow that issue for updates on this bug.

**Closed by angelikatyborska** 2021-09-16 06:38 UTC

**Comment by iHiD** [comment] 2021-09-16 10:42
@george-silva Thank you for the lovely encouraging words :)
