### ISSUE TITLE
Exercism list tracks and problems

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4161] opened 2018-07-14 04:07 UTC
@nealot opened the following issue:

---
Is there an api to fetch a list of the tracks and the problems? I would like to be able to integrate exercism with my text editor and it would be nice if I could obtain a preview of the tracks/problems to download.

**Comment by kytrinyx** [comment] 2018-08-05 17:46
This is going to require some product design discussions.

**Comment by nealot** [comment] 2019-02-08 21:55
Closing in favor of https://github.com/exercism/exercism/issues/4087.

**Comment by nealot** [comment] 2019-02-08 21:56
This seems to be a duplicate of https://github.com/exercism/exercism/issues/4087.

**Comment by ErikSchierboom** [comment] 2021-08-31 05:55
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 05:55 UTC
