### ISSUE TITLE
solving Error: not in workspace

### ISSUE THREAD

**Issue by padreno** [exercism/exercism#5429] opened 2020-12-01 23:15 UTC
I am working on the hello-world directory but yet. i can submit my work using the command exercism submit hello-worl.js
but i get the following output Error: not in workspace. thank u so much for help

**Comment by kotp** [comment] 2020-12-02 03:10
The problem is likely the missing `d` in `exercism submit hello-worl.js`

**Comment by NobbZ** [comment] 2020-12-02 06:00
Hi @padreno, we need some more information.

Can you please tell us what operating system you are on, as well as the output of the following commands:

* `exercism troubleshoot`
* `pwd` (Linux/Mac/Windows with PowerShell) or `echo %cd%` (Windows cmd)
* `ls -l` (Linux/Mac) or `dir` (Windows)
* the exact command you use to submit and the exact error.

Please use [Markdown](https://guides.github.com/features/mastering-markdown/) to format your post. Especially (fenced) codeblocks have been found suitable for terminal output.

**Comment by padreno** [comment] 2020-12-02 10:55
Hi @NOBBZ  thank you so much

Here is the details: I use os Sierra 10.12.6, I am on Mac machine.

```MacBook-Air:hello-world badrkhouzima$ exercism troubleshoot

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13


Operating System
----------------
OS:           darwin
Architecture: amd64


Configuration
----------------
Home:      /Users/badrkhouzima
Workspace: /Users/badrkhouzima/Exercism
Config:    /Users/badrkhouzima/.config/exercism
API key:   fc43*****************************718

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 66.893894ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 291.961549ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
```
*here is my pwd
````
MacBook-Air:hello-world badrkhouzima$ pwd
/Users/badrkhouzima/exercism/javascript/hello-world
````
*running the ls -l
```
MacBook-Air:hello-world badrkhouzima$ ls -l
total 696
-rw-r--r--    1 badrkhouzima  staff    1579 Dec  2 10:14 README.md
-rw-r--r--    1 badrkhouzima  staff     247 Dec  2 10:14 babel.config.js
-rw-r--r--    1 badrkhouzima  staff     207 Dec  2 10:21 hello-world.js
-rw-r--r--    1 badrkhouzima  staff     154 Dec  2 10:14 hello-world.spec.js
drwxr-xr-x  469 badrkhouzima  staff   15946 Dec  2 10:20 node_modules
-rw-r--r--    1 badrkhouzima  staff  333652 Dec  2 10:20 package-lock.json
-rw-r--r--    1 badrkhouzima  staff     948 Dec  2 10:14 package.json
MacBook-Air:hello-world badrkhouzima$ ls -a
.			.npmrc			hello-world.spec.js
..			README.md		node_modules
.eslintrc		babel.config.js		package-lock.json
.exercism		hello-world.js		package.json
MacBook-Air:hello-world badrkhouzima$
``

**Comment by NobbZ** [comment] 2020-12-02 12:13
Due to the case-insensitivity of the Macs filesystem (Windows suffers from the same Problem) you need to `cd Exercism` (with a capital `E`). Mac and Windows do not care for the difference, but the CLI does, and there is currently no reliable way to treat `exercism` and `Exercism` the same on those systems.

To be sure to always end up in the correct folder with correct casing, you can use `cd $(exercism workspace)` in bash and zsh or `cd (exercism workspace)` when in fish (at least IIRC).

Creating an alias in your shells RC file might help saving some keystrokes (tested on ZSH, but should work on bash as well, no clue about how to do this on fish):

```sh
alias cdex='cd $(exercism workspace)'
```

After reloading your shell, the command `cdex` will `cd` straight into your workspace.

**Comment by padreno** [comment] 2020-12-02 13:39
@NobbZ Thank you so much, this explanation helped and worked perfectly, to submit the exercise and to clarify things.

**Comment by kotp** [comment] 2020-12-04 06:36
Closing, per [comment](https://github.com/exercism/exercism/issues/5429#issuecomment-737235764).

**Closed by kotp** 2020-12-04 06:36 UTC
