### ISSUE TITLE
Feature request: Unpublish iteration for exercise

### ISSUE THREAD

**Issue by LauraDamianTNA** [exercism/exercism#5067] opened 2019-10-06 09:43 UTC
After publishing by accident, I could not find an easy way to remove the published solution

**Comment by NobbZ** [comment] 2019-10-06 10:15
Hello @LauraDamianTNA!

Could you please tell us the UUID of the solution you want to unpublish? Perhaps it is possible to change publishing state in the DB directly for now?

**Comment by sshine** [comment] 2019-10-06 11:40
@LauraDamianTNA: There isn't a way to *remove* an iteration, so the best alternative right now is to push a new iteration, either containing a file that says "Whoops, too early!" in case you want to avoid having it end up in the queue and receive attention too soon, or push something that is closer to being a final iteration soon enough.

With current queue lengths, you probably should not feel under time pressure, though, as the fast tracks usually have at least a day's waiting time.

Still, this seems like a useful feature. Since it is possible to publish many iterations, and one may also want to be able to unpublish an iteration that isn't the latest one, perhaps this feature is not entirely trivial and should be thought through.

Let's save it for now.

**Comment by sshine** [comment] 2019-10-07 15:08
Also a duplicate of #4525.

**Comment by ErikSchierboom** [comment] 2021-08-31 06:03
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 06:03 UTC
