### ISSUE TITLE
Rust Track misses String concept

### ISSUE THREAD

**Issue by jekkted** [exercism/exercism#6043] opened 2021-10-17 17:21 UTC
Learning path for Rust requires me to finish "String"-concept to continue with "Struct"-concept, but there is no "String"-concept to work on.

**Comment by SleeplessByte** [comment] 2021-10-17 23:21
Duplicate of https://github.com/exercism/rust/issues/1357. Please follow that issue instead!

**Closed by SleeplessByte** 2021-10-17 23:21 UTC
