### ISSUE TITLE
Include body of comment in emails

### ISSUE THREAD

**Issue by sf105** [exercism/exercism#4771] opened 2019-03-25 13:36 UTC
Can we include the reviewer's comment in the notification email? Whatever the motivation, it feels a bit like facebook notifications trying to drive traffic to the site. I'd like to be able to see what's going on from my phone email.

**Comment by iHiD** [comment] 2019-03-25 19:06
Yep. I agree. Closing as duplicate of https://github.com/exercism/exercism/issues/4428

**Closed by iHiD** 2019-03-25 19:06 UTC
