### ISSUE TITLE
Website title doesn't update

### ISSUE THREAD

**Issue by dem4ron** [exercism/exercism#6561] opened 2022-09-29 07:40 UTC
![Screenshot 2022-09-29 at 9 37 08](https://user-images.githubusercontent.com/66035744/192970317-131780ba-33d4-4733-84db-8639d7218352.png)

**Comment by iHiD** [comment] 2022-09-29 11:55
Duplicate of https://github.com/exercism/exercism/issues/6529

**Closed by iHiD** 2022-09-29 11:55 UTC
