### ISSUE TITLE
Some pages are not mobile responsive

### ISSUE THREAD

**Issue by gokul85** [exercism/exercism#6188] opened 2022-01-09 04:36 UTC
Some pages of this website are not mobile responsive or mobile friendly so kindly fix that pages ex: dashboard,... etc. 
![Screenshot_2022-01-09-10-01-40-908_com android chrome](https://user-images.githubusercontent.com/79007791/148669624-7449c5b1-6566-4473-b3d2-f16e8e620c87.jpg)

**Comment by SleeplessByte** [comment] 2022-02-03 16:32
Thanks for reporting! Duplicate of https://github.com/exercism/exercism/issues/6036

**Closed by SleeplessByte** 2022-02-03 16:32 UTC
