### ISSUE TITLE
[tracking] Ensure that each track config contains a list of file extensions that are acceptable in submissions

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4385] opened 2018-10-04 23:10 UTC
We will use this for a couple of different purposes:

- **syntax highlighting** - the Prism library can use file extensions to determine which syntax highlighting lexer to use
- **inferring files to submit with CLI** - the CLI can submit an exercise directory, but this often contains temp files, build files, artifacts, etc that we don't care to upload. The extensions will help us decide which files should be submitted

This depends on a number of other issues being solved:

- https://github.com/exercism/cli/issues/609
- https://github.com/exercism/cli/issues/610
- https://github.com/exercism/exercism/issues/3962
- https://github.com/exercism/exercism/issues/4386
- https://github.com/exercism/configlet/issues/141

**Comment by mienaikage** [comment] 2018-10-05 11:09
Will it be possible to include language specific files which don't have extensions? e.g. Perl 5 has `cpanfile` for declaring module dependencies.

**Comment by ErikSchierboom** [comment] 2018-10-11 06:40
> inferring files to submit with CLI

Really excited about this! This day, I've had several students that accidentally submitted the wrong file.

**Comment by kytrinyx** [comment] 2018-11-05 21:00
> Will it be possible to include language specific files which don't have extensions?

That is an excellent question, and I have no idea! We'll need to check how the Prism thing is implemented. Maybe we can have a default for a language that doesn't rely on extension.

**Comment by iHiD** [comment] 2020-03-07 17:18
@ErikSchierboom @kytrinyx Is this still relevant? If so, could you work out what needs to happen here pls, and provide a checklist. Or alternatively close the issue?

**Comment by iHiD** [comment] 2020-03-07 17:18
See also the references to other open issues throughout https://github.com/exercism/meta/issues/107

**Comment by ErikSchierboom** [comment] 2020-03-10 09:23
Well, I still really would like to be able to do `exercism submit` and have the CLI automatically determine which files to submit. I've regularly seen this go wrong for the C# and F# track.

In the research experiment, the `solution_files` key is used in each exercise's `config.json` (see [example](https://github.com/exercism/research_experiment_1/blob/master/exercises/csharp-1-a/.meta/config.json#L2)), which matches v3's stub files requirement. This has the disadvantage of requiring each exercise to specify the solution files (although test generators can automate this), but has the advantage that exercises can differ from each other if they choose so. I'm not sure that is something we actually need though, just a list of extensions might be fine too. Another "disadvantage" is that students are no longer free to just rename or add files.

The naming of the issue is slightly confusing I feel, as there can be a difference between the extensions a language uses and the extensions students want to submit. E.g. in C#, a solution will always have (and thus use) a `.csproj` file, but we almost never want to submit that file.

**Comment by kytrinyx** [comment] 2020-03-11 02:13
> I still really would like to be able to do exercism submit and have the CLI automatically determine which files to submit

Yeah, that's a good summary of the _why_ of this issue.

(Agreed on the naming of the issue. I've tried renaming for clarity).

**Comment by ErikSchierboom** [comment] 2020-03-11 10:31
Okay. @iHiD shall I create a checklist of what needs to be done?

**Comment by iHiD** [comment] 2020-03-11 11:45
Yes please! And some idea of it's importance/timings would be good too. e.g. is this something we should sync for the launch of v3.

**Comment by kytrinyx** [comment] 2020-03-11 15:50
I don't think it's important to sync for the launch of v3. This is a nice enhancement, but not critical path.

**Comment by ErikSchierboom** [comment] 2020-03-12 07:26
Agreed. Note that while writing this, I think what we might want is to have a gitignore-style globbing pattern, as that is a pattern people are familiar with. If we then combine this with both and include and an exclude property, we can make this a very nifty feature I feel. The exclude is necessary, as an extension might both be part of the solution and part of external files we don't want to submit (e.g. the `*.js` files in the `node_modules` directory for the JavaScript track).

Having examined the [configlet source code](https://github.com/exercism/configlet/blob/d7e3715157cc66669afcd6322ad19b11fdf830c4/track/config.go#L21), I think we miight already have the required fields to handle the above:

- `ignore_pattern`: can be used to exclude files/directories.
- `solution_pattern`: can be used to specify the default submission. We currently use this for the example file pattern, but we could introduce a separate field for that.
- `test_pattern`: specifies the test files.

So maybe we want to re-purpose the `solution_pattern` field and add a new `example_pattern` field?

@kytrinyx What do you think of the above suggestion?

**Comment by kytrinyx** [comment] 2020-03-12 19:47
I think that it would be easiest if we rely on completely new fields rather than changing how old fields work, since I'm not entirely sure where these get used, and we'd almost certainly break some existing (and hard to find) behavior.

Unless I'm missing something. If it's easy to ensure we don't break anything I have no problem with repurposing the fields.

**Comment by ErikSchierboom** [comment] 2020-03-13 07:39
You're probably right. I did a quick check, and the solution pattern is used in a variety of formats. Let's go for new fields.

**Comment by ErikSchierboom** [comment] 2021-08-31 05:57
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 05:57 UTC
