### ISSUE TITLE
Community solutions showing really old (and outdated) solutions first

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#5659] opened 2021-09-02 10:29 UTC
See the issue title

**Comment by iHiD** [comment] 2021-09-03 01:06
Stars then newest.

**Comment by iHiD** [comment] 2021-09-15 17:22
Duplicate of https://github.com/exercism/exercism/issues/5899

But also I think I fixed this?

**Closed by iHiD** 2021-09-15 17:22 UTC
Labels: priority/high

**Comment by gmlewis** [comment] 2021-11-24 15:33
@iHiD - check out this Elixir exercise where you have to navigate to Page 5 of the community solutions before you find the first one that is not outdated: https://exercism.org/tracks/elixir/exercises/list-ops/solutions?page=5

I would suggest that all "outdated" solutions be moved to the bottom of the list.

So the ordering should be:
Not-outdated: Stars, then newest.
Outdated: Stars, then newest.
