### ISSUE TITLE
Text on "About Go" page cut off

### ISSUE THREAD

**Issue by chillycurve1** [exercism/exercism#6216] opened 2022-02-01 14:00 UTC
Hello all,

Was just getting started on the Go track when I noticed that the [page](https://exercism.org/tracks/go/about) showing the advantages of Go had an error:

![image](https://user-images.githubusercontent.com/37170946/151982077-09ddab8b-1bd4-4b90-8348-4edd78801018.png)
 
I couldn't find the source code for that particular part of the page on Github, but I'd be happy to make a pull request if I missed it.

Have a great day!

**Comment by angelikatyborska** [comment] 2022-02-02 07:40
This is a duplicate of https://github.com/exercism/exercism/issues/5883 (cc @ErikSchierboom your own issue 😁). I'll close this one.

**Closed by angelikatyborska** 2022-02-02 07:40 UTC
Labels: area/website
