### ISSUE TITLE
Alignment of testimonials is all over the place

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5721] opened 2021-09-03 10:19 UTC
![grafik](https://user-images.githubusercontent.com/20866761/131990222-d7ca3ae6-9acc-4435-8b4b-0c54b6083eae.png)

I'm guessing this is related to the time/age of the testimonial.

**Comment by iHiD** [comment] 2022-05-10 17:14
Closing as duplicate of https://github.com/exercism/exercism/issues/5683

**Closed by iHiD** 2022-05-10 17:14 UTC
