### ISSUE TITLE
Display [ERROR]

### ISSUE THREAD

**Issue by Junior633-debug** [exercism/exercism#6209] opened 2022-01-29 17:19 UTC
Sometimes the content of the part where describing the language's pros doesn't display all the content as in Java track in the "Portable" part.
![Screenshot 2022-01-29 181905](https://user-images.githubusercontent.com/65125313/151670564-9fb87ebb-d52f-4713-914a-e33693c516d0.png)

**Comment by angelikatyborska** [comment] 2022-01-31 06:45
Thanks for reporting! This is a duplicate of https://github.com/exercism/exercism/issues/5883 so I will close this issue. Feel free to subscribe that other issue to get updates about it.

**Closed by angelikatyborska** 2022-01-31 06:45 UTC
