### ISSUE TITLE
Workflow bug or no available mentors.

### ISSUE THREAD

**Issue by jsplaine** [exercism/exercism#4197] opened 2018-08-07 13:15 UTC
Greetings, I have several ecmascript tasks completed which have not been mentored in 2 or 3 weeks now.  So I'm blocked from continuing on in ecmascript.  One reason why I suspect this to be some kind of bug is that, a week or so ago, these tasks each had this red text above the description: 

> This solution has been imported from independent mode. Mentoring will become available when your other solutions have been mentored.

However, there were no other unmentored solutions and the red status text persisted for about a week.  Seemed like an invalid state.

I suspect that my account is still in some kind of invalid state and that my tasks are not in any sort of mentor queue, thus preventing ecmascript tasks from being unlocked.  

Otherwise, if the mentor queue is very backed-up (tasks taking the better part of a month to be mentored), then please disregard.

And finally, thanks to all of you who generously work to support exercism.io -- I am a big fan!

**Comment by iHiD** [comment] 2018-08-07 13:26
Hey @jsplaine - thanks for the nicely written issue and sorry you've had a bit of a negative experience. I'll dig into your track for you now and see if I can find anything odd.

One thing I am aware of is that we're in the process of merging EMCA and Javascript, and that as of now most mentors are doing JavaScript because that's about to become the canonical one (with the EMCA exercises overwriting the old ones. It's complicated! :))

I'll get back to you.

**Comment by iHiD** [comment] 2018-08-07 13:31
@jsplaine So looking at your track, you're in mentored mode and all your exercises are ready to be mentored, so I think it's just a long queue, probably caused by the upcoming merging of EMCA and JavaScript and most mentors focusing on JS. @NobbZ has pinged the ECMAScript mentors to ask if they can prioritise your solutions.

**Comment by jsplaine** [comment] 2018-08-21 13:30
@iHiD Just wanted to give you an update -- I'm still stuck in the ECMAscript track with all possible tasks locked.  I'd say it's been like this for approximately a month now at this point.

![image](https://user-images.githubusercontent.com/1927930/44404365-b6423c80-a524-11e8-99b0-1056fe82c852.png)

**Comment by iHiD** [comment] 2018-09-02 18:29
So the problem with the is that you have some exercises waiting for mentoring, but they're all side exercises. There is an open issue to fix this problem by making seperate queues for side and core exercises for people who move from independent to mentored mode. In the meantime, I've manually fixed this in the database for you. You should receive mentoring soon :)

**Comment by jsplaine** [comment] 2018-09-10 13:02
Thanks @iHiD.  For now, I've reopened this bug as the exercises have not yet been mentored.

**Comment by jsplaine** [comment] 2018-09-21 12:36
Hello @iHiD, just pinging you again as it's been 19 days since your last update and still no reviews on my pending tasks.  Considering that this issue seems to be isolated to myself, I can pretty easily create a new account and copy my answers over?  Let me know what you think.

**Comment by niklaas** [comment] 2018-09-23 11:56
I am doing the Elixir track and have been waiting for mentoring approximately two to three weeks. I'll switch to independent mode now...

**Comment by OdellDotson** [comment] 2018-11-09 18:48
It seems that there aren't mentors for the python track either, I'm going to need to switch over to the independent mode... Really wish that I could get the extra exercises on independent mode, as waiting ~3 weeks for feedback on these early problems is a total blocker for actually learning anything.

**Comment by sshine** [comment] 2019-09-20 12:52
Since this issue is around a year old, I assume that those who reported being stuck (@jsplaine, @niklaas, @OdellDotson) have moved on, either in independent mode or elsewhere entirely.

The wording "Wordflow bug" in the issue's title, I interpret as addressing a bug when transitioning between independent mode and mentored mode where you may get stuck in the void in a way that is worse than if someone got stuck in mentored mode:

Side exercises that would have been unlocked don't unlock, because the core exercise was solved in independent mode, so you have nothing to do in the meantime. This means that switching from independent mode to mentored mode provides a considerably worse experience than the alternatives (always being in mentored mode, always being in independent mode, or switching from mentored to independent mode).

@iHiD wrote:
> So the problem with the is that you have some exercises waiting for mentoring, but they're all side exercises. There is an open issue to fix this problem by making seperate queues for side and core exercises for people who move from independent to mentored mode. In the meantime, I've manually fixed this in the database for you. You should receive mentoring soon :)

I am closing this issue, since separate queues were introduced.

If @jsplaine would like to further address the workflow / usability problems of switching from independent mode to mentored mode as the website currently is, this issue is an excellent place to do so, and the issue can be reopened or stay closed at your discretion.

**Closed by sshine** 2019-09-20 12:52 UTC
Labels: area/website, type/bug
