### ISSUE TITLE
gradle build error with test 

### ISSUE THREAD

**Issue by Matonte** [exercism/exercism#5517] opened 2021-04-18 02:37 UTC
When I try to run the initial test programs, I gets the following error:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\billm\Exercism\java\hello-world\build.gradle' line: 14

* What went wrong:
A problem occurred evaluating root project 'hello-world'.
> Could not find method testCompile() for arguments [junit:junit:4.13] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Anything that could get me on the right track will be appreciated!

**Comment by iHiD** [comment] 2021-04-18 19:56
cc @exercism/java

**Comment by mirkoperillo** [comment] 2021-04-19 06:44
Hi @Matonte ,
can you tell us:
- the version of gradle you are using (with command `gradle -v`)
- the folder you are executing the command `gradle test` from

thank you for you collaboration

**Comment by Matonte** [comment] 2021-04-19 13:49
`billm@DESKTOP-33HVAP8 MINGW32 ~/Exercism/java/hello-world (master)
$ gradle test

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\billm\Exercism\java\hello-world\build.gradle' line: 14

* What went wrong:
A problem occurred evaluating root project 'hello-world'.
> Could not find method testCompile() for arguments [junit:junit:4.13] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

billm@DESKTOP-33HVAP8 MINGW32 ~/Exercism/java/hello-world (master)
$ ^C

billm@DESKTOP-33HVAP8 MINGW32 ~/Exercism/java/hello-world (master)
$ gradle --version

------------------------------------------------------------
Gradle 7.0
------------------------------------------------------------

Build time:   2021-04-09 22:27:31 UTC
Revision:     d5661e3f0e07a8caff705f1badf79fb5df8022c4

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.10 (Oracle Corporation 11.0.10+9)
OS:           Windows 10 10.0 amd64


billm@DESKTOP-33HVAP8 MINGW32 ~/Exercism/java/hello-world (master)
$
`

**Comment by mirkoperillo** [comment] 2021-04-23 13:33
Hi @Matonte I have reproduced the problem.

The problem is about the version of gradle you are using (the v7). 
If you can downgrade to a previous version (6.8.x) everything will work.

I will open an issue in java track to trace this problem.

The current code in production is in freeze mode, so we cannot fix it.
We will push a fix when the new v3 platform will be officially online.

As said the current workaround is to use Gradle 6.8.x

**Comment by julia951** [comment] 2021-05-05 08:19
I've downloaded the 6.8.3 but problem is still exists 
[gradlew -version

Welcome to Gradle 6.8.3!

Here are the highlights of this release:
 - Faster Kotlin DSL script compilation
 - Vendor selection for Java toolchains
 - Convenient execution of tasks in composite builds
 - Consistent dependency resolution

For more details see https://docs.gradle.org/6.8.3/release-notes.html


------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (Oracle Corporation 11.0.11+9)
OS:           Windows 10 10.0 amd64

C:\Users\klimu\Exercism\java\hello-world>gradle test

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\klimu\Exercism\java\hello-world\build.gradle' line: 15

* What went wrong:
A problem occurred evaluating root project 'hello-world'.
> Could not find method testCompile() for arguments [junit:junit:4.13] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 687ms
](url)

**Comment by mirkoperillo** [comment] 2021-05-06 06:46
Hi @julia951 thank you for reporting this.
I tested the scenario under Linux with my "student profile" and with gradle 6.8.x and everything works.
It's not easy for me to test this under Windows quickly, I will investigate it ASAP.

Please can you run `gradle test --info` and paste here the output ?

Is there anybody of @exercism/java that can test this under Windows in a quick way ?

**Comment by julia951** [comment] 2021-05-06 06:55
`Initialized native services in: C:\Users\klimu\.gradle\native
Removing 0 daemon stop events from registry
Starting a Gradle Daemon (subsequent builds will be faster)
Starting process 'Gradle build daemon'. Working directory: C:\Users\klimu\.gradle\daemon\7.0 Command: C:\Program Files\OpenJDK\openjdk-11.0.11_9\bin\java.exe --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lan
g=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base
/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m -Dfile.encoding=windo
ws-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\ProgramData\chocolatey\lib\gradle\tools\gradle-7.0\lib\gradle-launcher-7.0.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.0
Successfully started process 'Gradle build daemon'
An attempt to start the daemon took 1.189 secs.
The client will now receive all logging from the daemon (pid: 1072). The daemon log file: C:\Users\klimu\.gradle\daemon\7.0\daemon-1072.out.log
Starting build in new daemon [memory: 512 MiB]
Using 12 worker leases.
Watching the file system is enabled if available
Now considering [C:\Users\klimu\Exercism\java\hello-world] as hierarchies to watch
Not watching anything anymore
Starting Build
Settings evaluated using settings file 'C:\Users\klimu\Exercism\java\hello-world\settings.gradle'.
Projects loaded. Root project using build file 'C:\Users\klimu\Exercism\java\hello-world\build.gradle'.
Included projects: [root project 'hello-world']

> Configure project :
Evaluating root project 'hello-world' using build file 'C:\Users\klimu\Exercism\java\hello-world\build.gradle'.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\klimu\Exercism\java\hello-world\build.gradle' line: 15

* What went wrong:
A problem occurred evaluating root project 'hello-world'.
> Could not find method testCompile() for arguments [junit:junit:4.13] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Not watching anything anymore
Watched directory hierarchies: []
Configuration Cache (C:\Users\klimu\Exercism\java\hello-world\.gradle\configuration-cache) removing files not accessed on or after Thu Apr 29 09:54:34 EEST 2021.
Configuration Cache (C:\Users\klimu\Exercism\java\hello-world\.gradle\configuration-cache) cleaned up in 0.001 secs.
VCS Checkout Cache (C:\Users\klimu\Exercism\java\hello-world\.gradle\vcs-1) removing files not accessed on or after Thu Apr 29 09:54:32 EEST 2021.
VCS Checkout Cache (C:\Users\klimu\Exercism\java\hello-world\.gradle\vcs-1) cleaned up in 0.0 secs.
`

**Comment by mirkoperillo** [comment] 2021-05-06 07:01
I see a lot of references to gradle 7.0, not to gradle 6.8.x
> ws-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\ProgramData\chocolatey\lib\gradle\tools\gradle-7.0\lib\gradle-launcher-7.0.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.0

**Comment by julia951** [comment] 2021-05-06 07:05
> I see a lot of references to gradle 7.0, not to gradle 6.8.x
> 
> > ws-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\ProgramData\chocolatey\lib\gradle\tools\gradle-7.0\lib\gradle-launcher-7.0.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.0

Intertesting because I changed the version in gradle-wrapper.properties. This is not enough?

**Comment by mirkoperillo** [comment] 2021-05-06 07:11
I seems you are not using the wrapper version, but a version installed on your OS.
Something installed using `chocolatey`
> C:\ProgramData\chocolatey\lib\gradle\tools\gradle

Can you copy here exactly the command you have run in the terminal ?

**Comment by julia951** [comment] 2021-05-06 07:23
I see here 'gradle 7.0' folder. You're totally right :)
But how I can change the version of gradle here?

**Comment by mirkoperillo** [comment] 2021-05-06 10:03
this is the link to gradle documentation
https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:using_wrapper

I think you have to use command `gradlew` insteadof `gradle` to be sure to use the wrapper.
But look at gradle documentation as reference

**Comment by mirkoperillo** [comment] 2021-05-27 11:36
Only to inform you that this issue has been already fixed by https://github.com/exercism/java/issues/1853
When v3 is officially released the students will be able to use new Gradle 7.x without issues

**Comment by belgoros** [comment] 2021-05-28 09:24
Same error on macOS `11.4`, Gradle `7.0.2`, it is really frustrating to see this kind of error comparing to a classic maven-based project.

**Comment by ajahraus** [comment] 2021-06-02 14:58
I would like to suggest a quick edit to the `build.gradle ` file which will let the tests run on the latest version of gradle (7.0 at the time of writing). 

The dependencies section of build.gradle file simply needs to be changed to

`dependencies {

  testImplementation "org.junit.vintage:junit-vintage-engine:5.7.2"
  
  testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.7.2"
  
}`

This will allow the tests (written in junit4) to be run on the more up to date junit5 vintage engine (i.e. the compatibility engine), as well as removes the usage of `testCompile` , which is deprecated and replaced with `testRuntimeOnly`

**Comment by belgoros** [comment] 2021-06-03 06:55
Applying the changes suggested by @ajahraus worked for me, thank you 🙂

**Comment by bb4L** [comment] 2021-06-16 20:50
@ajahraus  unfortunately those changes don't work for some tests which import / use

`import static org.assertj.core.api.Assertions.assertThat;`

do you have an idea how to fix those?

(i am using gradle 7.0.2)

**Comment by bobahop** [comment] 2021-07-05 19:21
FYI, it looks like 

```
dependencies {
testImplementation "junit:junit:4.13"
testImplementation "org.assertj:assertj-core:3.15.0"
}
```

works for `assertThat` but not for `containsExactlyInAnyOrderEntriesOf​` (as in Nucleotide Count.) The version of `testImplementation("org.assertj:assertj-core:3.20.2")` recommended on [assertj.org](https://assertj.github.io/doc/#gradle) also does not work.

It brings a little tear to my eye.

**Comment by wkpescherine** [comment] 2021-07-12 03:16
Having the same issue. In looking over various threads related to this. It seems that the gradle version as well as the API version are what is causing this. Basically this makes the API unusable at the moment. Do we need to wait for after August 2nd?

------------------------------------------------------------
Gradle 7.1.1
------------------------------------------------------------

Build time:   2021-07-02 12:16:43 UTC
Revision:     774525a055494e0ece39f522ac7ad17498ce032c

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          16.0.1 (Homebrew 16.0.1+0)
OS:           Mac OS X 10.15.7 x86_64

**Comment by ErikSchierboom** [comment] 2021-08-31 06:08
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 06:08 UTC
