### ISSUE TITLE
Make state of exercises re: mentoring/approval visible after being in independent mode

### ISSUE THREAD

**Issue by hilary** [exercism/exercism#4170] opened 2018-08-05 23:27 UTC
I submitted some of my core exercises for mentoring while in I was in independent mode (I'm trying to leverage my way back to mentored mode on a track). I believe those exercises have been mentored, because I have the option to submit another exercise for mentoring, which was previously disabled until the exercises I currently had submitted were done.

Oh, and no mentor notes show on any of my core exercises, even though I can now request mentoring on the things. So maybe they were reset rather than approved? Who knows? I sure don't 😭 

I can't tell *which* core exercises have been mentored, however, as there's no indicator I can find, in independent mode or in mentored mode (tried switching back), telling me my exercise had been approved.

In fact, I had one core exercise that had been approved, which approval no longer shows when I switch back to mentored mode. All I see in mentored mode is the big banner on each talking about how it was imported from independent mode. Furthermore, the mentor notes on that exercise have now disappeared.

Given that mentor resources are so scarce on the track in question, I'm reluctant to guess at which to submit next and possibly get it wrong.

**Comment by sshine** [comment] 2019-09-20 11:52
Hi @hilary. The website has changed quite a lot since this issue was posted, so I'll ask:

Is it correct that you say that some mentor *comments* (*) disappeared going from independent to mentored? This would be a testable bug, and we'd sure like that out of the way. Do you have a submission ID that @iHiD can eventually look at to see if there *are* actually mentor notes on it?

I think, maybe, this is a better approach (to relieve @iHiD):

Can you still reproduce this behavior? If you don't want to risk your feedback, you could try and sign up on a track you're not signed up on that I mentor, and we can simulate the steps it takes for the mentor feedback to disappear. If we can reproduce it, we can address this as a bug.

(*): Just to be sure, we have something called [mentor notes](https://github.com/exercism/website-copy/tree/master/tracks) now that is a summary/collection of feedback that mentors can base their feedback on, but it sounds to me that you're talking about the comments given by a mentor on the various iterations of your code as a student. If I'm wrong, let me know.

**Comment by ErikSchierboom** [comment] 2021-08-31 05:55
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 05:55 UTC
