### ISSUE TITLE
Umm mobile version is broken, fix it pls

### ISSUE THREAD

**Issue by AronCodes21** [exercism/exercism#6265] opened 2022-03-04 16:22 UTC

**Comment by NobbZ** [comment] 2022-03-04 16:26
What are you talking about exactly?

There is no android nor iphone app available, and the website is simply desktop centric, which might get fixed eventually but isn't one of the highest priorities as far as I understand.

**Comment by AronCodes21** [comment] 2022-03-04 16:32
Yes i was talking about the website, sorry about that.
It's just that some of the content doesnt align well, and are off the screen. Haven't found any problems with functionality tho

![image](https://user-images.githubusercontent.com/99847861/156801732-dc29b73a-8055-4d3b-9de8-0c4dd0b89470.png)

![image](https://user-images.githubusercontent.com/99847861/156801753-9f189aff-930d-4ab8-a13b-4cba6f3d490a.png)

**Comment by SleeplessByte** [comment] 2022-03-04 17:35
Duplicate of #6036  #6188  #6241  #6217 .

It's on the roadmap!

**Closed by SleeplessByte** 2022-03-04 17:35 UTC

**Comment by AronCodes21** [comment] 2022-03-04 17:36
Glad to hear that!
