### ISSUE TITLE
Can not sort solutions by stars or comments in V3

### ISSUE THREAD

**Issue by edxzh** [exercism/exercism#5666] opened 2021-09-02 12:50 UTC
Hi, I learnt a lot from the high stared/comments solutions, they always open my mind and help me better understand the programming language, however, this feature seems to be removed in V3 for some reasons, is this feature removed by purpose or I missed the filters on the page?

**Comment by angelikatyborska** [comment] 2021-09-02 12:58
This is a duplicate of https://github.com/exercism/exercism/issues/5616

**Comment by angelikatyborska** [comment] 2021-09-02 13:02
I will close it just because it's a duplicate, but of course this issue is important to us and we will take are of it. You can subscribe to https://github.com/exercism/exercism/issues/5616 to get notified when it gets resolved.

**Closed by angelikatyborska** 2021-09-02 13:02 UTC
