### ISSUE TITLE
Feature request: Show what exercises are done in blocking list

### ISSUE THREAD

**Issue by elyashiv** [exercism/exercism#5878] opened 2021-09-12 11:55 UTC
When you look at an exercise that is locked, you can see what exercises open it. Great!

But, there is no indication if you did that exercise or not :(

Screenshot:
![image](https://user-images.githubusercontent.com/1577529/132986588-d262dda0-340b-4a06-989a-b1a736b554c7.png)

I finished some of those exercises, but I can't know which from the list.

**Comment by angelikatyborska** [comment] 2021-09-12 12:15
I reported the same issue (in a different repository) when v3 was in beta: https://github.com/exercism/v3-beta/issues/151

@iHiD I don't know how you want to deal with duplicated between here and v3-beta. I thought all the valid issues from v3-beta would get moved here?

**Comment by iHiD** [comment] 2021-09-13 20:21
Thanks both. I've moved that issue here.

Duplicate of https://github.com/exercism/exercism/issues/5884

**Closed by iHiD** 2021-09-13 20:21 UTC
