### ISSUE TITLE
Make the track builds fail if `configlet fmt` hasn't been run

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3960] opened 2018-07-10 23:01 UTC
From https://github.com/exercism/meta/issues/105

We have the Configlet tool that we run against the track's `config.json` file, which ensures standardized formatting. This helps us when we need to script changes to the config files (a fairly frequent occurrence in the process of moving from v1 to v2), and also reduces the mental overhead for people who need to review, read, and maintain those files, since it keeps them consistent both in terms of whitespace and in terms of ordering of keys, so you know where to look for things.

If someone makes a change to a `config.json` file and submits a PR without having run `configlet fmt`, then the build should fail.

This task has two parts:

1. figure out how to make the build fail
1. submit a script to all the tracks to update the `.travis.yml` file with this change.

**Comment by iHiD** [comment] 2020-03-07 17:15
@ErikSchierboom Assigning this to you. I imagine there will be work to do for this for the v3 stuff. I'm not sure if the issue is still relevant, or how it should be handled.

**Comment by ErikSchierboom** [comment] 2020-03-11 10:46
> If someone makes a change to a config.json file and submits a PR without having run configlet fmt, then the build should fail.

@kytrinyx Does `configlet lint` verify that `configlet fmt` has been run?

**Comment by kytrinyx** [comment] 2020-03-11 15:49
It should do, yeah.

To test it, change some whitespace in a config.json and run `configlet lint .` from the root of the track.

**Comment by ErikSchierboom** [comment] 2020-03-12 08:16
It looks like it doesn't. I changed some things in my `config.json` and then ran `configlet lint .`, but nothing was displayed nor was the exit code non-zero.

**Comment by kytrinyx** [comment] 2020-03-12 19:44
I trust your test more than my memory!

**Comment by ErikSchierboom** [comment] 2020-03-13 07:37
I've created an issue: https://github.com/exercism/configlet/issues/175

**Comment by ErikSchierboom** [comment] 2021-08-31 05:54
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 05:54 UTC
