### ISSUE TITLE
Inconsistent queue number in Go track

### ISSUE THREAD

**Issue by dslizardo** [exercism/exercism#4984] opened 2019-08-18 05:33 UTC
**Solution ID** [04f2b8e81fac4be881e1d6fb80167472](https://exercism.io/my/solutions/04f2b8e81fac4be881e1d6fb80167472)

I submitted the exercise mentioned above last August 16, 2019 (Friday). I don't have a screenshot but I'm sure it says **1** _ahead in the Difference Of Squares queue_. I checked it again August 18, 2019 (Sunday) now it says **4** _ahead in the Difference Of Squares queue_. 

Why is that? How does the queue order works?

**Comment by smeruelo** [comment] 2019-08-20 22:10
I don't know if this is the way it's intended to work or not, but this definitely happens in Python track too. Two weeks after I last submitted a solution, the number of solutions ahead of mine has almost duplicated :(

**Comment by iHiD** [comment] 2019-08-21 12:05
Thanks. FYI, this is a duplicate of https://github.com/exercism/bugs/issues/18 which @kntsoriano is going to look into when he gets chance. I'm going to close this and suggest you subscribe to the other issue :)

**Closed by iHiD** 2019-08-21 12:05 UTC
