### ISSUE TITLE
Odd teams api errors

### ISSUE THREAD

**Issue by Smarticles101** [exercism/exercism#4587] opened 2019-01-08 16:01 UTC
I've been working on exercism/cli#788 lately, and I've found some odd differences/lack of error messages for teams.

Downloading an unstarted exercise on teams returns the following html 404 page.
```
<!DOCTYPE html>
<html>
    <head>
        <title>The page you were looking for doesn't exist (404)</title>
        <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
        <link rel="//fonts.googleapis.com/css?family=Lato:100,300,400,700,900|Montserrat+Alternates:400,700|Dosis:800"/>
        <style>
    * { box-sizing: border-box }

    html {
        @include normal-font;
        font-size: 62.5%;
        letter-spacing: 0;
    }

    body {
        z-index:0;
        margin: 0;
        @include normal-font;
        @include font-size(14);
        color:#333;
        padding: 0 0 env(safe-area-inset-bottom) 0;
    }
    .heading-bar {
      background:#22333b;
      height:40px;
      margin-bottom:150px;
      padding: env(safe-area-inset-top) 0 0 0;
    }
    img {
      display:block;
      margin: 0 auto 50px auto;
      width: 120px;
      height: 92px;
    }
    p {
      font-family: "Lato", 'Helvetica Neue', Helvetica, Arial, sans-serif;
      font-size:18px;
      line-height:18px;
      font-weight:300;
      color:#333;
      margin:0 0 6px 0;
      text-align:center;
    }
    a {
      color:#333;
      text-decoration:underline;
    }
  </style>
    </head>
    <body>
        <div class="heading-bar"></div>
        <img src="https://assets.exercism.io/sad-icon.png"/>
        <p>Oh dear, we can't find that page. Sorry about that.</p>
        <p>Continue by heading back to 
            <a href="/">the homepage</a>.
        </p>
    </body>
</html>
```
 This prompts this message in the cli: `unable to parse API response - invalid character '<' looking for beginning of value`

On the other hand, accessing an unlocked exercise on the normal site returns the proper json response
```
{
    "error": {
        "type": "solution_not_unlocked",
        "message": "You have not unlocked this exercise"
    }
}
```
which the cli properly handles.

If you try downloading an exercise which you have only started in one team track, without specifying the track_id, the api returns the following error when it should use the exercise already started:
```
{
    "error": {
        "type": "track_not_found",
        "message": "The track you specified does not exist",
        "fallback_url": "https://exercism.io/tracks"
    }
}
```

These are just a few errors I found. I recognize teams is newer, but having nicer error messages could go a long way as they are printed directly through the cli.

**Comment by iHiD** [comment] 2019-01-10 13:36
@Smarticles101 Thanks!
@kytrinyx Could you work out where the problem is with this and let me know if I need to fix anything in the API pls? :)

**Comment by ErikSchierboom** [comment] 2021-08-31 05:59
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 05:59 UTC
