### ISSUE TITLE
Waiting close to 3 monts for TypeScript track exercise feedback

### ISSUE THREAD

**Issue by paparomeo** [exercism/exercism#4866] opened 2019-05-27 20:54 UTC
My List Ops TypeScript exercise has been waiting for review for close to 3 months now (submitted on the 8th of March). Is this expected? Did it fall through the cracks? I would like to progress on the track. Any help is much appreciated.

https://exercism.io/my/solutions/f958057556064e05bf01a765f8cd1cd0

**Comment by iHiD** [comment] 2019-05-27 22:08
Closing as duplicate of #4867

**Closed by iHiD** 2019-05-27 22:08 UTC
