### ISSUE TITLE
Published solution preview is stale (shows old iteration)

### ISSUE THREAD

**Issue by michallepicki** [exercism/exercism#5651] opened 2021-09-02 07:56 UTC
I have a solution to [Elixir Lasagna exercise](https://exercism.org/tracks/elixir/exercises/lasagna/solutions?criteria=michallepicki) that I published an iteration for, and then changed it to a different one. Preview still shows the old iteration (in various places through the site, not only on that page). I even removed that iteration but it's still shown in preview.

**Comment by SleeplessByte** [comment] 2021-09-02 11:03
For @ErikSchierboom (and @iHiD): The snippet is incorrect, the page is correct.

**Comment by iHiD** [comment] 2021-09-03 01:12
Duplicate of https://github.com/exercism/exercism/issues/5690

Thanks all.

**Closed by iHiD** 2021-09-03 01:12 UTC
