### ISSUE TITLE
Published solution times are inaccurate

### ISSUE THREAD

**Issue by chriseyre2000** [exercism/exercism#5923] opened 2021-09-16 17:23 UTC
I just finished some Go exercises and my reputation dropdown is showing that I finished it 18 hours ago.
It's correct on the reputation page, and on the tracks, only wrong on the dropdown dialog.

**Comment by iHiD** [comment] 2021-09-16 19:48
Duplicate of https://github.com/exercism/exercism/issues/5620 - will be fixed soon 🙂

**Closed by iHiD** 2021-09-16 19:48 UTC
