### ISSUE TITLE
I can't do new exercises in my track

### ISSUE THREAD

**Issue by guygastineau** [exercism/exercism#4303] opened 2018-08-26 19:40 UTC
This is related to #4244 

This is technically a duplicate, but I have gotten no response from #4244 

I am wondering if this is a known bug.

I have added three exercises to the Bash track.  I have already completed the track.

The new exercises prerequisite exercises say they have unlocked these exercises, but they remain locked.

I would really like to do the exercises I have added to the track.  Please help or lets get this tracked as a bug if it isn't already.

Thanks.

closes #4244

**Comment by rpottsoh** [comment] 2018-08-26 19:43
see #3867

**Comment by guygastineau** [comment] 2018-08-26 19:51
@rpottsoh thanks for the link

I'm still confused though.  It seems like the solution in DEelphi became unlocked because of a one time script that was run my Jeremy.

Do you know where I can find information regarding the progress on a permanent solution for this?

Is this being actively tracked/ should I close this issue?

**Comment by kytrinyx** [comment] 2018-08-26 19:53
I know that it's on @iHiD's list to fix, so that the code that listens to the webhook and updates the track on the site also ensures that anyone who should have access to the new exercise does so.

**Comment by guygastineau** [comment] 2018-08-26 20:07
Thanks for the information @kytrinyx 

I guess I'll go ahead and close the issues I have that are related to this.

**Comment by kytrinyx** [comment] 2018-08-26 20:29
@iHiD might have a tracking issue for this. I'll let him point you to it if so!

**Comment by guygastineau** [comment] 2018-08-26 20:34
Thank you.  I'll wait to hear from him and then I'll close this.

:smile:

**Comment by iHiD** [comment] 2018-08-26 23:03
Closing as duplicate of https://github.com/exercism/exercism/issues/3867 - I've added the `priority/high` flag to that. It's a hard one to fix, but I'll prioritise it this week.

**Closed by iHiD** 2018-08-26 23:03 UTC

**Comment by guygastineau** [comment] 2018-08-27 00:02
Thank you @iHiD
