### ISSUE TITLE
Access to the uncompleted exercises by the url

### ISSUE THREAD

**Issue by Hiyorimi** [exercism/exercism#4212] opened 2018-08-09 16:05 UTC
I emailed about this back to Jeremy, but I got auto response to open an issue, hope, that would be helpful. I found a bug allowing to peek into solutions for unsolved exercises. It is reproducible:

Step 1: access solutions for the completed exercise, f.e: https://exercism.io/tracks/go/exercises/parallel-letter-frequency/solutions
Step 2: guess the slug part for the yet unsolved exercise, f.e: Robot Name
Step 3: access url https://exercism.io/tracks/go/exercises/robot-name/solutions
Step 4: peek the solutions.

**Comment by PatrickMcSweeny** [comment] 2018-08-10 15:33
You don't even have to guess the url if you just access the exercises page for a particular track while logged out. You can just click on any exercise and view all of the solutions.

https://exercism.io/tracks/go/exercises

**Comment by iHiD** [comment] 2018-08-10 16:12
Hi @Hiyorimi. Thanks for reporting (and for coming to me privately first). This is a feature, not a bug. We want solutions to be accessible externally and want search engines to be able to crawl them easily. If people really **want** to "cheat", then I don't think they'll get much value from Exercism. There's no external reward from using the platform so if people just choose to do that, then they'll lose out. As such, I'm going to close this, but thanks for reaching out.

**Closed** 2018-08-10 16:13 UTC
Labels: type/wontfix
