### ISSUE TITLE
docs: text missing in `/about`

### ISSUE THREAD

**Issue by AgataMaria** [exercism/exercism#6042] opened 2021-10-17 00:23 UTC
Hi, just wanted to let you know -> 
Some text is missing in [about](https://exercism.org/tracks/typescript/about) > Key Features of Typescript > Consistently Good Tooling **in desktop version**. 
It seems to be dropping after the 'and', should be 'and features' - which **is visible when you change the viewport size**

(full width)
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/36129701/137605245-0e3d53f2-1b76-4608-a13c-d68726617a61.png">

(smaller viewport)
<img width="575" alt="image" src="https://user-images.githubusercontent.com/36129701/137605357-a546fe73-eb4d-4b1f-8c1f-fae7ce935b6d.png">

**Comment by angelikatyborska** [comment] 2021-10-17 11:15
This is a duplicate of https://github.com/exercism/exercism/issues/5883

Make sure to subscribe to that issue to get updates about it. I'll close this one.

**Closed by angelikatyborska** 2021-10-17 11:15 UTC
