### ISSUE TITLE
Cant reply to a comment on a community solution

### ISSUE THREAD

**Issue by martinfreedman** [exercism/exercism#4414] opened 2018-10-11 14:45 UTC
For example:

https://exercism.io/tracks/csharp/exercises/bracket-push/solutions/8c7f29d4ccf349679c9e6db4a39c562e

**Comment by iHiD** [comment] 2019-01-22 21:06
Closing as duplicate of https://github.com/exercism/exercism/issues/4400

**Closed by iHiD** 2019-01-22 21:06 UTC
