### ISSUE TITLE
Create new track for Solidity

### ISSUE THREAD

**Issue by LivingLand** [exercism/exercism#6427] opened 2022-07-04 13:35 UTC
Good morning, Exercism team! 

I'm so excited to be here with you!  

As a serial entrepreneur, I've always hired programmers to create smart contracts for me.  At $70-100 per token, I knew I was being shamelessly used but it was more efficient than to learn the skills myself at the time.  

I'm the founder and CEO of New Coast Collaborative Finance, [nccf.io](http://nccf.io) .  We re-invented a new way of thinking of currency that I think will save the world's currencies:  by taking our labour time off the gold standard, off the fiat and petrol and national currency standards and onto something that has stable value and relevance to good work in the world, we want to impress upon people that the good work in our lives is stable, valuable, and can be used as currency.   We want to teach people to make their own Utility Tokens.  

So I made a common mistake:  I just expected Exercism to have a Solidity track.  

I was referred by some of my Microsoftian compsci brainy friends to Exercism as the entry-friendliest option for programming that they knew of, and you have definitely delivered on that.   

I was surprised and disappointed that Solidity is not in your Track offerings, and my first thought is that maybe I was referring to the wrong thing.  Solidity might be the software package?  Maybe Rust was the language that I was looking for? 
(Yes, I'm JUST THAT NEW.)

Anyway, a long story short:  I would like to learn ETH and BSC token programming, and I wonder what languages I should be learning, if not Solidity.  And I hope that if you're thinking what I'm thinking, that smart contract track support is high on the priority list to support.  

Many, many thanks for Version 3.   I didn't see Version 2 but this one looks bright, friendly and is quite approachable even by a newbie entrepreneur who's afraid to hit a key for fear of breaking the internet. 

Lots of love and gratitude, 
Livingland

**Comment by LivingLand** [comment] 2022-07-04 13:35
Solidity ! 
     Solidity !

**Comment by glennj** [comment] 2022-07-04 14:06
This is a duplicate of #6165 

The solidity track has been started (https://github.com/exercism/solidity), but not much work has been done. If you'd like to pitch in and contribute, have a look at https://exercism.org/docs/community/contributors

**Closed** 2022-07-05 09:44 UTC
Labels: type/duplicate
