### ISSUE TITLE
Create new track for [LANGUAGE]

### ISSUE THREAD

**Issue by Starblue0** [exercism/exercism#6165] opened 2021-12-21 20:22 UTC
Are you able to add Solidity?

**Comment by angelikatyborska** [comment] 2021-12-22 15:31
This is a duplicate of https://github.com/exercism/exercism/issues/5417 and https://github.com/exercism/exercism/issues/5417

@ali2251 already requested this in 2020 (https://github.com/exercism/request-new-language-track/issues/80) and did some work: https://github.com/exercism/solidity

If you want to help out, check out that repository. Unfortunately it doesn't have any track-specific activity in the last 12 months, so you would be on your own when it comes to Solidity-specific decisions. You can tag the team https://github.com/orgs/exercism/teams/reviewers whenever you need Exercism-specific help.

**Closed by angelikatyborska** 2021-12-22 15:31 UTC
