### ISSUE TITLE
Go workspaces require symlinks; exercism tool does not respect these

### ISSUE THREAD

**Issue by coriolinus** [exercism/exercism#3719] opened 2018-02-02 14:52 UTC
Go requires that all go code be part of a workspace; it explicitly recommends that all go code for a given user be located in one canonical go path, configured in the user's `.profile`. It's technically possible to configure multiple workspaces per user, but it's a huge hassle and not really worth it.

Exercism requires all exercism work to be part of one canonical directory tree. This is fine.

Bonus issue: I develop in a linux environment on a Windows machine for reasons which are out of scope for this issue. WSL internal paths are opaque to windows, but windows paths are automounted within WSL. Therefore, for maximum flexibility, things are configured as follows:

- A directory exists `D:\Users\coriolinus\Documents\Projects`
- A symlink exists `~/projects -> /mnt/d/Users/coriolinus/Documents/Projects`
- A subdirectory of the projects directory exists: `exercism.io`; it contains all my exercism work.

All of this worked very well until I started working on go exercises. After some initial fumbling, I decided that the canonical go workspace should be in `Projects/go`. I then configured the following so that it would actually compile:

```shell
$ pwd; readlink -f go
/home/coriolinus/projects/exercism.io
/mnt/d/Users/coriolinus/Documents/Projects/go/src/exercism
$ echo $GOPATH; readlink -f $GOPATH
/home/coriolinus/projects/go
/mnt/d/Users/coriolinus/Documents/Projects/go
```

However, having done that, the exercism command no longer works:

```text
exercism.io/go/parallel-letter-frequency$ exercism submit frequency.go
2018/02/02 15:25:06 Unable to submit - Unable to identify track and file.

It seems like you've tried to submit a solution file located outside of your
configured exercises directory.

Current directory:      D:\Users\coriolinus\Documents\Projects\go\src\exercism\parallel-letter-frequency
Configured directory:   D:\Users\coriolinus\Documents\Projects\exercism.io

Try re-running "exercism fetch". Then move your solution file to the correct
exercise directory for the problem you're working on. It should be somewhere
inside D:\Users\coriolinus\Documents\Projects\exercism.io

For example, to submit the JavaScript "hello-world.js" problem, run
"exercism submit hello-world.js" from this directory:

D:\Users\coriolinus\Documents\Projects\exercism.io\javascript\hello-world

You can see where exercism is looking for your files with "exercism debug".
```

As it happens, this is within the configured exercises directory from my perspective within WSL, but not from the Windows perspective. That suggested an answer: just install the real linux client within the WSL environment; it should know about symlinks.

Unfortunately, after installing and configuring the linux client, things still don't work:

```shell
~/projects/exercism.io/go$ exercism submit parallel-letter-frequency/frequency.go
2018/02/02 15:37:59 unable to submit - Unable to identify track and file.

It seems like you've tried to submit a solution file located outside of your
configured exercises directory.

Current directory:      /home/coriolinus/projects/exercism.io/go
Configured directory:   /mnt/d/Users/coriolinus/Documents/Projects/exercism.io

Try re-running "exercism fetch". Then move your solution file to the correct
exercise directory for the problem you're working on. It should be somewhere
inside /mnt/d/Users/coriolinus/Documents/Projects/exercism.io

For example, to submit the JavaScript "hello-world.js" problem, run
"exercism submit hello-world.js" from this directory:

/mnt/d/Users/coriolinus/Documents/Projects/exercism.io/javascript/hello-world

You can see where exercism is looking for your files with "exercism debug".

~/projects/exercism.io/go$ exercism debug

**** Debug Information ****
Exercism CLI Version: 2.4.1
Exercism CLI Latest Release: 2.4.1
OS/Architecture: linux/amd64
Build OS/Architecture linux/amd64
Home Dir: /home/coriolinus
Config File: /home/coriolinus/.exercism.json
API Key: 1fde*************************57e
Exercises Directory: /home/coriolinus/projects/exercism.io/
Testing API endpoints reachability
        * GitHub API: https://api.github.com/ [connected] 123.8373ms
        * API: http://exercism.io [connected] 234.3779ms
        * XAPI: http://x.exercism.io [connected] 282.8597ms
```

I'm looking for a configuration which has the following properties:

- All go code, within and without WSL, ends up in a single go workspace as required by go
- All exercism code, within and without WSL, ends up in a single exercism directory tree as required by exercism
- I am not required to move the exercism root inside of `GOPATH`
- Golang tools work
- Exercism tools work

My current configuration of symlinks has all those properties but the last. I believe the best way to accomplish this would be to change the behavior of the exercism tool. Ideally, it wouldn't recursively unwrap symlinks; it would just take as given the output of `pwd`.

**Comment by NobbZ** [comment] 2018-02-03 23:33
This exercises do work without beeing in the go workspace and shouldn't not thrown into it, they just pollute it. 

Also in general I'm not conform with the single workspace suggestion as it makes the already hard reproducible builds in go near to impossible. Especially updating project a breaks unrelated project b, because a shared dependency c got updated.

But I'm not related to the go track, cc @exercism/go

**Comment by coriolinus** [comment] 2018-02-04 00:27
- I'm not a fan of the single workspace thing either, but it AFAICT it's the community consensus among programmers in that language for reasons which appear to be primarily historical. See [here](https://dave.cheney.net/2016/12/20/thinking-about-gopath).
- Certain go tools refuse to operate on code which is not in GOPATH. Whatever it is that VSCode uses for refactoring is in that category.
- Due to WSL being WSL, everything needs to live in the Windows-native filesystem in order for me to use a GUI editor. While I admit that it would be more hardcore to use emacs or vim, in practice Atom and VSCode are more comfortable. This means that everything must be a symlink in the end anyway; the only question is at which point the OS resolves it.

**Comment by tleen** [comment] 2018-02-04 01:37
I'm using VS Code  with the full Go toolset on the exercises outside of my workspace and have had no issues.

**Comment by coriolinus** [comment] 2018-02-04 09:24
![go-outside-gopath](https://user-images.githubusercontent.com/7822926/35776049-5e2588f2-0995-11e8-9469-87b85aae6361.png)

This happens when I attempt to rename a variable outside GOPATH. It works fine when the project is within that path.

**Comment by kytrinyx** [comment] 2018-02-24 19:09
@coriolinus The only time you need to have Go code within the canonical workspace, is if you need to use imports. Exercism only uses code from the standard library, and therefore doesn't need to be within the GOPATH.

I've contributed to a number of Go projects (including Go itself)—I am quite familiar with the community consensus, but there really is no reason to do this with Exercism exercises. It adds complexity and hassle for no benefit that I can determine.

I would recommend that you remove the various symlinks that you have in place trying to comply with the single Go workspace thing and see if that simplifies matters for you.

**Comment by iHiD** [comment] 2018-08-01 22:37
@kytrinyx Can we close this?

**Comment by kytrinyx** [comment] 2018-08-10 21:31
Yeah, I don't think we have anything else we can do here.

**Closed by kytrinyx** 2018-08-10 21:31 UTC
