### ISSUE TITLE
Reputation notification timestamp incorrect

### ISSUE THREAD

**Issue by tsvng** [exercism/exercism#5733] opened 2021-09-03 17:28 UTC
As you can see in my attached screenshot, the reputation notification where I published my solution to **Hello World** in **Python** says it occurred 10 hours ago; when in reality the solution page itself shows that it was submitted 23 minutes ago.

![image](https://user-images.githubusercontent.com/24418304/132044727-8ac19bc7-a294-4934-99e4-c37f6f62be53.png)

**Comment by angelikatyborska** [comment] 2021-09-03 17:31
This is a duplicate of https://github.com/exercism/exercism/issues/5620, I'm closing

**Closed by angelikatyborska** 2021-09-03 17:31 UTC
