### ISSUE TITLE
Code not lining up with line numbers

### ISSUE THREAD

**Issue by edhaz** [exercism/exercism#4350] opened 2018-09-15 15:25 UTC
In dark mode, lines of code don't match up with the line numbers as the numbers get higher (screenshot attached) when viewing a submitted solution.
<img width="625" alt="screen shot 2018-09-15 at 16 24 44" src="https://user-images.githubusercontent.com/31481469/45587896-01712480-b904-11e8-89b8-c7efbf48e89e.png">

Update: I have just checked 'not dark mode' and the same thing is also occurring.

**Comment by iHiD** [comment] 2018-10-03 18:14
Thanks. This used to work so I imagine a change in the code when we added dark-mode has changed something. I've added the `community-pr-welcome` label to this :)

**Comment by sfairchild** [comment] 2018-10-04 13:09
@edhaz what browser/OS are you seeing this on? Also what page/section are you seeing this on? In chrome and safari on macOS it looks normal. Maybe it is a browser compatibility issue that needs to be fixed.

**Comment by edhaz** [comment] 2018-10-05 16:33
@sfairchild Just did a bit of checking, currently on macOS Mojave 10.14, using Safari 12.0 works fine (recently switched browser). The misalignment is on chrome Version 69.0.3497.100 (just checked it, still on macos).

**Comment by sfairchild** [comment] 2018-10-05 16:58
hmmm, maybe I am looking at the wrong location. I am on macos 10.13.6 and when I check chrome Version 69.0.3497.100
![exercism io_my_solutions_0acbb0b169814e6d923dff2a7131916d](https://user-images.githubusercontent.com/1839202/46548581-82856100-c89d-11e8-96e7-bdc3c912e6b4.png)
This is under my solution of "bob" in the elixir track, I have also checked in the mentor section and other solutions and can't reproduce. What language is that solution from? Have you tried other tracks/languages to see if you see the same result? Could you maybe have a chrome plugin that is messing with your styling?

@iHiD Are you able to reproduce this?

**Comment by iHiD** [comment] 2018-10-05 17:05
No I'm not. Both personal and mentored views look fine to me. How weird.

**Comment by edhaz** [comment] 2018-10-05 17:40
So just checked on my Linux machine on chrome, lines up fine. It just seems to be chrome on macOS, did a hard reload removing cache etc but no change.

**Comment by iHiD** [comment] 2018-10-05 17:49
Same issue in Chrome incognito?

**Comment by edhaz** [comment] 2018-10-06 10:50
Just tried on incognito and still the same error.

**Comment by mrtnmgs** [comment] 2018-11-05 16:51
I can see the misalignment when I zoom in in Chrome (zooming works fine in Firefox).
I'm on OSX 10.13.6 High Sierra running FF v.63.0.1 and Chrome 70.0.3538.77

**Comment by sfairchild** [comment] 2018-11-13 18:22
Your right, I see it when I zoomed to 110% on chrome running macOS 10.14, but 100% looks fine.

It seems to be a styling issue with prismjs https://github.com/PrismJS/prism/issues/1231. There is probably something in the sites styling that seems to be adding some slight extra height to each line that adds up by the end of the code block. I can probably look into this weekend unless someone else wants a crack at it.

**Comment by iHiD** [comment] 2018-11-14 23:34
Looks like you already have a copy of the database in the db you're running it on. `rake db:drop` and  `rake db:schema:load` should get you clean.

**Comment by mrtnmgs** [comment] 2018-11-15 14:42
Thanks Jeremy. I dropped the db and recreated it. I have a new error, Redis can't connect. Any idea how to fix?

```
Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
...
Caused by:
Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:6379
...
Caused by:
IO::EINPROGRESSWaitWritable: Operation now in progress - connect(2) would block
```

**Comment by sfairchild** [comment] 2018-11-15 16:15
do you have redis installed and is it running? 

@iHiD I just looked at the website README and it looks like installing redis is missing from the https://github.com/exercism/website#things-to-install.

**Comment by mrtnmgs** [comment] 2018-11-15 16:48
oops sorry about that. I thought I have. Should have checked. I'll submit a PR to update the README. Thanks Sean.

**Comment by sfairchild** [comment] 2018-11-15 16:54
I already created a PR that just needs to be merged https://github.com/exercism/website/pull/459

**Comment by mrtnmgs** [comment] 2018-11-15 22:20
I'm not sure how to unlock the tracks to access the solutions page and work on this issue. The README provides [a code snippet](https://github.com/exercism/website#unlock-first-exercise-for-each-user-track) but I don't know what to do with it. I tried in a Rails console and to run a task but `user_track_ids` is undefined.

**Comment by sfairchild** [comment] 2018-11-16 20:29
@mrtnmgs, If you need help figuring this out let me know. I am free tomorrow and can help with this.

**Comment by mrtnmgs** [comment] 2018-11-20 19:39
Thanks @iHiD and @sfairchild ! Just getting back to this now. I did have the tracks and with Jeremy's answer I could unlock a solution.  Do you want me submit a PR to update the README with the way to unlock the solutions?
When I unlock a solution, the 'Solution' tab appears but is empty. Not a big deal because I can reproduce the issue in the 'Test suite' tab...
![screenshot_2018-11-20 javascript zipper exercism](https://user-images.githubusercontent.com/16521819/48798136-f35bcd80-ecd1-11e8-8c6d-614fb93036e3.png)

**Comment by uzilan** [comment] 2019-09-18 18:31
![rwolines](https://user-images.githubusercontent.com/212351/65175463-33572280-da53-11e9-9d5f-678f002b2a09.jpg)
Same issue in my mobil - iPhone, Chrome

**Comment by brugnara** [comment] 2021-02-02 16:59
Hi.

I noticed this happens when the page has a zoom different from 100%.

Screenshot at 125%:

![image](https://user-images.githubusercontent.com/2781191/106634523-24a5d880-6580-11eb-967a-74806d82ce6e.png)

Screenshot at 100%:

![image](https://user-images.githubusercontent.com/2781191/106634633-41421080-6580-11eb-8aee-33c02e3a4e0c.png)

Hope this helps.

**Comment by ErikSchierboom** [comment] 2021-08-31 05:57
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 05:57 UTC
