### ISSUE TITLE
Command line instructions readability 

### ISSUE THREAD

**Issue by uzilan** [exercism/exercism#4397] opened 2018-10-06 05:32 UTC
The command line interface page instructions are barely readable since they are rendered as near-white text on light gray background. Here's how it looks like on my screen:
 
<img width="730" alt="command line poor visibility" src="https://user-images.githubusercontent.com/212351/46567765-4dc6e780-c939-11e8-9b42-131cd0bb8009.png">

**Comment by rpottsoh** [comment] 2018-10-06 14:32
Thank you for posting this issue.  My eyes could really use a break too!

**Comment by PatrickMcSweeny** [comment] 2018-10-08 20:14
@uzilan Which browser are you using? It looks pretty readable on my screen.
![screenshot from 2018-10-08 16-13-24](https://user-images.githubusercontent.com/1254212/46631393-3e03fa80-cb15-11e8-80e7-5818a2376d32.png)

**Comment by rpottsoh** [comment] 2018-10-08 20:23
Mine looks like @uzilan's example.  Chrome on Windows 7 for me.  @PatrickMcSweeny what you posted in your comment looks very nice....

**Comment by PatrickMcSweeny** [comment] 2018-10-08 21:20
Hm, I'm not able to reproduce the bug locally but I'm guessing it is being caused by the white text-shadow so I got rid of that in my pull request.

**Comment by rpottsoh** [comment] 2018-10-08 22:41
Chrome on my Windows 10 system is also equally hard to read, however, Firefox on the same Windows 10 system is just fine.

**Comment by uzilan** [comment] 2018-10-08 22:45
Chrome on mac and on iphone x - both are quite unreadable.

**Comment by iHiD** [comment] 2018-10-08 22:45
Which page is this on?

**Comment by rpottsoh** [comment] 2018-10-08 22:47
New information.  It is messed up looking if I am signed in.  It is fine if I am logged out.

url is https://exercism.io/cli

**Comment by rpottsoh** [comment] 2018-10-08 22:48
If I am signed in it is hard on the eyes for both Chrome and Firefox.  It is fine on both browsers if I am signed out.

**Comment by iHiD** [comment] 2018-10-08 22:50
Funky. So the code respects your setting for dark-mode, but the background does. @PatrickMcSweeny - can you change both to respect dark-mode in the same way as how the solution page works please? :)

**Comment by PatrickMcSweeny** [comment] 2018-10-09 20:31
[This bit of css](https://github.com/exercism/website/blob/master/app/assets/stylesheets/pages/generic-page.scss#L70) is definitely the culprit, which is being caused by #generic-page being an id selector which would override the .prism-dark selector. One possible fix for this would be to convert generic-page to a class so that it doesn't override this or other selectors.

**Comment by iHiD** [comment] 2018-10-09 22:17
@PatrickMcSweeny Thanks for tracking that down. Can we just remove that line of CSS? I'd rather that `generic-page` stayed as an id, as that fits in better with the pattern we use everywhere.

**Comment by PatrickMcSweeny** [comment] 2018-10-10 01:10
Okay, I got rid of that line.

**Closed** 2018-10-10 02:11 UTC
Labels: community-pr-welcome, type/bug
