### ISSUE TITLE
How to Publish Solution

### ISSUE THREAD

**Issue by confidentidiot** [exercism/exercism#4685] opened 2019-02-11 01:52 UTC
I am currently in the [D track](https://exercism.io/my/tracks/d) (self-study, or independent mode) and just completed the ETL exercise.  Normally, after I submit a solution, I can just click on the "Publish Solution" button any my solution is visible for all to see.  For some reason, after submitting the solution for the ETL exercise, I am told that "A mentor will check out your work and leave a comment here on your solution soon" and I don't have an option to just publish the solution.  Am I doing something wrong now?  As far as I can tell, there are [no mentors](https://exercism.io/tracks/d/mentors) in the D track.

**Comment by texastoland** [comment] 2019-02-14 22:47
This may be a duplicate of #4432.

**Comment by confidentidiot** [comment] 2019-02-15 15:18
I think it might be a duplicate.  Happy to have this closed since it's been linked to #4432.

**Comment by iHiD** [comment] 2019-02-17 18:54
Closing in favour of #4432.

**Closed by iHiD** 2019-02-17 18:54 UTC
