### ISSUE TITLE
Rust exercices concepts locked

### ISSUE THREAD

**Issue by darnuria** [exercism/exercism#6035] opened 2021-10-12 14:23 UTC
Hello,

I have one exercises locked on my rust concept track abut I fulfill all the requirement yet it suggest me to do something I have already done:

- Health Statistics (suggest me to do assembly line I already have done)

Other below may be OK because I haven't done the locked one above:

- Low-Power Embedded Game
- Role-Playing Game
- RPN Calculator
- Magazine Cutout

Screenshots:

![image](https://user-images.githubusercontent.com/2827553/136973352-075bd5eb-ab58-487a-b345-63d6f3ef46e8.png)

Suggested exercise already done:
![image](https://user-images.githubusercontent.com/2827553/136974488-7741ce58-fa6e-4543-8217-4d88afcd92d0.png)

My progression:

![image](https://user-images.githubusercontent.com/2827553/136973566-a8d7b38e-4a7a-4304-a1f7-0133ec722350.png)

I' checked out rust repository but i'am not fluent right now with exercism concept as a contributor to understand if the problem is there. :)

**Comment by angelikatyborska** [comment] 2021-10-15 06:32
I will close this issue because it's a duplicate of https://github.com/exercism/rust/issues/1357 

Make sure to subscribe to https://github.com/exercism/rust/issues/1357 if you want to get notified about updates!

**Closed by angelikatyborska** 2021-10-15 06:32 UTC
