### ISSUE TITLE
Feature request - dark mode 

### ISSUE THREAD

**Issue by ahmadateya** [exercism/exercism#6002] opened 2021-10-02 12:57 UTC
the V3 is awesome but it needs to have a dark mode

**Comment by SleeplessByte** [comment] 2021-10-02 16:04
Duplicate of https://github.com/exercism/exercism/issues/5748 and https://github.com/exercism/exercism/issues/5436.

It's on the roadmap!

**Closed by SleeplessByte** 2021-10-02 16:04 UTC
