### ISSUE TITLE
Side exercise without image on track page displayed weird

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#4416] opened 2018-10-12 07:38 UTC
![image](https://user-images.githubusercontent.com/135246/46854900-97fd0c80-ce02-11e8-9037-a252ec1d123b.png)

**Comment by iHiD** [comment] 2018-11-17 13:33
Going to close this as duplicate of #4460

**Closed by iHiD** 2018-11-17 13:33 UTC
