### ISSUE TITLE
"You've unlocked extra exercises" box should indicate which exercises are completed

### ISSUE THREAD

**Issue by hickford** [exercism/exercism#4809] opened 2019-04-13 13:11 UTC
It would be helpful if the "You've unlocked extra exercises" box distinguished which have been completed.

Currently it does not distinguish

![image](https://user-images.githubusercontent.com/105314/56079515-1b210e80-5df6-11e9-8ee8-953704755b57.png)

**Comment by hickford** [comment] 2019-04-13 13:13
It could do this by inverting the colours, as under 'extra exercises' below

![image](https://user-images.githubusercontent.com/105314/56080248-9686be00-5dfe-11e9-84a3-20c8025622e7.png)

**Comment by Stigjb** [comment] 2019-04-15 11:22
Agreed, see also #4444

**Comment by iHiD** [comment] 2019-04-15 12:09
Thanks for opening :) Closing as duplicate of #4444

**Closed by iHiD** 2019-04-15 12:09 UTC
