### ISSUE TITLE
Reputation timestamps in wrong timezone

### ISSUE THREAD

**Issue by Steffan153** [exercism/exercism#5860] opened 2021-09-10 01:32 UTC
![image](https://user-images.githubusercontent.com/40404519/132784355-7bff34f5-136b-465e-81fa-b9ad6bee334d.png)

I'm UTC-6.

**Comment by iHiD** [comment] 2021-09-10 07:37
Duplicate of https://github.com/exercism/exercism/issues/5860 when @kntsoriano is fixing :)

**Closed by iHiD** 2021-09-10 07:37 UTC

**Comment by Steffan153** [comment] 2021-09-10 14:14
It's a duplicate of itself?? :joy:

**Comment by angelikatyborska** [comment] 2021-09-11 13:25
Haha, I think @iHiD meant https://github.com/exercism/exercism/issues/5620 :D

**Comment by iHiD** [comment] 2021-09-13 11:27
I did!
