### ISSUE TITLE
Home page responsive rendering of a picture incorrect.

### ISSUE THREAD

**Issue by DjangoFett** [exercism/exercism#6217] opened 2022-02-03 00:09 UTC
Viewing the browser from an iPhone 12 on Safari seems to have a couple elements re-size to the screen in an awkward manner. This has been confirmed with two different phones. I am unsure if affects other iPhone versions or Android.
Edit: Doesn't quite look as bad when I posted it here, but it's still not great.

![render_ios_12_safari_2](https://user-images.githubusercontent.com/2284834/152258824-d0eb0943-d20c-499f-964d-a4af59dffb07.png)
![render_ios_12_safari_1](https://user-images.githubusercontent.com/2284834/152258831-cc5f8d4c-95b4-47b4-be64-6aa450a631e2.png)

**Comment by SleeplessByte** [comment] 2022-02-03 16:32
Thanks for reporting. 

Technically a duplicate of https://github.com/exercism/exercism/issues/6036 and https://github.com/exercism/exercism/issues/6188

**Closed by SleeplessByte** 2022-02-03 16:32 UTC
