### ISSUE TITLE
Reputation isn't fully credited (or it's spread across multiple people)

### ISSUE THREAD

**Issue by joshgoebel** [exercism/exercism#5608] opened 2021-09-01 15:20 UTC
I'm listed at least twice in the list that I see:

- ajoshguy (my Exercism ID, which has all my mentoring rep)
- yyyc514 (my old GitHub, has some reputation)

My new GitHub [renamed] (which I've done all my recent Exercism contrib under) is `joshgoebel`, but I don't see any PR credit for any of my recent work on Wren track/stuff.

Are there some YAML files I need to edit perhaps to update yyyc514 to joshgoebel? (not sure if that's still a thing with v3)

<img width="619" alt="Screen Shot 2021-09-01 at 11 18 51 AM" src="https://user-images.githubusercontent.com/6473/131698187-14ea8b20-4447-4790-967b-e53524c4f819.png">

---

Not sure if this is just me or might be a more general issue.

**Comment by bobahop** [comment] 2021-09-01 16:58
I second that. I would think my bobahop GitHub activity on mostly Rust and one or two other tracks would have been worth some contribution points for my Exercism bobahop.

**Comment by IsaacG** [comment] 2021-09-01 16:59
+3 :) 
There was a Python exercise I wrote that was tagged major

**Comment by iHiD** [comment] 2021-09-01 20:08
If you've not logged in through GitHub on the website, the reputation gets awarded. From what I can tell, neither @bobahop nor @IsaacG do. So we need an additional setting for you to link your GH and Exercism accounts for them to get merged.

Josh's issue is a bit more complex as he has two GH account that he would like merged into one thing.

I think we need:
- A feature request for (1)
- A josh-specific fix for (2)

**Comment by joshgoebel** [comment] 2021-09-01 20:11
> he has two GH account that he would like merged into one thing.

Not really... 

My GitHub account is `joshgoebel`.  It used to be `yyyc514` and was renamed.   The `yyyc514` of today is a NEW account I created to serve as a pointer.  But I don't know about any historic data (on GH side or on Exercism's side).

**Comment by joshgoebel** [comment] 2021-09-01 20:12
> If you've not logged in through GitHub on the website, the reputation gets awarded.

Does or doesn't?

**Comment by SleeplessByte** [comment] 2021-09-01 20:33
Does.

**Comment by IsaacG** [comment] 2021-09-01 22:04
What's the best way to associate my Exercism account with my GitHub account? Should I log into Exercism with GitHub then request a merge?

**Comment by SleeplessByte** [comment] 2021-09-01 22:36
@IsaacG I think that @iHiD is creating a button on the profile settings to do exactly that. I recommend waiting for it :)

**Comment by IsaacG** [comment] 2021-09-24 23:22
Any ETA or updates on this issue?

**Comment by iHiD** [comment] 2021-09-25 11:26
Not yet. Sorry.

**Comment by endlesslycurious** [comment] 2021-11-03 23:01
I just hit this issue too it seems:

- I login to exercism with email not GitHub
- I don't have a public profile setup
- I submitted https://github.com/exercism/go/pull/1923 to add extra tests to simple-linked-list on the go track which was accepted
- In the PR I updated the json config for the exercise, adding my Exercism username `EndlesslyCurious` to the contributors list

Yet I don't see myself on the contributor list on the [exercise page](https://exercism.org/tracks/go/exercises/simple-linked-list) and I don't see any points awarded either.

**Comment by IsaacG** [comment] 2021-11-04 00:03
That makes sense. Anyone with the same setup should see the same thing.

**Comment by iHiD** [comment] 2021-11-11 11:44
@bobahop @IsaacG @endlesslycurious I've manually linked your accounts. Josh - I still don't have a solution for you, sorry.

**Comment by joshgoebel** [comment] 2021-11-11 13:09
What makes me the edge case again, because my account name changed?

**Comment by iHiD** [comment] 2021-11-11 13:22
Because you have two GH accounts that need to be linked to one Exercism account:
- https://github.com/yyyc514
- https://github.com/joshgoebel

**Comment by joshgoebel** [comment] 2021-11-11 13:38
Again, (just to be clear) only `joshgoebel` [should be] relevant.  It was `yyyc514` then I renamed it to `joshgoebel` per your suggestion.  I only re-created `yyyc514` as a 302 redirect to my new account.  If I hadn't created the redirect account I would have a singular GH account...  there was certainly a time when `joshgoebel` solo existed WITHOUT the redirect account.

If just deleting the redirect account would fix this I could consider that... but I don't think that would help - so anytime I hear it phrased as "you have two GitHub accounts" I frown slightly as I don't think it's that simple.

**Comment by iHiD** [comment] 2021-11-11 15:57
OK, thanks for explaining that. I hadn't understood it properly.

I've looked more into it now. The issue is that there is an Exercism account linked to your GitHub user (Exercism handle: "yyyc514"), which has your GitHub Rep attached, and your normal "ajoshguy" account, which has your in-Exercism rep.

So effectively I need to repoint all those things from one account to the other, which is fine, but we just don't have scripts for it, so it's work. But it's something we should do for this scenario in general.

**Comment by iHiD** [comment] 2021-11-23 16:03
https://github.com/exercism/website/pull/2180 adds the button for the normal state.

**Comment by jamessouth** [comment] 2021-12-10 00:10
I used this button and got 60 reps (5x12) for 5 PRs merged (2 on website copy and 3 on Go), but the website is not aware of my authorship of the [3 Go concepts](https://github.com/exercism/v3/commits?author=jamessouth) which prompted the PRs. Can someone review please? :) Exercism name == GH name.

**Comment by iHiD** [comment] 2021-12-10 11:10
@ErikSchierboom Do you know if authorships get recalculated in our weekly check thing? I'm imagining they also need adding to the script that syncs up users' data when they GH sync.

**Comment by ErikSchierboom** [comment] 2021-12-10 13:12
They do. They are updated as part of the track syncing, which also syncs the exercises and its authors.
It runs on:

```
# 1am Wednesday
sync_tracks:
  cron: "0 1 * * 3"
  class: "SyncTracksJob"
  queue: dribble
```

> I'm imagining they also need adding to the script that syncs up users' data when they GH sync.

Ehm, let me think. We don't really know which exercise would need their authorship to re-calculate, as that information is only stored in the exercise's `config.json` file and we'd thus need to re-sync all exercises to update the authorships. What we could perhaps do, is have a separate job to only update the authorship/contributorship of exercises/concepts, without syncing the rest of the exercise.

**Comment by iHiD** [comment] 2022-05-10 15:48
I believe this is now fixed for everyone other than @joshgoebel and @jamessouth.
1. Is that correct?
2. @ErikSchierboom Could you solve this for Josh and James please, either by giving them instructions, or by fixing whatever needs fixing in the db. Thanks!

**Comment by ErikSchierboom** [comment] 2022-05-25 07:21
@joshgoebel The problem was that there are two users in our database: `ajoshguy` and `yyyc514`. Weirdly, the latter had its github username set to `joshgoebel`, and not to `yyyc514`. The former didn't have a github username, which is why the experience was awarded wrongly. I've just correct this in the database and recalculated your reputation. Looking at https://exercism.org/contributing/contributors?track_slug=wren, that looks a lot more sane to me. @joshgoebel?

**Comment by ErikSchierboom** [comment] 2022-05-25 07:25
@jamessouth Your authorship count is now fixed:

![image](https://user-images.githubusercontent.com/135246/170205008-2b53d46c-81b8-44ea-b3b5-68ce696a8ca1.png)

**Comment by joshgoebel** [comment] 2022-05-25 10:10
Is this a permanent change, vs something that will accidentally unwind in the future?

@ErikSchierboom   I was mostly looking at my https://exercism.org/profiles/ajoshguy page... but yes, it looks a lot more complete now, thanks!  Sadly, I think there is one more (related) issue here, but I think this one from my perspective seems closed.

**Comment by ErikSchierboom** [comment] 2022-05-25 10:51
> Is this a permanent change, vs something that will accidentally unwind in the future?

This is a permanent change.

> Sadly, I think there is one more (related) issue here, but I think this one from my perspective seems closed.

What is the related issue?

**Closed** 2022-05-25 10:51 UTC
Labels: type/janitorial

**Comment by jamessouth** [comment] 2022-11-28 00:54
Thank you!
