### ISSUE TITLE
Students with multiple solutions in mentor queue

### ISSUE THREAD

**Issue by emcoding** [exercism/exercism#4234] opened 2018-08-14 09:44 UTC
Copied from Slack
Me: My dashboard has 2 or 3 or even more imported solutions by the same students. It feels a bit unfair that 1 student get several submissions, while others may be waiting for 1 side exercise.

@ihid: 
The multiple submissions from the same student is because students can submit as many side exercises as they want while waiting for core to be prioritised. I'll make it so only one appears in the queue at a time.

Me: Yay!

**Comment by F3PiX** [comment] 2018-08-20 22:30
@ihid The label says it's on the roadmap but I don't see it listed on THE Roadmap?

**Comment by iHiD** [comment] 2018-08-21 12:42
I've changed this to be a bug. It basically just needs a group by clause as a first pass I think.

**Comment by PureRonin** [comment] 2018-09-27 07:55
> Is there a way to modify the mentor dashboard queue? There seems to be bursts of solutions from the same people as they do extra exercises and I'd rather not review a second task from the same person while I wait for them to respond to the first one since it's often the same issues I have with them. Ideally I'd like the "Next solutions to mentor" queue to not contain any solutions from users who have solutions in my "Solutions you're mentoring" with the "Waiting for them" status. 

So I have copied by question from the slack, since this seems like it might be the same thing? If it is, cool I look forward to seeing it. If not, I can create a new issue.

Thanks,
PR.

**Comment by BethanyG** [comment] 2019-01-31 21:34
Tacking on here to avoid duplication. 

The issue we're seeing may be a separate one, so if it is please let me know and I will move it to it's own report.

In [**This Slack Thread**](https://exercism-team.slack.com/archives/CAQP7JL3T/p1548845079221500) and [**This one**](https://exercism-team.slack.com/archives/CARRG4MNC/p1548921422218100), there's discussion around multiple solutions from the same student showing up in the mentor queue at the same time.  It's probably because the student in question switched from independent mode to mentored mode, but if it **is**, there should be some flag or process so it doesn't confuse both the mentors and the students it happens to.  Right now, it's been observed in Python and Ruby tracks.  UUIDs for Python below, Ruby to follow:

[**SpooksMcGoose**](https://exercism.io/profiles/SpooksMcGoose) in the Python Track
<details>
<summary>


</summary>

![python_queue_2019-01-30at11_54pm](https://user-images.githubusercontent.com/5923094/52086807-aceddf00-255c-11e9-9649-3cc0bbb290e3.png)


* https://exercism.io/mentor/solutions/ee17fc12a2114f78ac0c2ac580549a8f
* https://exercism.io/mentor/solutions/a93b61fc5cc84d1e891c473f82e2323b
* https://exercism.io/mentor/solutions/03e2285b18224a1ea791964f19e9c145
* https://exercism.io/mentor/solutions/224e0c5b01124fd5966ed8c5b30e96d5
* https://exercism.io/mentor/solutions/1c238fbfb97541dcb14035b06fd543eb
* https://exercism.io/mentor/solutions/377a81fa61d14f139ed6922aaf0e57a2

</details>

**Comment by F3PiX** [comment] 2019-01-31 21:46
These have always been core  
49be4a742a5d4b278f78bfe37f0f78b8
e548daf67bfd42a2ab623de15cb2334e
a267c6be43614eb2831b0b42e0a0eddd

But this one is High Scores: first non-existing, then side, then promoted to core
Maybe there's some side effect with locking later exercises 😕 . 
5c8e75af1ab64110b511b3b85c5c7515

**Comment by F3PiX** [comment] 2019-01-31 21:59
_cross posting_ 
Maybe :grimacing: the bigger issue is: can we make it such that only one core exercise at the time of a certain user can show up in the Mentor Queue? Meaning, we don’t have to block the unlocking depending on all the states, we just manage the queue. ???

**Comment by F3PiX** [comment] 2019-01-31 22:08
_cross posting from Slack, for future reference_
If the problem is because of the 'completed unapproved' option, it may be worth to check if the numbers of 'completed unapproved' went down after the new feature with ‘stale’ mentors (= putting abandoned solutions back in the queue)? If they are going down, the problem is real small.

**Comment by ErikSchierboom** [comment] 2021-08-31 05:56
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 05:56 UTC
