### ISSUE TITLE
Right clicking and selecting `Open Link in New (Tab|Window)` in Safari directs to wrong page

### ISSUE THREAD

**Issue by atfelix** [exercism/exercism#4723] opened 2019-02-23 16:48 UTC
System Info: 
- Browser:  Safari 12.0
- OS:  macOS Mojave 10.14
 
Steps to Reproduce:

1. Go to the Swift language track (https://exercism.io/my/tracks/swift)
2. Ensure that you have status bar enabled
3. Hover over an unsolved problem
4. If the status bar shows a link of the form `https://exercism.io/my/solutions?exercise_id=linked-list&track_id=swift`, then Right click or Ctrl-click on the problem and select `Open in New Tab` or`Open in New Window`

Expected Result:
The new tab or window opens the problem

Actual Result:
The new tab or window opens to your completed solutions page (see the attached screen shot)

<img width="1440" alt="screen shot 2019-02-23 at 11 42 43 am" src="https://user-images.githubusercontent.com/16291501/53289167-876d8300-3760-11e9-82fc-22afd499345c.png">

**Comment by atfelix** [comment] 2019-02-23 16:55
In Step 4, if the hover over reveals `https://exercism.io/my/solutions/<hash_value>`, then the new tab or window open as expected.

**Comment by chrisbro** [comment] 2019-08-04 13:20
Reproducible in Chrome as well (macOS Mojave 10.14, Chrome 75.0.3770.142).

**Comment by iHiD** [comment] 2019-08-04 14:37
For anyone else finding this, it's a duplicate of [this](https://github.com/exercism/exercism/issues/4949#issuecomment-515432681), which I replied to.

**Comment by IndelicateArgot** [comment] 2019-08-08 23:37
Reproducible also in Firefox (68.0.1) on Linux (Ubuntu: 4.15.0-55-generic #60~16.04.2-Ubuntu x86_64).

**Comment by iHiD** [comment] 2019-08-09 00:06
For clarity, it's going to be reproducable in every browser, as if you open it in a new tab, you're just opening a link to a page that doesn't exist :)

**Comment by sshine** [comment] 2019-10-02 12:01
Related to #4724.

**Comment by ErikSchierboom** [comment] 2021-08-31 06:01
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 06:01 UTC
