### ISSUE TITLE
Clicking "mentor" does nothing obvious and refreshing breaks page

### ISSUE THREAD

**Issue by joshgoebel** [exercism/exercism#5882] opened 2021-09-13 10:44 UTC
Clicking "Mentor" just makes the button pop up and down with no obvious effect.  Hitting refresh results in a broken page:

<img width="879" alt="Screen Shot 2021-09-13 at 6 42 47 AM" src="https://user-images.githubusercontent.com/6473/133070265-da58823b-2f1c-4b0e-bb18-a176dd06950c.png">

Yes I probably had left the page open and come back to it later...  so I'm assuming that someone else grabbed the slot - and this is an edge case - but we should probably handle it better.

**Comment by iHiD** [comment] 2021-09-13 20:19
Duplicate of https://github.com/exercism/exercism/issues/5755

**Closed by iHiD** 2021-09-13 20:19 UTC
