### ISSUE TITLE
Palindrome Products test suites are confusing

### ISSUE THREAD

**Issue by aprilmintacpineda** [exercism/exercism#4749] opened 2019-03-11 03:28 UTC
Note:

I have seen https://github.com/exercism/exercism/issues/1979 which I think is not related to this. Therefore, opening new issue.

On the *Palindrome Products*, I don't get what output is expected for the factors.

Is it suppose to be, `[1, 3, 9]` or `[[3, 3], [1, 9]]`?

I'm confused with what this test is doing:

```
test('largest palindrome from single digit factors', () => {
  const palindromes = generatePalindrome({ maxFactor: 9 });
  const { largest } = palindromes;

  expect(largest.value).toEqual(9);
  const containsMatch = [[3, 3], [1, 9]].filter(el => numericalArraysMatch(el, largest.factors)).length > 0;
  expect(containsMatch).toBe(true);
});
```

Because it's passing in the `largest.factors` to `numericalArraysMatch` and then the `numericalArraysMatch` is expecting `a.length === b.length` but if you check, `a` is either `[3, 3]` or `[1, 9]`, that means I should only return either one, which I tried and it worked.

The problem with this is that it's not in synched with the instructions that says

_Your solution should return the largest and smallest palindromes, along with the factors of each within the range. If the largest or smallest palindrome has more than one pair of factors within the range, then *return all the pairs*._

The problem here is what output is expected for the factors? Are we suppose to return all set of factors or just one? If just one then how are we suppose to know which factor to return? Because the test suites indicate that we should only return one set of factors. however, the instruction says otherwise.

**Comment by G-Rath** [comment] 2019-03-11 09:45
A *pair* is two numbers - three numbers is a trio :wink: So, ya as it says: every pair, which is `[3, 3]` & `[1, 9]`.

For the answer to be `[1, 3, 9]`, the wording would be something like

> If the largest or smallest palindrome has more than one pair of factors within the range, then *return all the factors that can be used to form a pair*.

I think the readme is just fine as it is, but open to suggestions on what'll make it clearer if you have any 😄

**Comment by aprilmintacpineda** [comment] 2019-03-11 10:16
Does it expect to receive ALL the pairs inside an array? I.e.,

```js
[
  [3, 3],
  [1, 9]
]
```

> If the largest or smallest palindrome has more than one pair of factors within the range, then return all the pairs.

would suggest **YES**, however, if you do so, `numericalArraysMatch(el, largest.factors)` would translate to:

```js
numericalArraysMatch([3, 3], [[3, 3], [9, 1]]);
```

The condition

```js
if (a.length !== b.length) {
  return false;
}
```

Would still be satisfied, however, the condition `one[index] === two[index]` would no longer be satisfied because:

given index is `0`:

```js
```

**Comment by G-Rath** [comment] 2019-03-11 18:56
Sorry, that's my bad.

So the problem is that the test is slightly wrong (IMO). It should be doing what the [typescript version](https://github.com/exercism/typescript/blob/master/exercises/palindrome-products/palindrome-products.test.ts#L10) does: testing that both pairs are returned.

Feel free to make a PR on the javascript track correcting this :)

**Comment by aprilmintacpineda** [comment] 2019-03-12 02:45
```js
test('largest palindrome from single digit factors', () => {
  const palindromes = Palindromes.generate({ maxFactor: 9, minFactor: 1 });
  const { largest } = palindromes;
  const expected = { value: 9, factors: [[1, 9], [3, 3]] };

  expect(largest.value).toEqual(expected.value);
  expect(sortFactors(largest.factors)).toEqual(expected.factors);
});

test('smallest palindrome from double digit factors', () => {
  const palindromes = Palindromes.generate({ maxFactor: 99, minFactor: 10 });
  const { smallest } = palindromes;
  const expected = { value: 121, factors: [[11, 11]] };

  expect(smallest.value).toEqual(expected.value);
  expect(sortFactors(smallest.factors)).toEqual(expected.factors);
});
```

Notice that on the first test, it expected `[1, 9]` which is `1 * 9`, but on the second test it did not expect `[1, 121]` which is `1 * 121`.

Also

```js
test('largest palindrome from double digit factors', () => {
  const palindromes = Palindromes.generate({ maxFactor: 99, minFactor: 10 });
  const { largest } = palindromes;
  const expected = { value: 9009, factors: [[91, 99]] };

  expect(largest.value).toEqual(expected.value);
  expect(sortFactors(largest.factors)).toEqual(expected.factors);
});
```

The expected factors are incomplete, it's only expecting one pair, `9009` has these factors:

```js
function getFactors(number) {
  const factors = [];

  for (let a = 1; a <= number; a += 1) {
    if (number % a === 0) {
      for (let b = 1; b <= a; b += 1) {
        if (a * b === number) {
          factors.push([a, b]);
        }
      }
    }
  }

  return factors;
}

function areFactorsCorrect(factorPairs, product) {
  for (let a = 0, max = factorPairs.length; a < max; a++) {
    if (factorPairs[a][0] * factorPairs[a][1] !== product) {
      return false;
    }
  }

  return true;
}

const targetProduct = 9009;
const factorPairs = getFactors(targetProduct); // [[1, 9009], [1001, 9], [11, 819], [117, 77], [1287, 7], [13, 693], [143, 63], [21, 429], [231, 39], [273, 33], [3, 3003], [91, 99]]
const checking = areFactorsCorrect(factorPairs, targetProduct); // true
```

Same goes for

```js
test('largest palindrome from triple digit factors', () => {
  const palindromes = Palindromes.generate({ maxFactor: 999, minFactor: 100 });
  const { largest } = palindromes;
  const expected = { value: 906609, factors: [[913, 993]] };

  expect(largest.value).toEqual(expected.value);
  expect(sortFactors(largest.factors)).toEqual(expected.factors);
});
```

Also with this,

```js
test('error for smallest if min is more than max', () => {
  expect(() => {
    const palindromes = Palindromes.generate({ maxFactor: 1, minFactor: 10000 });
    palindromes.smallest;
  }).toThrow(new Error('min must be <= max'));
});

test('error for largest if min is more than max', () => {
  expect(() => {
    const palindromes = Palindromes.generate({ maxFactor: 1, minFactor: 2 });
    palindromes.largest;
  }).toThrow(new Error('min must be <= max'));
});
```

I think the `palindromes.largest` and `palindromes.smallest` are quite unnecessary, the checking of factors SHOULD happen right inside `generate` method, right?

**Comment by aprilmintacpineda** [comment] 2019-03-12 02:55
> I think the palindromes.largest and palindromes.smallest are quite unnecessary, the checking of factors SHOULD happen right inside generate method, right?

actually, based on the [example](https://github.com/exercism/javascript/blob/065a4b287580978e2cbca6fd0db5df50e9898905/exercises/palindrome-products/example.js#L66), it's already being done on the `generate` method.

While the example works, it's [implementation for the factor pairs](https://github.com/exercism/javascript/blob/065a4b287580978e2cbca6fd0db5df50e9898905/exercises/palindrome-products/example.js#L6) is incorrect. It's always only remembering the first pair. This does not conform to the spec that says

> If the largest or smallest palindrome has more than one pair of factors within the range, then return all the pairs.

**Comment by SleeplessByte** [comment] 2019-03-12 14:13
I think this should be in the https://github.com/exercism/javascript repo.

**Comment by sshine** [comment] 2019-10-01 05:58
I'm closing this issue, as it appears to have been resolved.

If this is not the case, feel free to reopen and/or continue discussion.

**Closed by sshine** 2019-10-01 05:58 UTC
