### ISSUE TITLE
Limit mentor dashboard "Next solutions to mentor" by difficulty

### ISSUE THREAD

**Issue by lathspell** [exercism/exercism#4239] opened 2018-08-15 19:27 UTC
Would be nice if the "Next solutions to mentor" list could be limited by difficulty. When I'm tired I'd rather like to review 10 "easy" solutions than one "medium" :-)
At least write it in tiny font in the line under the title like "Kotlin | easy | Iteration 1 | $date" line.

**Comment by Cohen-Carlisle** [comment] 2018-08-21 03:41
This looks like a duplicate of https://github.com/exercism/exercism/issues/4105

**Comment by ErikSchierboom** [comment] 2021-08-31 05:56
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 05:56 UTC
