### ISSUE TITLE
Analytics Suggestion: Student drop-off ratio

### ISSUE THREAD

**Issue by lbsa71** [exercism/exercism#4646] opened 2019-01-29 12:17 UTC
As a mentor, I would like to understand how the drop-off looks for my mentored tracks, so I can understand where I should concentrate my efforts.

Discussion:
If would be instructive to get a listing, for each track, of what the 'exit' percentages are per exercise; i.e.

For the JavaScript track (before or after the latest track restructuring)
"Of the students that submitted a solution for exercise 1 (Hello World), how many of them did submit a solution for exercise 2 (Leap)"?
"Of the students that submitted a solution for exercise 2 (Leap), how many of them did submit a solution for exercise 3 (RNA)"?

et c.

This would help give us an idea of how much time and effort we should put into giving concise responses to each exercise, given the probability that the student will simply drop off.

**Comment by lbsa71** [comment] 2019-01-29 12:21
If the drop-off is significant, which would mean that it would make sense to start the first exercise(s) with simpler responses to screen drop-offs, then build up investment of efforts as the students progress. The intuition is that the exit percentage should be lower the further you go along, but this intuition might be wrong.

**Comment by sshine** [comment] 2019-10-03 22:44
#4714 appears to be a duplicate of this issue. Perhaps we should, however, close this issue as #4714 includes code that generates some of these statistics?

**Comment by lbsa71** [comment] 2019-10-07 06:40
While #4714 is corollary to this, that one concerns itself with queue length; this one concerns itself with student drop-off. This issue would be input to determinining the 'ideal' curve of #4714

**Comment by ErikSchierboom** [comment] 2021-08-31 06:00
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 06:00 UTC
