### ISSUE TITLE
Tabs in Online Editor

### ISSUE THREAD

**Issue by schackbrian2012** [exercism/exercism#6400] opened 2022-06-08 14:03 UTC
Dear Exercism,

I am doing the "Remote Control Competition" exercise [0] in the Java track. This issue could apply to other tracks with solutions that consist of multiple files. In the online editor, I see three tabs: ExperimentalRemoteControlCar.java, ProductionRemoteControlCar.java, and RemoteControlCar.java. The instructions for the exercise refer to a TestTrack class. I assume that the solution also contains a TestTrack.java document. I do not see this document in the tab bar. I cannot scroll the tab bar to show additional tabs. How do I edit the TestTrack class? I read "Using the online editor" [1] in the documentation, but it didn't say.

[0] https://exercism.org/tracks/java/exercises/remote-control-competition
[1] https://exercism.org/docs/using/solving-exercises/using-the-online-editor

Regards,
Brian Schack

**Comment by angelikatyborska** [comment] 2022-06-08 16:29
This might be a duplicate of: https://github.com/exercism/exercism/issues/5870

The other issue is from a mentor's perspective, but about the same Java exercise.

**Comment by schackbrian2012** [comment] 2022-06-09 13:49
@angelikatyborska Yes, that is the same issue from the perspective of the mentor.

**Closed** 2022-06-10 06:08 UTC

**Comment by ErikSchierboom** [comment] 2022-06-10 06:27
Should be fixed now. We'll do a proper fix sometime in the future.
