### ISSUE TITLE
matching-brackets: issues after renaming from bracket-push

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#4815] opened 2019-04-15 23:24 UTC
I have renamed `bracket-push` to `matching-brackets` for the Delphi track per exercism/problem-specifications#1501.  The rename appears to have gone OK except that when I view the exercise on the site the Test Suite and Instructions tabs are empty.  The site indicated that the exercise has been updated so I `updated`.  Trying to download via the CLI errors.  A `--verbose` look at the output reveals the CLI is receiving a 404 response.  Does @ihid need to run `the script`?

Verbose output from CLI:
```

========================= BEGIN DumpRequest =========================
GET /v1/solutions/latest?exercise_id=matching-brackets&track_id=delphi HTTP/1.1
Host: api.exercism.io
Authorization: Bearer b228*****************************5bc
Content-Type: application/json
User-Agent: github.com/exercism/cli v3.0.11 (windows/amd64)


========================= END DumpRequest =========================


========================= BEGIN DumpResponse =========================
HTTP/1.1 500 Internal Server Error
Content-Length: 1443
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Mon, 15 Apr 2019 23:07:18 GMT
Server: nginx/1.10.3 (Ubuntu)
X-Request-Id: 5db77c43-8071-4bef-ab70-a0595a578e9a
X-Runtime: 0.131484

<!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <link rel="//fonts.googleapis.com/css?family=Lato:100,300,400,700,900|Montserrat+Alternates:400,700|Dosis:800"/>
  <style>
    * { box-sizing: border-box }

    html {
        @include normal-font;
        font-size: 62.5%;
        letter-spacing: 0;
    }

    body {
        z-index:0;
        margin: 0;
        @include normal-font;
        @include font-size(14);
        color:#333;
        padding: 0 0 env(safe-area-inset-bottom) 0;
    }
    .heading-bar {
      background:#22333b;
      height:40px;
      margin-bottom:150px;
      padding: env(safe-area-inset-top) 0 0 0;
    }
    img {
      display:block;
      margin: 0 auto 50px auto;
      width: 120px;
      height: 92px;
    }
    p {
      font-family: "Lato", 'Helvetica Neue', Helvetica, Arial, sans-serif;
      font-size:18px;
      line-height:18px;
      font-weight:300;
      color:#333;
      margin:0 0 6px 0;
      text-align:center;
    }
    a {
      color:#333;
      text-decoration:underline;
    }
  </style>
</head>

<body>
  <div class="heading-bar"></div>
  <img src="https://assets.exercism.io/sad-icon.png"/>
  <p>Oh dear, something's not working here. Sorry about that.</p>
  <p>Continue by heading back to <a href="/">the homepage</a>.</p>
</body>
</html>

========================= END DumpResponse =========================

Error: unable to parse API response - EOF
```

**Comment by SleeplessByte** [comment] 2019-04-16 09:29
This seems similar to https://github.com/exercism/javascript/issues/664#issuecomment-483137466. This student gets an empty response when downloading the file.

@iHiD

**Comment by tejasbubane** [comment] 2019-04-16 11:04
I can reproduce same error on JS track with pretty similar debug output:

<details>

```
➜ ~ exercism download --verbose --exercise=matching-brackets --track=javascript

========================= BEGIN DumpRequest =========================
GET /v1/solutions/latest?exercise_id=matching-brackets&track_id=javascript HTTP/1.1
Host: api.exercism.io
Authorization: Bearer token
Content-Type: application/json
User-Agent: github.com/exercism/cli v3.0.11 (darwin/amd64)


========================= END DumpRequest =========================


========================= BEGIN DumpResponse =========================
HTTP/1.1 500 Internal Server Error
Content-Length: 1443
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Tue, 16 Apr 2019 11:01:10 GMT
Server: nginx/1.10.3 (Ubuntu)
X-Request-Id: 3145fb1c-de51-4b52-b286-a62e4cd269dd
X-Runtime: 0.110119

<!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <link rel="//fonts.googleapis.com/css?family=Lato:100,300,400,700,900|Montserrat+Alternates:400,700|Dosis:800"/>
  <style>
    * { box-sizing: border-box }

    html {
        @include normal-font;
        font-size: 62.5%;
        letter-spacing: 0;
    }

    body {
        z-index:0;
        margin: 0;
        @include normal-font;
        @include font-size(14);
        color:#333;
        padding: 0 0 env(safe-area-inset-bottom) 0;
    }
    .heading-bar {
      background:#22333b;
      height:40px;
      margin-bottom:150px;
      padding: env(safe-area-inset-top) 0 0 0;
    }
    img {
      display:block;
      margin: 0 auto 50px auto;
      width: 120px;
      height: 92px;
    }
    p {
      font-family: "Lato", 'Helvetica Neue', Helvetica, Arial, sans-serif;
      font-size:18px;
      line-height:18px;
      font-weight:300;
      color:#333;
      margin:0 0 6px 0;
      text-align:center;
    }
    a {
      color:#333;
      text-decoration:underline;
    }
  </style>
</head>

<body>
  <div class="heading-bar"></div>
  <img src="https://assets.exercism.io/sad-icon.png"/>
  <p>Oh dear, something's not working here. Sorry about that.</p>
  <p>Continue by heading back to <a href="/">the homepage</a>.</p>
</body>
</html>

========================= END DumpResponse =========================

Error: unable to parse API response - EOF
```

</details>

**Comment by iHiD** [comment] 2019-04-16 11:09
Looking.

**Comment by iHiD** [comment] 2019-04-16 11:21
Fixed by https://github.com/exercism/website/pull/627

I need to work out a script to fix existing people's code.

**Closed** 2019-04-16 11:37 UTC

**Comment by iHiD** [comment] 2019-04-16 11:47
Script is running now. This will fix for everyone who has downloaded since March 15th. If there was a rename before this, then please let me know the date and I'll play the script from earlier. I don't want to do it for everyone because it will put people's tests out of sync with their code if they solved it before the rename.
