### ISSUE TITLE
Line numbers are not aligned on Chrome

### ISSUE THREAD

**Issue by siebenschlaefer** [exercism/exercism#5443] opened 2020-04-07 02:07 UTC
On Chrome (80.0.3987.163, Linux and Windows) the line numbers are not aligned with the lines of the source code.

![Screenshot from 2020-04-07 03-57-30](https://user-images.githubusercontent.com/1228739/78621916-03069280-7884-11ea-9244-9035f1c21744.png)

On Firefox (74.0.1, Linux and Windows) everything is fine.

![Screenshot from 2020-04-07 04-02-58](https://user-images.githubusercontent.com/1228739/78622175-bd969500-7884-11ea-981c-9cfb9d72b50e.png)

Screenshots from https://exercism.io/mentor/solutions/b7456d081946490692f86997f887650f

**Comment by siebenschlaefer** [comment] 2020-12-14 13:11
@corneliusroemer I see. Thanks.

**Comment by martinfreedman** [comment] 2020-12-30 18:53
Can't see where this issue has been moved to. In the interim the same issues applies to Opera/GX LVL2 (core: 72.0.3815.459) running on the latest windows 10

**Comment by corneliusroemer** [comment] 2020-12-31 20:07
@martinfreedman What do you mean by you can't see where this issue has been moved to?

I can add an additional side-effect of this issue: the code box gets a scroll bar, because the view height is appropriate for the code yet the numbers overshoot. It's a bit annoying when trying to scroll the page because often the code just scrolls a tiny bit and the page moves not at all.

I had a look into tracking down the root cause of this and played around with css. But it's deeper, it's somewhere in the javascript. The way line numbers are added is very Javascripty and it's all about whether the rescaling is correct. In this case it's not, but I don't know why not.

Is it just dark mode or also light mode?

**Comment by iago-lito** [comment] 2021-01-04 12:46
> Is it just dark mode or also light mode?

@corneliusroemer Also light mode according to [this updated comment](https://github.com/exercism/exercism/issues/4350#issue-360549466).

**Comment by iHiD** [comment] 2021-01-04 13:51
This is all being entirely rewritten for v3, so I wouldn't invest more time into this for now. Thanks everyone though.

**Comment by ErikSchierboom** [comment] 2021-08-31 06:07
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 06:07 UTC
