### ISSUE TITLE
The code shown does not match the downloaded code

### ISSUE THREAD

**Issue by chriseyre2000** [exercism/exercism#5156] opened 2020-01-07 18:20 UTC
This is the problem exercise.

https://exercism.io/mentor/solutions/6358c67777f5414ab595deca3f3f2cfe

**Comment by iHiD** [comment] 2020-01-08 15:10
@chriseyre2000 What code do you get?

**Comment by chriseyre2000** [comment] 2020-01-08 17:13
The empty starting project

**Comment by chriseyre2000** [comment] 2020-01-08 17:14
When downloaded

**Comment by iHiD** [comment] 2020-01-08 21:21
The issue is that the student has uploaded the file with the full path to the file on their OS: ```/home/XXX/exercism/groovy/linked-list-2/src...```

Maybe they submitted it while at the root or something? Either way, because of this, we don't see a filename match, so it's not getting sent over the CLI.

**Comment by chriseyre2000** [comment] 2020-01-08 21:46
It's odd that the website can see the file.

**Comment by iHiD** [comment] 2020-01-08 21:47
Conceptually yes, but they're totally different codepaths, so less so in practice. 

I'm not sure how we should handle the issue generally. @kytrinyx might have some ideas but its such a rarity that I'm not it'll get prioritised for now.

**Comment by NobbZ** [comment] 2020-01-09 06:18
> `/home/XXX/exercism/groovy/linked-list-2/src...`

This looks like a path that is not considered valid anymore for recent CLI versions AFAIR.

Can you ask the student to check for their version (`exercism version`) and update if its less 3.0.10?

**Comment by chriseyre2000** [comment] 2020-01-10 19:16
They have now upgraded.

**Comment by iHiD** [comment] 2020-01-11 12:50
Thanks @chriseyre2000. Happy for this to be closed?

**Comment by chriseyre2000** [comment] 2020-01-11 13:22
Yes. A warning about out of date Elixir cli version would be useful.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jeremy Walker <notifications@github.com> Date: 11/01/2020  12:50  (GMT+00:00) To: exercism/exercism <exercism@noreply.github.com> Cc: Christopher Eyre <chriseyre2000@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [exercism/exercism] The code shown does not match the downloaded code (#5156) Thanks @chriseyre2000. Happy for this to be closed?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/exercism/exercism/issues/5156?email_source=notifications\u0026email_token=AAIMRX6Q4FG4EP7F2KQD64LQ5G6CNA5CNFSM4KD5FGD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIWBJAQ#issuecomment-573314178",
"url": "https://github.com/exercism/exercism/issues/5156?email_source=notifications\u0026email_token=AAIMRX6Q4FG4EP7F2KQD64LQ5G6CNA5CNFSM4KD5FGD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIWBJAQ#issuecomment-573314178",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sshine** [comment] 2020-02-01 11:33
I'm closing this because exercism/cli#913 was created.

**Closed by sshine** 2020-02-01 11:33 UTC
