### ISSUE TITLE
Sorting of community solutions could be improved

### ISSUE THREAD

**Issue by bobtfish** [exercism/exercism#5990] opened 2021-09-30 09:48 UTC
I'm not sure how community solutions get sorted currently, however my observation is that the first page almost universally contains solutions that are:

1) Several years old
2) Due to this, they're out of date with the current version of the exercise

<img width="1665" alt="Screenshot 2021-09-30 at 10 42 58" src="https://user-images.githubusercontent.com/42338/135428890-47cfb738-6c02-404a-a9fe-18e884a83524.png">

I think it would be good to expose some controls to affect the sorting of solutions so that you could toggle sorting:

1) Show only solutions for the current version of the exercise/show all
2) Show newest solutions first
OR
3) Show solutions with most stars/comments first

My inclination would be to default to showing the newest solutions which were for the current version of the exercise - this would also spread the love/comments around better as more eyes would get on newer solutions rather than older ones, but people would be easily able to toggle community 'favourite' solutions.

**Comment by angelikatyborska** [comment] 2021-09-30 09:58
They are currently sorted by most stars first, and then newest first if they have the same number of stars.

This is a duplicate of https://github.com/exercism/exercism/issues/5616. Please subscribe there to get updates on this solution and add any thoughts and suggestion you might have.

I'm closing this one to keep the issue list tidy 🧹

**Closed by angelikatyborska** 2021-09-30 09:58 UTC

**Comment by bobtfish** [comment] 2021-09-30 19:23
Thanks @angelikatyborska - I looked to see if it was already a reported issue, but didn't find #5616!
