### ISSUE TITLE
HTML anchors

### ISSUE THREAD

**Issue by mirkoperillo** [exercism/exercism#5268] opened 2020-04-27 05:14 UTC
Looking the Java installation page, I notice a wrong behavior of HTML anchors.

In the markdown version the anchors  exist and they work fine.
https://github.com/exercism/java/blob/master/docs/INSTALLATION.md

In the [HTML version](https://exercism.io/tracks/java/installation) of the same page anchors don't exist and if a click on a OS link browser open a new tab showing the beginning of the page.

**Comment by iHiD** [comment] 2020-04-27 10:12
Thanks for reporting.

Currently all links on those pages are set to open in new windows. I can change this but it's not something I'll have time to do before v3 launches.

**Comment by jmrunkle** [comment] 2020-04-27 14:20
@iHiD - I do not think the issue is opening the pages in new windows. Something is wrong with whatever converts the markdown to HTML. It opens the page in a new window with the expected anchor set, but the actual HTML content does not have the anchors that should be getting generated from the markdown.

For example, the Linux hyperlink takes you to https://exercism.io/tracks/java/installation#linux which should get you to the "linux" anchor generated by the markdown, but the HTML at that spot has no anchor:

```html
<h1>Linux</h1>
```

In contrast, here is what the markdown generates on GitHub:

```html
<li><a href="#linux">Linux</a></li>
```

Something in the way that the markdown is being converted into HTML pages is stripping (or failing to produce) those anchors.

**Comment by iHiD** [comment] 2020-04-27 14:40
Ah. I see. Thank you. I imagine that's a GH enhancement to markdown, but I will check when I have some time. It probably won't be for a little while but feel free to ping me in a week or two to see if I have a little more breathing space to take a look :)

**Comment by SleeplessByte** [comment] 2020-05-01 01:07
Yes, this is an "addon" and not standard in markdown, although expected by many.

**Comment by jmrunkle** [comment] 2020-05-01 01:41
> Yes, this is an "addon" and not standard in markdown, although expected by many.

Apparently it is so common that I have never encountered a markdown to HTML converter that did NOT do it. Probably should be standard...

**Comment by SleeplessByte** [comment] 2020-05-01 02:02
There are a lot of "hook and eyes" with automatically generating ids. A lot of platforms will actually not generate the value of the header, but apply some transformation (alsmost all), and sometimes add something to make it unique (medium).

[The official spec](https://daringfireball.net/projects/markdown/syntax) doesn't mention it at all.

https://talk.commonmark.org/t/anchors-in-markdown/247/17
https://commonmark.org/

**Comment by iHiD** [comment] 2020-05-04 23:08
Having read around I don't think it's actually part of any markdown processor. It's not part of GitHub Flavoured Markdown's spec for example. I think instead many website just insert anchors for any `h1/h2/h3` headings they find. We can totally do that, but I think we should separate this mentally from anything to do with markdown parsing.

**Comment by jmrunkle** [comment] 2020-05-05 00:47
Since this is currently broken for users, I will probably go ahead and submit a PR for the Java repo to manually add the anchors, but I figured we should think about just supporting the normal thing since we tend to review the generated content on GitHub when reviewing pull requests so it is difficult to tell that it does not work on the main website if we do not have some way to check for this.

**Comment by SleeplessByte** [comment] 2020-05-05 11:17
> Having read around I don't think it's actually part of any markdown processor. It's not part of GitHub Flavoured Markdown's spec for example. I think instead many website just insert anchors for any `h1/h2/h3` headings they find. We can totally do that, but I think we should separate this mentally from anything to do with markdown parsing.

In Gatsby and CommonMark they're a plugin, and a setting respectively. It only applies it to the parsed mark down tho.

**Comment by iHiD** [comment] 2020-05-05 11:51
> ...review the generated content on GitHub when reviewing pull requests so it is difficult to tell that it does not work on the main website if we do not have some way to check for this.

Yeah - this is tricky in general, because GH could do lots of things that are GH specific. I'm not sure how we fix it in general. 

Totally agree it would be nice to have.

@SleeplessByte we use `commonmarker` gem for Exercism currently. If there's some extension for that, I'd happily use it.

**Comment by SleeplessByte** [comment] 2020-05-05 12:56
GitHub seems to use this: https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb

Pass it through that after generating the HTML.

**Comment by ErikSchierboom** [comment] 2021-08-31 06:05
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 06:05 UTC
