### ISSUE TITLE
Cli authentication token management

### ISSUE THREAD

**Issue by swalladge** [exercism/exercism#4452] opened 2018-11-02 23:46 UTC
There should be a function to re-generate the cli authentication token for the case where a token is compromised.

**Comment by iHiD** [comment] 2018-11-03 16:00
Thanks for the issue. I'm closing this as its a duplicate of #4150 and it's also fixed by https://github.com/exercism/website/pull/446 which will get merged/deployed in the next 24hrs.

**Closed by iHiD** 2018-11-03 16:00 UTC
