### ISSUE TITLE
Issue with one of the Rust tests in the two_bucket exercise

### ISSUE THREAD

**Issue by rhorrace** [exercism/exercism#5205] opened 2020-02-29 04:45 UTC
Specifically, I believe one tests to be wrong in the two_bucket Rust exercise. Specifically:
fn goal_equal_to_other_bucket()
With the start bucket being 2, the other bucket being 3, and the goal being 3, there is a total of 4 moves:
1. fill up the 2 bucket
2. transfer 2 bucket to 3 bucket
3. fill up the 2 bucket
4. transfer 2bucket to 3 bucket

This will leave you with the resulting total of moves of 4, Bucket::two (correct), and a leftover of 1 in the other bucket

**Comment by iHiD** [comment] 2020-03-02 23:36
(cc @exercism/rust)

**Comment by coriolinus** [comment] 2020-03-02 23:45
The actual solution, as expected by the test:

1. Fill the 2 bucket (required)
1. Fill the 3 bucket

From the README:

> the only valid moves are:
>
> - pouring from one bucket to another
> - emptying one bucket and doing nothing to the other
> - filling one bucket and doing nothing to the other

The wording of the third valid move is critical, here: it does not mean that you can only fill `Bucket::One` and do nothing to `Bucket::Two`; it means that you can fill _either_ of the buckets while doing nothing to the other one. 

Recommend closing as not a bug.

**Comment by rhorrace** [comment] 2020-03-02 23:49
oh i see. sorry. i didnt consider that option. thank you

**Closed** 2020-03-03 00:36 UTC

**Comment by iHiD** [comment] 2020-03-03 00:40
@rhorrace I've added a change to make it clearer so it doesn't catch future people out.

**Comment by iHiD** [comment] 2020-03-03 00:40
And @coriolinus: Thanks for explaining! :)
