### ISSUE TITLE
Auto-create a link when entering a link in a mentoring comment

### ISSUE THREAD

**Issue by uzilan** [exercism/exercism#4598] opened 2019-01-13 11:26 UTC
Currently, if a mentor wants to add a link in a comment they have to write markdown such as `[text](https://actual.link.to/something)`. It would be helpful though if once submitting a comment that contains a link, it could be detected automatically and the markdown needed to create the link would be added.

**Comment by NobbZ** [comment] 2019-01-13 11:33
Personally I do not like turning URLs into links automatically. All implementations I've seen so far either had false positives or false negatives, both annoying.

Therefore I prefer the explicit way of always using markdown to make a link a link.

**Comment by F3PiX** [comment] 2019-01-13 11:38
Actually, there is a button in the editor menu that let you enter the url without thinking about brackets. It looks like the perfect compromise for both preferences.

**Comment by uzilan** [comment] 2019-01-13 11:42
@NobbZ could you please give an example of either?

**Comment by NobbZ** [comment] 2019-01-15 09:58
Sometimes in a sentence like "this is an example.is this an example?", the missing space after the dot makes autolinkers recognize `example.is` as an URL and will link it without the user hab any intend. Pretty much the same happens with filenames. Even if you apply a domain filter, main.rs or lib.rs which are common in rust will become links.

On the other hand side, to restricitve TLD filters will stop you from linking to example.museum without adding extra markdown.

**Comment by NobbZ** [comment] 2019-01-16 09:50
Which is often considered as annoying as writing out the markdown by those people that want to have the auto-linking behaviour. At least by the people I have talked to about this topic.

And to be honest, explicit schema does already work, for github at least, and as exercism is using GFM, it should work there as well.

**Comment by uzilan** [comment] 2019-01-16 11:02
Then I guess it's a bug!

**Comment by sshine** [comment] 2019-10-04 12:31
Duplicate of #4291. I've closed this one, as the context and arguments for and against seem apparent to those who have participated in both threads. By the effect of referring to this issue from here, both are now linked.

**Closed by sshine** 2019-10-04 12:31 UTC
Labels: area/website, type/feature-request
