### ISSUE TITLE
No way to navigate through iterations if there are too many of them

### ISSUE THREAD

**Issue by rcardenes** [exercism/exercism#5886] opened 2021-09-14 10:31 UTC
While I can imagine this is not an everyday issue, today I found a user that had iterated multiple times (21!, see attached image)

<img width="1199" alt="Screen Shot 2021-09-14 at 11 46 53 AM" src="https://user-images.githubusercontent.com/474868/133241844-11960dc0-30c2-410a-b01d-be9d4f967a2a.png">

What you see here is the product of narrowing the chat panel as much as possible, as there is no slider to let me scroll through the iterations. I can see how this could be a problem with not-so-wide screens, and make mentoring a bit more difficult.

**Comment by joshgoebel** [comment] 2021-09-14 10:34
Duplicate of #5768.

**Comment by rcardenes** [comment] 2021-09-14 10:47
Oh! Should I close it as duplicate?

**Comment by kytrinyx** [comment] 2022-03-04 22:08
I'll go ahead and close this as duplicate. Thanks for the report!

**Closed by kytrinyx** 2022-03-04 22:08 UTC
Labels: type/duplicate
