### ISSUE TITLE
Access solution/discussion from testimonial window

### ISSUE THREAD

**Issue by ynfle** [exercism/exercism#5972] opened 2021-09-26 12:41 UTC
If I recall correctly, in v2 we used to be able to access the solution/discussion from the testimonial. It would be great to be able to do that if the person accessing the page was the mentor for the corresponding discussion

**Comment by iHiD** [comment] 2021-09-26 19:16
I think this is a duplicate of https://github.com/exercism/exercism/issues/5864

**Closed by iHiD** 2021-09-26 19:16 UTC
