### ISSUE TITLE
Go hamming exercise queued for 10 days

### ISSUE THREAD

**Issue by saschamonteiro** [exercism/exercism#5414] opened 2020-11-11 21:31 UTC
it's been 10 days now since I submitted, and the queue ahead has not changed 
When I submitted the median waiting time was 2 days

If it really takes this long between every exercise I loose the flow and need to find something else

**Comment by saschamonteiro** [comment] 2020-12-04 03:28
so it took about 1 month for the exercise to get reviewed, and the avg time is now 1 month, so it will take 1.5 year to get through the 18 exercises!!
That is a shame, we can't progress properly 👎

**Comment by iHiD** [comment] 2020-12-04 11:47
@saschamonteiro Yes. The problem is well known. Which tracks are you mentoring on?

**Comment by saschamonteiro** [comment] 2020-12-04 18:45
I am not mentoring, but doing exercises being mentored.. It's on the Go track

**Comment by iHiD** [comment] 2020-12-04 19:15
Ah. Yeah, the problem is that we have tens of thousands of people using the site to learn, but then not contributing back by mentoring, so things are slow. If you helped clear some of the JS queue, I'm sure some of the Go mentors would be happy to bump you up their queue 🙂

**Comment by ErikSchierboom** [comment] 2021-08-31 06:07
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 06:07 UTC
