### ISSUE TITLE
Exercism CLI permission error

### ISSUE THREAD

**Issue by benni347** [exercism/exercism#6588] opened 2022-10-18 14:07 UTC
Hello,
When I run the command to configure exercism like the following way: `exercism configure --token={token}`, I get an error for `Error: open /home/cdrc/.config/exercism/user.json: permission denied
`. My last commit was 9 days ago then it woked. 
env
```
PWD=/home/cdrc/Git/mine/exercism/go/need-for-speed
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
LC_MEASUREMENT=de_CH.UTF-8
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
GDMSESSION=ubuntu
__INTELLIJ_COMMAND_HISTFILE__=/home/cdrc/.cache/JetBrains/GoLand2022.2/terminal/history/exercism-history
GNOME_SHELL_SESSION_MODE=ubuntu
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
_INTELLIJ_FORCE_SET_GOROOT=/usr/lib/go-1.18
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/
XDG_RUNTIME_DIR=/run/user/1000
LC_NUMERIC=de_CH.UTF-8
LC_NAME=de_CH.UTF-8
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
SSH_AGENT_LAUNCHER=gnome-keyring
XDG_SESSION_TYPE=x11
OLD_XDG_CONFIG_HOME=/home/cdrc/.config
_INTELLIJ_FORCE_PREPEND_PATH=/usr/lib/go-1.18/bin:
XDG_CONFIG_HOME=/home/cdrc/.config
HOME=/home/cdrc
TERM=xterm-256color
DESKTOP_SESSION=ubuntu
STARSHIP_SESSION_KEY=2484244711068078
GO111MODULE=on
LC_TIME=de_CH.UTF-8
DISPLAY=:1
SHLVL=1
WINDOWPATH=2
LANG=en_US.UTF-8
TERMINAL_EMULATOR=JetBrains-JediTerm
USER=cdrc
PATH=/usr/lib/go-1.18/bin:/home/cdrc/.local/bin:/home/cdrc/Applications:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/cdrc/.local/share/JetBrains/Toolbox/scripts
GIO_LAUNCHED_DESKTOP_FILE=/home/cdrc/.local/share/applications/jetbrains-goland.desktop
XAUTHORITY=/run/user/1000/gdm/Xauthority
STARSHIP_SHELL=fish
INVOCATION_ID=70d3d6a629e74ccc8a7e68539c84e9db
LC_MONETARY=de_CH.UTF-8
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
XDG_SESSION_CLASS=user
GJS_DEBUG_OUTPUT=stderr
DESKTOP_STARTUP_ID=gnome-shell/GoLand 2022.2.3/5250-14-cdrc-ubuntu_TIME10171962
QT_ACCESSIBILITY=1
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
_INTELLIJ_FORCE_SET_GO111MODULE=on
SHELL=/usr/bin/fish
QT_IM_MODULE=ibus
GOROOT=/usr/lib/go-1.18
LC_IDENTIFICATION=de_CH.UTF-8
XDG_SESSION_DESKTOP=ubuntu
SYSTEMD_EXEC_PID=5250
TERM_SESSION_ID=0a7cd6d3-f1b8-4a31-a6cf-f182cc71ce7a
GTK_MODULES=gail:atk-bridge
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
LC_ADDRESS=de_CH.UTF-8
LC_TELEPHONE=de_CH.UTF-8
XMODIFIERS=@im=ibus
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
LOGNAME=cdrc
GIO_LAUNCHED_DESKTOP_FILE_PID=75838
MANAGERPID=4800
SESSION_MANAGER=local/cdrc-ubuntu:@/tmp/.ICE-unix/5181,unix/cdrc-ubuntu:/tmp/.ICE-unix/5181
XDG_MENU_PREFIX=gnome-
LC_PAPER=de_CH.UTF-8
JOURNAL_STREAM=8:56727
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/home/cdrc/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
XDG_CURRENT_DESKTOP=ubuntu:GNOME
USERNAME=cdrc
```

**Comment by benni347** [comment] 2022-10-18 14:09
I installed it via snap. The version of exercism is: `exercism version 3.0.13`.

**Comment by kytrinyx** [comment] 2022-10-18 15:04
It looks like the CLI is complaining that it's not able to access the file that it needs to read, located at `/home/cdrc/.config/exercism/user.json` 

If you say `ls -la /home/cdrc/.config/exercism/user.json` what is returned?


(You should also be able to say `exercism upgrade` to get the latest version of the CLI, which will allow you to submit by saying `exercism submit` without specifying which files should be submitted. Worth doing, but totally irrelevant to the problem you're experiencing here!)

**Comment by glennj** [comment] 2022-10-18 15:13
`exercism troubleshoot` output would be useful

**Comment by benni347** [comment] 2022-10-18 18:53
> It looks like the CLI is complaining that it's not able to access the file that it needs to read, located at `/home/cdrc/.config/exercism/user.json`
> 
> If you say `ls -la /home/cdrc/.config/exercism/user.json` what is returned?
> 
> (You should also be able to say `exercism upgrade` to get the latest version of the CLI, which will allow you to submit by saying `exercism submit` without specifying which files should be submitted. Worth doing, but totally irrelevant to the problem you're experiencing here!)
ls -la returns :
```
ls -la ~/.config/exercism/
total 8
drwxrwxrwx  2 cdrc cdrc 4096 Okt 18 16:01 .
drwx------ 89 cdrc cdrc 4096 Okt 18 16:00 ..
-rwxrwxrwx  1 cdrc cdrc    0 Okt 18 16:01 user.json
```





> `exercism troubleshoot` output would be useful
exercism trubleshoot returns :
```
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.1.0

Call 'exercism upgrade' to get the latest version.
See the release notes at https://github.com/exercism/cli/releases/tag/3.1.0 for details.


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/cdrc/snap/exercism/5
Workspace: /home/cdrc/snap/exercism/5/exercism (default)
Config:    /home/cdrc/.config/exercism
API key:   <not configured>
Find your API key at https://exercism.io/my/settings

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 10.503518ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 132.15046ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
```

**Comment by glennj** [comment] 2022-10-18 23:04
This bit looks odd:
```
Configuration
----------------
Home:      /home/cdrc/snap/exercism/5
Workspace: /home/cdrc/snap/exercism/5/exercism (default)
Config:    /home/cdrc/.config/exercism
```
Your $HOME is not the parent directory of .config. Have you set `HOME=...` somewhere?

**Comment by benni347** [comment] 2022-10-19 05:24
> This bit looks odd:
> 
> ```
> Configuration
> ----------------
> Home:      /home/cdrc/snap/exercism/5
> Workspace: /home/cdrc/snap/exercism/5/exercism (default)
> Config:    /home/cdrc/.config/exercism
> ```
> 
> The "Home" reported there is not the same as HOME shown in your env output.
> 
> @kytrinyx do you know if this is how a snap-installed exercism behaves? I typically install exercism with homebrew.

My $HOME is set to /home/cdrc.
```
echo $HOME
/home/cdrc
```

**Comment by kytrinyx** [comment] 2022-10-19 06:18
I don't know, @glennj, I've not tried installing via Snap either. @ekingery might know, but we will have to ping him on slack as this repo doesn't seem to want to allow us to at-mention him.

**Comment by NobbZ** [comment] 2022-10-19 12:14
This is one of the know and not reproducible problems with the snap, hence exercism/cli#973 exists.

As a sidenote: It seems as if 3.1.0 hasn't made it to snapcraft yet.

**Comment by kytrinyx** [comment] 2022-10-19 12:25
> As a sidenote: It seems as if 3.1.0 hasn't made it to snapcraft yet.

Yes, I was unable to publish it to Snapcraft, as they've made changes to their platform since last time we published, and I haven't had time to debug it.

**Comment by glennj** [comment] 2022-10-19 15:24
@benni347 you might consider:
* uninstall the snap exercism
* install [Homebrew](https://brew.sh)
* then `brew install exercism`

**Comment by ekingery** [comment] 2022-10-19 16:01
By default, Snap requires that all files and any file access by a snap-installed binary happens [within the snap home / sandbox](https://snapcraft.io/docs/security-sandboxing). I assume snap increased the enforcement of this in a recent version. 

@benni347 if you do want to keep your config and/or workspace in your homedir and not the snap home, I like @glennj's suggestion. Before uninstalling the snap, I recommend submitting any active exercises and make a backup of your exercism workspace just in case.

**Comment by ekingery** [comment] 2022-10-19 16:40
@benni347, in theory you might be able to [install the snap in "dev mode"](https://askubuntu.com/questions/1227963/how-to-disable-snap-filesystem-sandboxing) as an alternative. YMMV.

**Comment by glennj** [comment] 2022-10-19 16:54
@ekingery the problem is the OP cannot submit: `exercism configure` fails

**Comment by kytrinyx** [comment] 2022-10-21 10:22
@benni347 have you found a solution?

If you're comfortable on the command-line, the easiest thing might actually be to download the latest release directly from GitHub:
https://github.com/exercism/cli/releases/tag/v3.1.0

You can check which architecture you have with `uname -m`, and ask us here if you're still stuck.

**Comment by kytrinyx** [comment] 2022-10-29 12:29
It's been a week since we've heard back from the original author, so I'm going to go ahead and close this issue.

@benni347 if you need further help, would you please post in the support channel of the Exercism community forum? https://forum.exercism.org/c/support/8

**Closed by kytrinyx** 2022-10-29 12:29 UTC
