### ISSUE TITLE
estimated time should be shown for review comment as well

### ISSUE THREAD

**Issue by vikramvi** [exercism/exercism#5548] opened 2021-06-03 05:53 UTC
- Currently estimated time is shown only for newly submitted solution

- Once I get review comment and resubmit changes or ask for clarification, there is no estimation is shown

- Please check screenshot, even after 24 hours I didn't hear back from mentor.
I'm not sure how much more I need to wait and this really break the momentum

**Comment by vikramvi** [comment] 2021-06-04 03:21
Even after 2 days of re-submitting solution I didn't hear back from mentor and I don't know how many more days I need to wait ?

I feel there is bug and mentor is not getting notifications ?

<img width="1440" alt="Screen Shot 2021-06-04 at 8 50 32 AM" src="https://user-images.githubusercontent.com/308490/120741108-122db280-c512-11eb-8fb9-3fbeb2b50a07.png">

**Comment by iHiD** [comment] 2021-06-04 10:18
@vikramvi You'll have to wait until the mentor gets back to you. There's not a bug - the mentor is a volunteer who mentors in their spare time. Some are very responsive, others are less responsive as they have busy jobs etc.

**Comment by vikramvi** [comment] 2021-06-04 16:05
> @vikramvi You'll have to wait until the mentor gets back to you. There's not a bug - the mentor is a volunteer who mentors in their spare time. Some are very responsive, others are less responsive as they have busy jobs etc.

oh ok, thanks for clarification,  doesn't a mentor who has free time jumps into another mentor's thread ? 

It'll be nice to have this kind of mechanism. Please let me know your thoughts on this

**Comment by vikramvi** [comment] 2021-06-06 16:38
@iHiD Even after 5 days I didn't back from this particular moderator ? 

Kindly assign to some other available moderator if s/he is willing to **help genuinely on time** 

These kind super slow moderator really discourage people to user your platform

**Comment by iHiD** [comment] 2021-06-06 21:21
The mentor will automatically time out after a 7 days if they don't answer. A lot of this will be fixed/changed in v3 - you might want to watch https://www.youtube.com/watch?v=5Cj1Dr9m3GM&ab_channel=Exercism to see what's changing :)

**Comment by vikramvi** [comment] 2021-06-07 05:31
Thanks for reviewing & commenting this sincere request

**Comment by vikramvi** [comment] 2021-06-07 05:35
I've sent few emails to hello@exercism.io, contribute@exercism.io but didn't hear back.

Kindly look into this problem as well ( LOL ).

God bless the team, you guys are rocking

**Comment by vikramvi** [comment] 2021-06-12 03:44
> I've sent few emails to [hello@exercism.io](mailto:hello@exercism.io), [contribute@exercism.io](mailto:contribute@exercism.io) but didn't hear back.
> 
> Kindly look into this problem as well ( LOL ).
> 
> God bless the team, you guys are rocking

@iHiD can you update on above ? Even after 1 week, there is no update on my status update from mentor. This way you're asking **NOT** to use your platform and look for better alternatives

**Comment by iHiD** [comment] 2021-06-13 21:26
@vikramvi What's the id of your solution (it'll be the UUID in the URL)?

**Comment by vikramvi** [comment] 2021-06-15 16:11
> @vikramvi What's the id of your solution (it'll be the UUID in the URL)?

https://exercism.io/my/solutions/fd5f0200a44c43748d58c6fdcb119d3a

**Comment by vikramvi** [comment] 2021-06-15 16:20
> I've sent few emails to [hello@exercism.io](mailto:hello@exercism.io), [contribute@exercism.io](mailto:contribute@exercism.io) but didn't hear back.
> 
> Kindly look into this problem as well ( LOL ).
> 
> God bless the team, you guys are rocking

Even people don't bother to reply back to emails even after 2 weeks, not sure what's the use of such platform where new comers are discouraged and forced to use something else

**Comment by iHiD** [comment] 2021-06-15 17:40
When you say "people" you mean me. I'm volunteer about 60hrs a week into Exercism - I don't get paid for it. Thousands of people use Exercism and are mentored each week. I get numerous emails from people wanting all sorts of stuff from me. If something isn't urgent it's unlikely that it's going to jump to the top of my list of things that need responding to, and I have a lot of things that are urgent that will end up coming before it.

**Comment by iHiD** [comment] 2021-06-15 17:44
So, having looked at your solution, the mentor was removed from the conversation when they timed out, and another mentor picked the solution up, and offered to mentor you, which is exactly as the system is designed to work. 

I understand you are frustrated with the wait, but I clearly communicated at the start of this thread that we are working on a new version that fixes the problems and linked you to the video. My responding individually to every person who's frustrated in the interim isn't going to get that version launched any faster.

**Comment by ErikSchierboom** [comment] 2021-08-31 06:08
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 06:08 UTC
