### ISSUE TITLE
UI/UX Responsive Layout Defects

### ISSUE THREAD

**Issue by Thoughtscript** [exercism/exercism#6581] opened 2022-10-13 20:20 UTC
Hi! First time poster here - let me just say thanks for the awesome website and community!

Second, wanted to point out the following:

1. On desktop, Brave/Chrome, Windows 11, web inspector:

![Screenshot 2022-10-13 151318](https://user-images.githubusercontent.com/10905039/195700256-e921c5ff-0b9b-42a0-a4ab-a870e7951c52.png)

2. On mobile, Safari, iPhone 11 Pro Max:

![IMG_5061](https://user-images.githubusercontent.com/10905039/195700261-2c0ea5f1-6242-49c9-b016-2d75fe6641d3.PNG)

![IMG_5060](https://user-images.githubusercontent.com/10905039/195700268-cef2550e-b9fe-4461-b700-3d7d2cdc464d.PNG)

![IMG_5059](https://user-images.githubusercontent.com/10905039/195700274-adae8bb7-495d-4c79-8e83-637b4432f9ea.PNG)

I did a quick search through and don't believe the issue's been raised. I also did not see a way to input the issue within the app proper (since it's UI/UX related).

I haven't looked too closely but I think you can fix it quite easily by removing `display: flex` possibly with a media-query (wrapping some overriding default attribute in there as appropriate):

![solution](https://user-images.githubusercontent.com/10905039/195701813-0ba00f6d-25b5-43eb-a38f-8983c20517c6.png)

If this a duplicate or if I've missed anything, my apologies!

Cheers!

**Comment by iHiD** [comment] 2022-10-13 21:52
@Thoughtscript Hi, thanks for the encouraging words and all the screenshots! The inside of the site isn't responsive yet (this is a known issue and a duplicate of https://github.com/exercism/exercism/issues/6036) but the external parts should be so need fixing, so I'll leave this open. Thank you :)

@dem4ron When you have a free hour, could you look at the issues on the logged out pages here, fix the easy ones and chat to me about the rest please.

**Comment by tarcisiooliveira** [comment] 2023-04-12 02:59
This issue could be closed?

**Closed** 2023-07-11 12:37 UTC
