### ISSUE TITLE
Problem running gradlew in kotlin's hamming 

### ISSUE THREAD

**Issue by axtens** [exercism/exercism#5341] opened 2020-07-22 09:08 UTC
More a heads-up than a breaking problem. Bottom line: `gradlew` doesn't work out of the box. Might have something to do with the Java version ( Java 14 installed, via `scoop install oraclejdk` ).

```
Exercism\kotlin\hamming>gradlew test

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 913ms
```

```
Exercism\kotlin\hamming>gradlew -version

------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------

Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          14.0.2 (Oracle Corporation 14.0.2+12-46)
OS:           Windows 10 10.0 amd64
```
I have gradle 6.5.1 installed (via Scoop) but that's not what's running above. 
```
Exercism\kotlin\hamming>gradle -version

------------------------------------------------------------
Gradle 6.5.1
------------------------------------------------------------

Build time:   2020-06-30 06:32:47 UTC
Revision:     66bc713f7169626a7f0134bf452abde51550ea0a

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          14.0.2 (Oracle Corporation 14.0.2+12-46)
OS:           Windows 10 10.0 amd64
```
If I try gradle test (without the `w`) I get 
```
Exercism\kotlin\hamming>gradle test

> Task :test

HammingTest > single letter identical strands SKIPPED

HammingTest > empty strands PASSED

HammingTest > long different strands SKIPPED

HammingTest > disallow first strand longer SKIPPED

HammingTest > long identical strands SKIPPED

HammingTest > disallow second strand longer SKIPPED

HammingTest > single letter different strands SKIPPED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 39s
3 actionable tasks: 3 executed
```
So it works, it's just confusing when the supplied tool fails to work as advertised.

**Comment by NobbZ** [comment] 2020-07-22 09:25
`gradle` in general is very sensitiv to the Java version used. And its error messages about beeing run with the wrong version of Java are really bad.

`gradlew` is a small program that will download a certain version of gradle and use it, whihc is meant to be used for the project. The main benefit of this is, that all members of the team are using the exact same version of `gradle` all the time. This makes results of `build` tasks more reproducible.

The major issue with that approach though is, that the `gradlew` needs to be updated for each new release of Java that is supported by the project in general, which also might require work to be done in the actual gradle scripts.

Due to this, the wrapper is only updated occasionally when someone of the @exercism/java team sees failing builds with newer Java versions.

I mentioned them in the last sentence to make them aware of the problem. Until the problem got fixed upstream, you can continue to use your system installed `gradle` binary. For the sake of `exercism` it will probably work, though for contributing to other projects you might want to look into environment managers which allow you to choose different versions of Java for different projects. As I do not do Java development on my own, I am not aware of any specialised tool, but I am pretty sure that [asdfv-vm][asdf] has some Java plugin.

[asdf]: https://asdf-vm.com/

**Comment by mirkoperillo** [comment] 2021-03-02 09:46
Just for information, we have just merged a PR in java track to move the wrapper to the last gradle version (6.8.3)
PR ref #1896

**Comment by ErikSchierboom** [comment] 2021-08-31 06:05
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 06:05 UTC
