### ISSUE TITLE
Emoji keyboard in mentor discussion

### ISSUE THREAD

**Issue by adambuckland** [exercism/exercism#4059] opened 2018-07-24 12:53 UTC
I'd totally like some kind of emoji dropdown in the mentor disscussion box, or the ability to do a `:wave:` sort of thing á la GitHub or Slack please.

I mean, I can't be the only millenial mentor! 😎

**Comment by iHiD** [comment] 2018-11-17 13:35
Totally agree. Closing as duplicate of https://github.com/exercism/exercism/issues/3902 :)

**Closed by iHiD** 2018-11-17 13:35 UTC
