### ISSUE TITLE
Command click on link in Safari doesn't open problem page in new tab

### ISSUE THREAD

**Issue by atfelix** [exercism/exercism#4724] opened 2019-02-23 16:53 UTC
System Info: 
- Browser:  Safari 12.0
- OS:  macOS Mojave 10.14
 
Steps to Reproduce:

1. Go to the Swift language track (https://exercism.io/my/tracks/swift)
2. Ensure that you have status bar enabled
3. Hover over an unsolved problem
4. If the status bar shows a link of the form `https://exercism.io/my/solutions?exercise_id=linked-list&track_id=swift`, then Command click on the problem

Expected Result:
The new tab opens the problem

Actual Result:
The problem page opens in the current tab

**Comment by atfelix** [comment] 2019-02-23 16:56
In Step 4, if the hover over reveals `https://exercism.io/my/solutions/<hash_value>`, then the new tab opens the page and leaves the current tab where it was.

**Comment by atfelix** [comment] 2019-02-23 16:57
This issue and #4723 are likely related

**Comment by sshine** [comment] 2019-10-02 11:58
@atfelix: Yes, the root cause is the same as in #4723, [this comment](https://github.com/exercism/exercism/issues/4949#issuecomment-515432681) in #4949, and #4471:

As @iHiD wrote:
> It's standard Rails code for POST links, but it does have that annoying side effect.
>
> I'm going to close this for now, as you've got a workaround, but I'll improve it some time in the future so opening things in new tabs works. It's not trivial though.

The code in question is:

```html
<a class="widget-side-exercise unlocked" rel="nofollow" data-method="post"
   href="/my/solutions?exercise_id=hello-world&amp;track_id=perl5">
```

I believe that Rails attempted to invent an alternative to form submit buttons shaped like links.

I also think this is a standards-incompliant practice.

**Comment by ErikSchierboom** [comment] 2021-08-31 06:01
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 06:01 UTC
