### ISSUE TITLE
Sort community solutions to an exercise

### ISSUE THREAD

**Issue by adrien1990** [exercism/exercism#6131] opened 2021-11-26 15:00 UTC
the community solutions to an exercise can not be sorted, although the attributes (stars, date, ...) are visible.
It was possible in version 2 and was very helpful, since it was possible to get other interesting solutions this way. Now they are lost between the thousands of other generic solutions. 
Please bring back this feature!

**Comment by angelikatyborska** [comment] 2021-11-26 17:38
Duplicate of https://github.com/exercism/exercism/issues/5616 - please subscribe to this issue to get updates on this topic.

**Closed by angelikatyborska** 2021-11-26 17:38 UTC
