### ISSUE TITLE
Homepage is horizontally scrollable

### ISSUE THREAD

**Issue by TimonVS** [exercism/exercism#6271] opened 2022-03-06 14:26 UTC
The homepage shows a horizontal scrollbar, because of an image.

The following suggestions will probably fix the issue:

- Change CSS of main graphic:

```css
#page-landing section.mentoring-section .main-graphic {
  margin-left: auto;
  margin-right: auto;
  width: 100%;
  max-width: 100%;
}
```
- Add `width` and `height` attributes to `img` element [to preserve aspect ratio and to prevent layout shift](https://developer.mozilla.org/en-US/docs/Web/Media/images/aspect_ratio_mapping).

## Screenshots

![CleanShot 2022-03-06 at 15 16 36@2x](https://user-images.githubusercontent.com/876666/156927109-ea645fae-4684-4471-9ecf-97ccb3af3d65.png)

![CleanShot 2022-03-06 at 15 16 31@2x](https://user-images.githubusercontent.com/876666/156927124-72198b57-4e6d-4009-90ad-04ab5fd277d8.png)

**Comment by SleeplessByte** [comment] 2022-03-07 11:12
Thanks @TimonVS! This is part of a larger ticket on our roadmap: responsiveness.

Duplicate of #6036  #6188  #6241  #6217 .

**Comment by iHiD** [comment] 2022-03-07 12:53
_(Thanks for triaging, DJ 💙  This is actually in scope because the external site should be responsive. So I've reopened.)_

We made changes to this last week to reduce flashes of CLS so it looks like I've made a mistake somewhere. Will fix this afternoon. @TimonVS Thanks for reporting.

**Comment by iHiD** [comment] 2022-03-07 14:17
@TimonVS What browser are you on? Could you check the CSS on the image please and let me know how your browser is interpreting it. The CSS for this image should have `width: 90vw` so it shouldn't need to have a `max-width: 100%` and I can't reproduce the issue locally. Thanks.

**Comment by SleeplessByte** [comment] 2022-03-07 15:23
@iHiD I'll make sure external site responsiveness issues reach you! 😄

**Comment by TimonVS** [comment] 2022-03-07 15:58
@iHiD I'm on Firefox, but the same happens in Chrome (both on latest versions). `width: 90vw` doesn't respect the container (=90% of viewport width),  `max-width: 100%` does (=100% of container width/1440px), unless you wanted the image to  break out of the container? :)

**Comment by SleeplessByte** [comment] 2022-03-07 16:20
I have the same issue as Timon, and you can see here why:

![image](https://user-images.githubusercontent.com/1964376/157074050-f58781f5-f8fb-4ad6-9641-02cdd6e0579c.png)

The left side is > 10vw. 

Personally I would solve this by stop overflow on its section/container:
![image](https://user-images.githubusercontent.com/1964376/157074238-2b58b822-0240-4754-913c-46f875f5ea25.png)

**Comment by iHiD** [comment] 2022-03-07 17:33
Ah - it's because you're on a bigger screen than me!

How do I set the image height doing it the way you suggest?

**Comment by TimonVS** [comment] 2022-03-07 18:11
If you set the image's `width` and `height` attributes on the `img` element to the original dimensions, the browser will retain the aspect ratio of the image, and prevent layout shift. So you don't need to set the height of the image in CSS :). You can read more about this here: https://developer.mozilla.org/en-US/docs/Web/Media/images/aspect_ratio_mapping#a_new_way_of_sizing_images_before_loading_completes.

**Comment by iHiD** [comment] 2022-03-07 20:07
@TimonVS TIL! Awesome, thanks.

**Closed** 2022-03-07 22:51 UTC
Labels: type/duplicate
