### ISSUE TITLE
Improve rust 'hello-world'

### ISSUE THREAD

**Issue by gongpengjun** [exercism/exercism#4969] opened 2019-08-07 02:53 UTC
The package `name` in Cargo.toml is `hello-world`, I try to `use hello-world;` in source file `test/hello-world.rs`, the rustc report error as followings:

```
error: expected one of `::`, `;`, or `as`, found `-`
 --> tests/hello-world.rs:1:10
  |
1 | use hello-world;
  |          ^ expected one of `::`, `;`, or `as` here
```

Since 'hello-world' is invalid, It is better modify the package `name` in Cargo.toml from `'hello-world'` to `'hello_world'`.

I did it in the solution:
https://exercism.io/tracks/rust/exercises/hello-world/solutions/3e6595d1fc444f0c9de044cda6962400

**Comment by PatrickMcSweeny** [comment] 2019-08-07 03:09
There should be no need for you to modify the test file in any of the exercises.

**Comment by tejasbubane** [comment] 2019-08-07 08:32
cc @exercism/rust

**Comment by coriolinus** [comment] 2019-08-07 09:43
The test file already has the correct import: https://github.com/exercism/rust/blob/master/exercises/hello-world/tests/hello-world.rs#L1

We have learned through prior experience that it is a bad idea to shift hyphens to underscores in exercise names; this confuses exercism.

I recommend this issue be closed as Not A Bug.

**Comment by sshine** [comment] 2019-09-19 16:12
@gongpengjun: Feel free to bring this or similar suggestions for improvements up in the [exercism/rust](https://github.com/exercism/rust) repo. I'm closing this issue by request, since no discussion has taken place for a while, but you're welcome to get back.

**Closed by sshine** 2019-09-19 16:12 UTC
