### ISSUE TITLE
Non-learnable concepts block progression 

### ISSUE THREAD

**Issue by junedev** [exercism/exercism#5770] opened 2021-09-04 17:21 UTC
Currently some tracks have concepts as prerequisites to exercises that are not taught by any concept exercise yet so they can't be unlocked.

This is the issue for this in the Go track https://github.com/exercism/go/issues/1495 but it is a general problem and I didn't see an issue in this repo. In Python they started hiding exercises because of this issue: 
https://github.com/exercism/python/pull/2547

Instead of every track working around this manually it would be great if it could be fixed in general. Only prerequisites that are taught by some non-wip/non-deprecated exercise should block the progression in the tree.

**Comment by junedev** [comment] 2021-09-04 17:29
(imo the prio on this should be rather high)

**Comment by iHiD** [comment] 2021-09-04 17:45
@junedev Agree that priority is high. `configlet` should be blocking this. The problem is that that didn't get merged pre-launched. I don't hugely want to write a load of code in the website for this only to delete it a week later when `configlet` gets fixed.

@ee7 @ErikSchierboom How close are we on this? If @ee7 is busy is this something @ErikSchierboom could spike a quick version of?

**Comment by junedev** [comment] 2021-09-04 18:00
I understand. So if I understand correctly, the fix on configlet side would at least allow track maintainers to identify (and fix) the issue before students need to report them, is that what you meant?

**Comment by BethanyG** [comment] 2021-09-04 18:03
For my part, I was overly ambitious in what I thought I'd get done concept-exercise wise.  I am in the middle of clearing out the prerequisites in Pythons `config.json` for any practice exercise or concept exercise that has dependancies that are not yet complete.  I saved my "ideal" off to the side.  A check going forward to stop me or someone else from adding prerequisites back in that are not yet complete would be _**excellent**_  😄

**Comment by iHiD** [comment] 2021-09-04 23:56
> So if I understand the solution correctly, the fix on configlet side would at least allow track maintainers to identify (and fix) the issue before students need to report them, is that what you meant?

Configlet would fail if there was not a valid path through the tree (and from next week configlet must be green to get deployable).

**Comment by iHiD** [comment] 2021-09-05 00:01
@ee7 has now done this here: https://github.com/exercism/configlet/pull/410 - Erik will review/merge first thing on Tuesday. Thank you @ee7!

**Comment by ee7** [comment] 2021-09-05 00:42
I've made a quick configlet release (`4.0.0-alpha.27`) so `configlet lint` in CI now checks these rules for a
track-level `config.json` file:
> - The `exercises.concept[].prerequisites` values must match any other concept exercise's `concepts` property values
> - The `exercises.concept[].prerequisites` values must not match any of the values in the exercise's `exercises.concept[].concepts` property

These rules currently apply to user-facing Concept Exercises only, which are those with `status` of `active` or `beta`.

More coming soon.

**Comment by iHiD** [comment] 2021-09-05 00:49
Thanks so much for the fast follow @ee7 :)

**Comment by ErikSchierboom** [comment] 2022-03-05 14:02
This has been fixed and can be closed.

**Closed by ErikSchierboom** 2022-03-05 14:02 UTC
