### ISSUE TITLE
Enable commenting on community solutions.

### ISSUE THREAD

**Issue by Ornataweaver** [exercism/exercism#4156] opened 2018-08-05 09:34 UTC
can't comment under my solution:
https://exercism.io/tracks/python/exercises/list-ops/solutions/70a00044df934e95b2b17e71d774eccd
can't comment under others' solutions:
https://exercism.io/tracks/python/exercises/list-ops/solutions/95a04d201d6c49f9902bc5f1ef3c722e
I can 'React to this solution' via a box under the solution. But there is no comment button there.
Whereas there is almost the same box, which counts reactions plus comments, in front of the name at the top.

I can comment under Mentor Discussion:
https://exercism.io/my/solutions/70a00044df934e95b2b17e71d774eccd

**Comment by iHiD** [comment] 2018-08-05 11:02
Thanks @Ornataweaver. This is coming soon.

**Comment by Ornataweaver** [comment] 2018-10-23 00:34
After changing to independent mode, can't comment under Mentor Discussion anymore:
https://exercism.io/my/solutions/70a00044df934e95b2b17e71d774eccd
However, I can edit or delete previous comments.

**Comment by iHiD** [comment] 2018-10-23 03:43
Could you open a new issue for that please?

**Comment by Ornataweaver** [comment] 2018-10-24 14:01
Done:
https://github.com/exercism/exercism/issues/4440

**Comment by cstegel** [comment] 2018-11-26 04:00
I also cannot comment on community solutions or my own solution. This is very confusing since other people have put comments on solutions such as here: https://exercism.io/tracks/rust/exercises/saddle-points/solutions/062e8486d1954e00a5af8475eef26950

Any estimate on when this will be tackled? I tried to look at the `website` repo to see if this was an easy fix but I'm not familiar at all with how the website operates. 

I would like to comment on other people's solutions to give them feedback and help them learn but this completely prevents that.

**Comment by glenegbert** [comment] 2018-12-12 15:49
I am having the same issue as cstegel

**Comment by TylerP33** [comment] 2019-01-16 03:33
Same problem here?

**Comment by iHiD** [comment] 2019-01-22 21:06
Closing as duplicate of https://github.com/exercism/exercism/issues/4400

**Closed by iHiD** 2019-01-22 21:06 UTC
Labels: status/on-roadmap
