### ISSUE TITLE
Can access "Community Solutions" tab even without permission

### ISSUE THREAD

**Issue by RuiL1904** [exercism/exercism#5867] opened 2021-09-10 17:33 UTC
Simple as adding "/solutions" after the exercise url will lead us to the "Community Solutions" tab even without permission.
Example: https://exercism.org/tracks/python/exercises/meltdown-mitigation/solutions

**Comment by FaisalAfroz** [comment] 2021-09-11 02:10
Yes I think a route guard could prevent that.

**Comment by ProProgrammer2504** [comment] 2021-09-11 02:34
Duplicate of #5850

**Comment by angelikatyborska** [comment] 2021-09-11 13:15
I'll close this one but feel free to continue the conversation in #5850

**Closed by angelikatyborska** 2021-09-11 13:15 UTC
