### ISSUE TITLE
Repeated timeout errors when downloading etc.

### ISSUE THREAD

**Issue by lmrqrdt** [exercism/exercism#5269] opened 2020-04-27 17:37 UTC
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13

Operating System
----------------
OS:           windows
Architecture: amd64

Configuration
----------------
Home:      C:\Users\larry
Workspace: C:\Users\larry\Exercism
Config:    C:\Users\larry\AppData\Roaming\exercism
API key:   18e3*****************************1fb

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 102.8126ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [Get https://api.exercism.io/v1/ping: dial tcp: i/o timeout]
    * 30.0000898s

**Comment by iHiD** [comment] 2020-04-28 15:09
Hi. Where are you geographically?

**Comment by lmrqrdt** [comment] 2020-04-28 16:20
Hi Jeremy,
I am in Pueblo, CO US
Thanks for responding.
Larry

**Comment by iHiD** [comment] 2020-04-28 20:42
Colorado is a place I want to visit :)

And are you still having the same issue? We seem to be having some weird connectivity issues sporadically coming from the US. If you have `mtr` could you run `mtr --report exercism.io` please? Do you get any loss? Based on research last week, I suspect the issue is somewhere in between you and Exercism's servers, rather than the servers itself.

**Comment by lmrqrdt** [comment] 2020-04-28 22:34
I don't have mtr. Is it an npm package?

**Comment by iHiD** [comment] 2020-04-29 11:53
It's probably apt or brew (depends on your package manager. I don't know for windows).

**Comment by SleeplessByte** [comment] 2020-05-01 01:06
For windows, you can use [WinMTR](https://sourceforge.net/projects/winmtr/), but you do NOT need it. Open `cmd.exe` and run `tracert api.exercism.io`. It's completely normal that some of the hops will be timeouts -- you might need to increase the max hops size to reach the `api.exercim.io` final ip.

**Comment by lmrqrdt** [comment] 2020-05-01 01:43
Interesting. I get this message when running tracert api.exercism.io -
Unable to resolve target system name api.exercism.io. You should know that
the timeouts occur intermittently and usually resolve with a reboot, which
of course is less than optimal.

**Comment by lmrqrdt** [comment] 2020-05-04 15:59
Derk-Jan,

I had success running tracert api.exercism.io

Here is the result:


C:\Users\larry\Exercism\javascript\matrix>tracert api.exercism.io

Tracing route to api.exercism.io [52.209.53.10]
over a maximum of 30 hops:

  1     3 ms     2 ms     2 ms  192.168.0.1
  2    14 ms    12 ms    13 ms  cm-1-acr02.pueblo.co.denver.comcast.net
[96.120.12.237]
  3    13 ms    14 ms    12 ms
ae-252-1209-rur01.pueblo.co.denver.comcast.net [96.110.195.129]
  4    14 ms    15 ms    14 ms  ae-35-ar01.denver.co.denver.comcast.net
[68.86.179.81]
  5    24 ms    15 ms    14 ms
be-33652-cr02.1601milehigh.co.ibone.comcast.net [68.86.92.121]
  6    15 ms    13 ms    13 ms
be-12176-pe02.910fifteenth.co.ibone.comcast.net [68.86.83.94]
  7    35 ms    35 ms    62 ms  173.167.57.142
  8    31 ms    41 ms    30 ms  kanc-b1-link.telia.net [62.115.120.67]
  9    39 ms    39 ms    36 ms  chi-b21-link.telia.net [213.155.130.176]
 10     *        *        *     Request timed out.
 11   131 ms     *      130 ms  ldn-bb3-link.telia.net [62.115.113.21]
 12   127 ms   126 ms   126 ms  ldn-b1-link.telia.net [62.115.114.235]
 13   127 ms   132 ms   126 ms  a100-ic-328647-ldn-b1.c.telia.net
[213.248.99.217]
 14     *        *        *     Request timed out.
 15     *        *        *     Request timed out.
 16     *        *        *     Request timed out.
 17     *        *        *     Request timed out.
 18     *        *        *     Request timed out.
 19     *        *        *     Request timed out.
 20     *        *        *     Request timed out.
 21     *        *        *     Request timed out.
 22     *        *        *     Request timed out.
 23     *        *        *     Request timed out.
 24     *        *        *     Request timed out.
 25     *        *        *     Request timed out.
 26     *        *        *     Request timed out.
 27     *        *        *     Request timed out.
 28     *        *        *     Request timed out.
 29     *        *        *     Request timed out.
 30     *        *        *     Request timed out.

Trace complete.

C:\Users\larry\Exercism\javascript\matrix>

I don't know how to set the maximum hops or what you reccomend

Thanks,
Larry

**Comment by SleeplessByte** [comment] 2020-05-05 11:22
Yeah, this definitely is a broken trace -- around 20 I would expect hops to resolve again. cc @iHiD anything we could do?

**Comment by iHiD** [comment] 2020-05-05 11:49
I have no idea what we could do. 

Out of interest, do you get the same if you tracert to `exercism.org`?

**Comment by ErikSchierboom** [comment] 2021-08-31 06:05
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 06:05 UTC
