### ISSUE TITLE
404 when joining a track

### ISSUE THREAD

**Issue by isomorphisms** [exercism/exercism#4471] opened 2018-11-15 02:11 UTC
https://exercism.io/my/user_tracks?track_id=haskell

[sad-icon]

Oh dear, we can't find that page. Sorry about that.

Continue by heading back to the homepage.

**Comment by rpottsoh** [comment] 2018-11-15 03:51
try https://exercism.io/my/tracks/haskell

**Comment by iHiD** [comment] 2018-11-15 11:29
Hi @isomorphisms. I presume this is referring to [this tweet](https://twitter.com/isomorphisms/status/1062890958390349825). You're going to have to give me a few more details about what doesn't work, please :)

It looks like you're accessing a page with a GET that's meant to my accessed via a POST. I would like to understand how that's happening so any information you can give would be appreciated. Thanks.

**Comment by teor2345** [comment] 2018-11-20 15:38
I see a 404 error when opening "Join a track" in a new tab on iOS Safari.
Tapping the button to open in the same tab works.

**Comment by F3PiX** [comment] 2018-11-20 20:17
To reproduce: 
On Language Tracks page, click a new language, on that page click-and-hold the purple "Join the * Track".  A pop up menu appears, with 'Open in new tab'. Click that, a new tab opens -> 404.
The link is formatted as in the OP's description: `https://exercism.io/my/user_tracks?track_id=haskell`

The 404 does not appear when clicking 'Open' form the pop up menu, and also not when just clicking the purple button.

**Comment by IlyaKryazhev** [comment] 2019-01-10 13:04
https://exercism.io/my/solutions/608cae7be7714c10be99dc45faaebb19
Please, help me, i do not understand how to fix this problem.
I submit solution and then this error turns out.

**Comment by iHiD** [comment] 2019-01-10 13:57
@IlyaKryazhev Please open a new issue for your problem and someone will help you :)

**Comment by sshine** [comment] 2019-10-01 06:48
Following @F3PiX's instructions, this occurs here, too.

The link looks like

```html
<a class="pure-button pure-x-hide pure-u-md-show" rel="nofollow" data-method="post" href="/my/user_tracks?track_id=bash">Join the Bash Track</a>
```

Possibly, `data-method="post"` is a Javascript thing, so the browser's Right-Click-Open-In-New-Tab doesn't trigger it. The point of making it a link rather than a form button is lost if it doesn't work like a link.

**Comment by ErikSchierboom** [comment] 2021-08-31 05:58
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 05:58 UTC
