### ISSUE TITLE
[Bug] Huge JPEG image embedded inside an SVG on the landing page

### ISSUE THREAD

**Issue by noocsharp** [exercism/exercism#6177] opened 2021-12-31 04:50 UTC
The exercism landing page weighs 7.7MB. The largest file served is [this](https://d24y9kuxp2d7l2.cloudfront.net/packs/media/images/graphics/landing-page-exercise-8a95dc9aabafebaccf79d2bbed0213c8.svg), which is 1.8MB.

This file is jpeg data embedded inside an svg as base64. I decoded it, and found that it is a 2.1MB 1871x4096 image. This indicates to me that this is a mistake, because only the top 1/3 of the image is actually displayed, and it can be much smaller given the way it is used on the page.

Fixing the size of this image would decrease the landing page size by around 20% (if shrunk to ~500kB like the other images on the page)

**Comment by kotp** [comment] 2021-12-31 05:33
I do not see that same image as linked on my page, nothing mentioning SleeplessByte, for example.  I am not sure that link links to the intended graphic.

**Comment by kotp** [comment] 2021-12-31 05:34
Oh, unless you mean the not-logged in landing page.

**Comment by noocsharp** [comment] 2021-12-31 05:43
Yes, the not-logged in landing page.

**Comment by kotp** [comment] 2021-12-31 06:20
@iHiD or @ErikSchierboom will likely move it to the correct place, reporting it here is correct.

**Comment by ErikSchierboom** [comment] 2022-01-04 09:44
I can confirm that the image displayed on the not-logged in landing page is very big (2.9MB according to Chrome DevTools on my machine). We'll take a look.

p.s. I think it's fine having this issue here (unless @iHiD disagrees)

**Comment by iHiD** [comment] 2022-01-04 11:56
@noocsharp Thanks for this! :)

**Comment by iHiD** [comment] 2022-01-04 12:10
Fixed by https://github.com/exercism/website/pull/2307

**Closed** 2022-01-05 11:49 UTC
Labels: type/improvement, area/website
