### ISSUE TITLE
Profile requires password to change things like email but I made no password since I sign in via GitHub.

### ISSUE THREAD

**Issue by zorn** [exercism/exercism#5665] opened 2021-09-02 12:40 UTC
Not sure what the alternate path should be for this but noticed the issues as I have an older email on my account and would like to update it.

**Comment by angelikatyborska** [comment] 2021-09-02 12:44
This is a duplicate of https://github.com/exercism/exercism/issues/5662 which was closed because it's a duplicate of https://github.com/exercism/exercism/issues/5661 😁 

@exercism/maintainers-admin can somebody please rename https://github.com/exercism/exercism/issues/5661 to something like the title of this issue? the title of that issue makes no sense to normal people and they can't recognize it as the problem they're having.

**Comment by angelikatyborska** [comment] 2021-09-02 13:07
@zorn the title of your issue has been copied to https://github.com/exercism/exercism/issues/5661 (because it has been here first). Subscribe to that issue to get updated about progress.

I am going to close this now because it's a duplicate, but of course this problem is important to us and will get fixed.

**Closed by angelikatyborska** 2021-09-02 13:07 UTC
