### ISSUE TITLE
c# track very long response time

### ISSUE THREAD

**Issue by damiangraber** [exercism/exercism#5070] opened 2019-10-09 08:30 UTC
Hi guys, 

I read lately information about the long waiting time and growing queues, but I guess there is something wrong with my submission... Since the moment I submitted the task instead of less, I have more and more tasks before mine to be checked... Is there some general problem? 

Regards,
Damian

**Comment by NobbZ** [comment] 2019-10-09 08:53
@iHiD, is this related to exercism/bugs#18 and exercism/bugs#19?

**Comment by iHiD** [comment] 2019-10-09 09:19
I suspect a mentor has just timed out so there are lots of solutions that have just gone back into the queue. I'm pretty sure those two bugs you linked to are fixed.

@damiangraber How long has your wait time being so far and what is your solution id?

**Comment by OswyChow** [comment] 2019-10-09 10:14
Same for me, been 2 days without response in C# Track for the Leap exercise, the ID is 9dde385f510343609bc7c7f1681ff482

**Comment by damiangraber** [comment] 2019-10-09 10:18
@iHiD I have no idea what happened... I am waiting since 03/10/2019 and my solution ID is 04e116f034b347c7a4035452b8ab00ba

**Comment by iHiD** [comment] 2019-10-09 10:24
What is the median wait time for your exercises according to the UI?

**Comment by OswyChow** [comment] 2019-10-09 10:25
@iHiD for me its 3 hours

**Comment by damiangraber** [comment] 2019-10-09 10:54
@iHiD "There are currently 29 solutions ahead of this in the C# queue, and 2 ahead in the Gigasecond queue. The median waiting time for mentoring on this exercise is 10 minutes. Learn more about how mentor queues work."

**Comment by iHiD** [comment] 2019-10-09 10:57
That's some fast median wait times! I'll ask the C# mentors to see what's going on. There might just be a rush of solutions.

**Comment by damiangraber** [comment] 2019-10-09 11:10
Yeah... but that is why I actually think is some kind of a bug... before I had 20 something solutions ahead, 1 ahead in the gigasecond queue and the waiting time was 2 hours or so... But it's like that since 03/10.

**Comment by sshine** [comment] 2019-10-10 11:39
@iHiD the estimates could be temporarily affected by a mentor picking up the lost submissions of an exiting mentor simply by saying "Hey, I see you didn't do anything here, let me know if you need more feedback." which is a copy-paste action. I did that once half a year ago to dozens in a short period of time.

**Comment by damiangraber** [comment] 2019-10-13 11:33
Any news? Should I wait or just let it go? Again, yesterday I had 20 solutions to be reviewed before mine, now it's 22. I am checking that basically every day because I would like to keep moving forward...

**Comment by sshine** [comment] 2019-10-13 12:38
@damiangraber: I'm sorry, but the queue growing is probably not a bug in the sense that your solution will never be reached, or that there is some kind of "skipping the line" logic involved; both the waiting time and the queue appearing to grow is caused by too few mentors per student.

As such, your best bet of moving forward quickly is to skip to independent mode.

Otherwise, you are also free to wait or explore a language track with better response times.

I'm closing this issue for now.

**Closed by sshine** 2019-10-13 12:38 UTC
Labels: type/mentoring-support
