### ISSUE TITLE
Instructions rendering issue for several exercises in the Elixir track

### ISSUE THREAD

**Issue by sevenseacat** [exercism/exercism#5780] opened 2021-09-05 06:51 UTC
I was going to file these in the Elixir track repo, but I think they might be more general and apply to multiple exercises so we'll see?

--- 

I noticed that for code blocks in the City Office exercise, the first line of text is not being rendered inside the code block. And if the block is only a single line, then there's no rendered code block at all!

Source: https://github.com/exercism/elixir/blob/main/exercises/concept/city-office/.docs/instructions.md

How it renders: 

<img width="461" alt="Screen Shot 2021-09-05 at 2 42 27 pm" src="https://user-images.githubusercontent.com/543859/132118127-9ab25787-ffe1-4802-9fee-60d0d8f64d5a.png">

<img width="460" alt="Screen Shot 2021-09-05 at 2 42 52 pm" src="https://user-images.githubusercontent.com/543859/132118134-4d9f6b2f-4dae-4c38-8e5f-a66a66ecaf54.png">

---

There's a similar issue for table rendering in the German Sysadmin exercise. Content below the table is being rendered inside the table?

Source: https://github.com/exercism/elixir/blob/main/exercises/concept/german-sysadmin/.docs/instructions.md

How it renders: 

<img width="441" alt="Screen Shot 2021-09-05 at 2 50 40 pm" src="https://user-images.githubusercontent.com/543859/132118195-7adff1a7-11a5-46cd-be0e-1913542d3871.png">

**Comment by angelikatyborska** [comment] 2021-09-05 10:25
@sevenseacat Good call opening it here. Those documents render correctly when I look at them on GitHub, so their markdown source is correct. @iHiD @ErikSchierboom There must be something wrong with the markdown rendering library that you're using. I think it's the same issue as https://github.com/exercism/v3-beta/issues/172 that issue is even about the same exercise. I had blockquotes there initially that rendered wrong, so I changed them to code blocks.

Full comparison

## Example 1

### Correct - GH

![Screen Shot 2021-09-05 at 12 19 45](https://user-images.githubusercontent.com/7852553/132123316-1cc6192c-d27c-47af-a68b-d4f24a6e9862.png)

### Incorrect - Exercism

![](https://user-images.githubusercontent.com/543859/132118127-9ab25787-ffe1-4802-9fee-60d0d8f64d5a.png)

### Raw

~~~markdown
## 2. Document filling out fields with blank values

Add documentation and a typespec to the `Form.blanks/1` function. The documentation should read:

```
Generates a string of a given length.

This string can be used to fill out a form field that is supposed to have no value.
Such fields cannot be left empty because a malicious third party could fill them out with false data.
```

The typespec should explain that the function accepts a single argument, a non-negative integer, and returns a string.
~~~

## Example 2

### Correct - GH

![Screen Shot 2021-09-05 at 12 19 17](https://user-images.githubusercontent.com/7852553/132123318-577440fb-0659-483d-bfd7-7b8ee07464a1.png)


### Incorrect - Exercism

![](https://user-images.githubusercontent.com/543859/132118195-7adff1a7-11a5-46cd-be0e-1913542d3871.png)

### Raw
~~~markdown

## 3. Substitute German characters

There are 4 non-Latin characters in the German alphabet, and all of them have commonly-recognized Latin substitutes.

| German character | Latin substitute |
| ---------------- | ---------------- |
| ä                | ae               |
| ö                | oe               |
| ü                | ue               |
| ß                | ss               |

Extend the `sanitize/1` function. It should substitute German characters according to the table. You can safely assume all usernames are already downcase.

```elixir
Username.sanitize('cäcilie_weiß')
'caecilie_weiss'
```
~~~

**Comment by iHiD** [comment] 2021-09-05 13:34
We're using https://github.com/gjtorikian/commonmarker/, which wraps GitHub's own rendering library. It could be some pre/post-processing maybe, but it's strange.

I'll have a look a little later.

**Comment by angelikatyborska** [comment] 2021-09-05 14:59
At a first glance, this library renders the first example correctly so it might be some other issue.

```
angelika in ~
$ gem install commonmarker
Fetching commonmarker-0.23.1.gem
Building native extensions. This could take a while...
Successfully installed commonmarker-0.23.1
Parsing documentation for commonmarker-0.23.1
Installing ri documentation for commonmarker-0.23.1
Done installing documentation for commonmarker after 0 seconds
1 gem installed

angelika in ~
$ irb
irb(main):001:0" example1 = <<-XXX
irb(main):002:0" ## 2. Document filling out fields with blank values
irb(main):003:0"
irb(main):004:0" Add documentation and a typespec to the `Form.blanks/1` function. The documentation should read:
irb(main):005:0"
irb(main):006:0" ```
irb(main):007:0" Generates a string of a given length.
irb(main):008:0"
irb(main):009:0" This string can be used to fill out a form field that is supposed to have no value.
irb(main):010:0" Such fields cannot be left empty because a malicious third party could fill them out with false data.
irb(main):011:0" ```
irb(main):012:0"
irb(main):013:0" The typespec should explain that the function accepts a single argument, a non-negative integer, and returns a string.
irb(main):014:0> XXX

irb(main):015:0> require 'commonmarker'
=> true

irb(main):016:0> CommonMarker.render_html(example1, :DEFAULT)
=> "<h2>2. Document filling out fields with blank values</h2>\n<p>Add documentation and a typespec to the <code>Form.blanks/1</code> function. The documentation should read:</p>\n<pre><code>Generates a string of a given length.\n\nThis string can be used to fill out a form field that is supposed to have no value.\nSuch fields cannot be left empty because a malicious third party could fill them out with false data.\n</code></pre>\n<p>The typespec should explain that the function accepts a single argument, a non-negative integer, and returns a string.</p>\n"
```

**Comment by iHiD** [comment] 2021-09-05 19:21
Please can I confirm it's correct here: https://exercism.org/tracks/elixir/exercises/city-office ?

It's just on the editor where it's wrong?

**Comment by iHiD** [comment] 2021-09-05 19:24
@ErikSchierboom This issue here is in `app/serializers/serialize_exercise_assignment.rb`. `task_text` is doing something wrong.

**Comment by angelikatyborska** [comment] 2021-09-05 20:39
> Please can I confirm it's correct here: exercism.org/tracks/elixir/exercises/city-office ?

I confirm, it's correct there

**Comment by iHiD** [comment] 2021-09-05 20:42
@angelikatyborska This is Erik's #1 priority on Tues.

**Comment by ErikSchierboom** [comment] 2021-09-07 08:48
PR to fix this is up: https://github.com/exercism/website/pull/1828

This is a duplicate of https://github.com/exercism/v3-beta/issues/172 BTW. Same issue.

**Comment by junedev** [comment] 2021-09-07 10:19
@ErikSchierboom Does this also include a fix for this other rendering issue https://github.com/exercism/exercism/issues/5654?

**Closed** 2021-09-07 10:50 UTC
Labels: priority/urgent

**Comment by angelikatyborska** [comment] 2021-09-07 11:23
@junedev unlikely since #5654 is caused by CSS only, not wrong markup
