### ISSUE TITLE
Can't quite figure out how to get started doing PHP exercises

### ISSUE THREAD

**Issue by remotelyruth** [exercism/exercism#5487] opened 2021-03-06 22:59 UTC
Hello, I am making progress, I've gotten help from lovely people, but still have not quite figured out how to get up and running! Please see Twitter thread below (includes several screenshots and explanations), thanks for any assistance you can provide!

https://twitter.com/remotely_ruth/status/1368254172458414086?s=20

**Comment by neenjaw** [comment] 2021-03-06 23:29
Hey @remotelyruth, I can help you with this.  I can either help you here, or, if you prefer something more real-time, we also have a [gitter chat room](https://gitter.im/exercism/support) here.

If you prefer more asynchronous help, can you tell me what you've done so far?
- What kind of a computer are you using? Windows? Mac? Linux?
- Have you installed php?
  - Are you able to run php from the command line?
  - What version? (`php -v`)
- Did you download phpunit? or did you install composer to install phpunit? 
  - If yes, what version of phpunit? Until v3 launches, the PHP track only supports PHPUnit 8 (and the default download is version 9)

**Comment by SleeplessByte** [comment] 2021-03-07 02:35
@neenjaw for context, see their Twitter thread: https://twitter.com/remotely_ruth/status/1368254172458414086

From this I can establish:
- They are on Mac
- Their primary issue is a missing dependency `wget`

**Comment by remotelyruth** [comment] 2021-03-07 03:15
And sorry that thread is awfully long, if you don't want to sift through that, I've figured out quite a bit and even had help to install wget.
Where I'm stuck is the next step, here is a screenshot of my terminal:
![Screen Shot terminal next step](https://user-images.githubusercontent.com/67297142/110227721-98593f00-7eb8-11eb-8431-f6a029b8561a.jpeg)

**Comment by neenjaw** [comment] 2021-03-07 03:34
Awesome, you've gotten pretty far!!! You're very close. So the problem is what I described above, phpunit always wants to download version 9, which isn't compatible with the track (yet -- _It will when v3 is released_). You need to use phpunit version 8.

Since you have wget this is what you can do:

```shell
> rm phpunit.phar
> wget https://phar.phpunit.de/phpunit-8.phar 
> chmod +x phpunit-8.phar
> ./phpunit-8.phar hello-world/hello-world_test.php
```

Then it should work
```

**Comment by remotelyruth** [comment] 2021-03-07 03:43
Thank you so much for adding the explanations! sorry to say it didn't seem to fully work. Here is another screenshot. Appreciate your help so much!
![Screen Shot phpunit](https://user-images.githubusercontent.com/67297142/110228203-84afd780-7ebc-11eb-8893-7d694bd214ea.jpeg)

**Comment by neenjaw** [comment] 2021-03-07 03:55
A new error is progress though!

So from the screenshot it looks like you are in your home directory, I missed a step to asking you to change to the `exercism/php` directory (`cd ~/exercism/php`) before running those commands. 🤦🏻

**Comment by remotelyruth** [comment] 2021-03-07 04:13
Oh, thanks! I definitely need to learn more about what is happening in the terminal, ha. For now though progress continues, here is the new screenshot.
![Screen Shot fail](https://user-images.githubusercontent.com/67297142/110228750-c5115480-7ec0-11eb-8e8b-b7f33507ca8e.jpeg)

**Comment by SleeplessByte** [comment] 2021-03-07 04:24
You got it working! That failing test is expected. I think you might be able to continue the instructions now. They will/should help you turn that failure into a pass.

**Comment by neenjaw** [comment] 2021-03-07 04:33
@SleeplessByte said it better than I could have! You're doing great, one thing at a time.  Just look at all the things you've picked up getting to this point. 😄 All the best in your adventure, shout if you need anything else!

**Comment by remotelyruth** [comment] 2021-03-07 04:50
Oh well then, that's great! Thanks to both of you for spending the time to help me out with this!!

**Comment by remotelyruth** [comment] 2021-03-07 18:27
Does this mean I passed???
![Screen Shot ok](https://user-images.githubusercontent.com/67297142/110250346-14469c00-7f38-11eb-872c-6baded55cfbd.jpeg)

**Comment by neenjaw** [comment] 2021-03-07 18:35
Yep!

**Comment by neenjaw** [comment] 2021-03-07 18:36
if it were failing, the `.` would be an `E` or `F`, and the summary would say something like `1 ERRORS (1 test, 1 error)`

**Comment by remotelyruth** [comment] 2021-03-07 18:38
Yayyy! Yeah the first couple times I got an error because of my punctuation choices, haha.
Thank you again SOOO much, can't tell you how much I appreciate your help and how close I was to giving up. This experience has made me want to be a part of the Exercism community :)

**Comment by iHiD** [comment] 2021-03-07 18:54
@remotelyruth Glad you've got on with this all so well, and thanks to @neenjaw and @SleeplessByte for their guidance! 

As I mentioned on Twitter, in v3 we've added an editor you can use in the website itself so that others don't have to go through the "pain" you've been through, as it can be really offputting. That all said, going through that "pain" will have taught you so much and given you familiarity/confidence with loads, so it's definitely a great investment of your time :)

Once you submit Hello World, you'll get the next exercise (TwoFer) which you can download, solve, then submit too, at which stage you'll be able to get a mentor to take a look at it for you. If you post a link here once you've done all that, I'll make sure a mentor takes a look :)

(Obviously if you get stuck in the interim feel free to post too!)

**Comment by remotelyruth** [comment] 2021-03-07 19:09
Thanks, and yes all the times I've gotten stuck with anything while learning to code, I've ended up learning a lot. Even though I don't end up doing "the thing" that I wanted to accomplish that day, it's never a waste of time! And reaching out for help is an important experience too, and makes me feel better about humanity when people are so kind and willing to give of their time and energy :) I hope someday I'll have the skills and knowledge to mentor others.

**Comment by ErikSchierboom** [comment] 2021-08-31 06:07
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 06:07 UTC
