### ISSUE TITLE
Cannot submit to Teams when in Mentored mode on website

### ISSUE THREAD

**Issue by stoicAlchemist** [exercism/exercism#5019] opened 2019-09-03 16:51 UTC
Just an FYI, it's confusing the "mode change", I'm using the Team functionality, then on the personal mode, I started in "mentored mode" and started working my solutions, then I tried to get back to my team and push solutions to them and I couldn't, I was locked in "mentored mode" even on the Team context. To solve it, I had to go to the personal context and leave the "mentored mode", then I could go to the Team context and submit new solutions. Is there a better way to be on "team learning" and "personal tracking" at the same time?

**Comment by sshine** [comment] 2019-09-19 16:03
Hi there! Sorry for the response time.

Are you saying that changing into mentored mode on https://exercism.io/ meant that you couldn't upload solutions to https://teams.exercism.io/ ? Is this mentored mode for *any* track? And can you replicate the problem still?

I've been both in mentor mode, mentored mode, independent mode and on teams simultaneously, but it's been a while, so I can't say if there has come some cross-effect in the meantime.

**Comment by sshine** [comment] 2019-10-13 09:56
@iHiD: How do you feel about this bug? I would assume that it's not atypical for Teams users to also have joined the mentored track. My assessment is that it makes Teams useless without explanation for anyone who, unlike @stoicAlchemist, figures out the connection and/or reports it.

@stoicAlchemist: Could you verify if this only applies to uploading Teams solutions in a language for which you're in mentored mode on the main site, or if it applies to *all* language solutions in Teams regardless of what track you're in mentored mode for? I suspect that there may be a connection, and I have some intuition about it only applying to exercises that are not unlocked in mentored mode.

If that is the case, then a fix would be to find and disable this check in Teams.

**Comment by iHiD** [comment] 2019-10-14 12:46
>  I was locked in "mentored mode" even on the Team context.

I need to understand exactly what this means / looks like, etc. Knowing the codebase, it feels like a very strange bug.

**Comment by sshine** [comment] 2019-10-14 13:34
I'll try to replicate the problem at some point.

**Comment by stoicAlchemist** [comment] 2019-10-15 02:56
> > I was locked in "mentored mode" even on the Team context.
> 
> I need to understand exactly what this means / looks like, etc. Knowing the codebase, it feels like a very strange bug.

Hi, sorry for the late response, I haven't had the time to get back to it. What I meant was that I couldn't post new solutions to the "Team mode" until I "abandoned" the "mentored mode"

**Comment by Eddie-Hartman** [comment] 2021-07-22 04:03
@sshine @iHiD 
I may be experiencing this bug currently.

I started on the C# track in mentored mode and was going through the exercises. I like the site and saw the team option. I created a team to share with colleagues, but none of my solutions were visible.

I "started" a problem I already completed in the team and re-submitted the solution, but it just showed up as another iteration in my personal exercism. I went to settings and turned the track into practice mode and submitted another exercise after "starting" it in the team and it still did not show up. I'm going to try and submit a completely new exercise that I have not done in my personal exercism yet to see if me leaving mentored mode and submitting a completely new exercise will show up in my team.

Either way, my expected behavior was that I could be in mentored mode, complete exercises, then share them with my team. I don't think being in practice mode should be a requirement of being on a team. If I'm missing something please let me know.

**Comment by SleeplessByte** [comment] 2021-07-22 14:21
Given the response by the OP, this is indeed a duplicate of #4718.

**Closed by SleeplessByte** 2021-07-22 14:21 UTC
