### ISSUE TITLE
Responsiveness breaks at a particular point

### ISSUE THREAD

**Issue by Ashvith** [exercism/exercism#6241] opened 2022-02-14 05:27 UTC
The responsiveness of the website goes awry when the size is below or equal to `1023 x <any height>`.

Edit: Added picture for reference
![Screenshot from 2022-02-14 11-10-18](https://user-images.githubusercontent.com/9512421/153806543-7fa3098c-1367-465f-8eaa-43ae55fad29d.png)

**Comment by angelikatyborska** [comment] 2022-02-14 07:37
Thanks for reporting! This is a duplicate of https://github.com/exercism/exercism/issues/6036. I'm going to close this issue to keep things tidy. Feel free to subscribe and comment on the other one.

**Closed by angelikatyborska** 2022-02-14 07:37 UTC

**Comment by Ashvith** [comment] 2022-02-14 07:40
> Thanks for reporting! This is a duplicate of https://github.com/exercism/exercism/issues/6036. I'm going to close this issue to keep things tidy. Feel free to subscribe and comment on the other one.

Can I look into this? I have some experience with Rails and HTML-CSS-JS. It would be great if you can direct me to the repository.

**Comment by angelikatyborska** [comment] 2022-02-14 07:47
@Ashvith Not really. The problem affects every single page of the platform. We would need Exercism's designer to actually design mobile views for every page before anyone can start working on the CSS to ensure good UX.

Additionally, while Exercism is generally an open-source project that everyone contributes to, the website code itself is an exception. Only Exercism employees work on that code. It's not set up for community contributions 😞.
