### ISSUE TITLE
CODEOWNERS files with @exercism/maintainers-admin aren't working

### ISSUE THREAD

**Issue by ee7** [exercism/exercism#5411] opened 2020-11-06 14:35 UTC
### Current behaviour
@exercism/maintainers-admin is not automatically requested for review on PRs where they are intended to be the CODEOWNER (and their approving review is not required).

For example, see https://github.com/exercism/nim-test-runner/pull/33

### Expected behaviour
The team should be automatically be requested for review, and we probably intended that their approving review is required.

### Discussion
I believe this affects every repo touched by https://github.com/exercism/exercism/issues/5400 , which added a `.github/CODEOWNERS` file to many repos with the contents
```
* @exercism/maintainers-admin
```

It isn't working. If you browse to a file in affected repos, it doesn't look like this image from the docs:
![code-owner-for-a-file](https://user-images.githubusercontent.com/45465154/98375527-81a5f700-2042-11eb-8774-2b8e8d2e095a.png)

See:
https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners
> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own. Code owners are not automatically requested to review draft pull requests. For more information about draft pull requests, see "About pull requests." When you mark a draft pull request as ready for review, code owners are automatically notified. If you convert a pull request to a draft, people who are already subscribed to notifications are not automatically unsubscribed. For more information, see "Changing the stage of a pull request."
>
> When someone with admin or owner permissions has enabled required reviews, they also can optionally require approval from a code owner before the author can merge a pull request in the repository. For more information, see "Enabling required reviews for pull requests."
>
>If a team has enabled code review assignments, the individual approvals won't satisfy the requirement for code owner approval in a protected branch. For more information, see "Managing code review assignment for your team."
>
>If a file has a code owner, you can see who the code owner is before you open a pull request. In the repository, you can browse to the file and hover over

**Comment by iHiD** [comment] 2020-11-06 14:41
Thanks 🙂  We actually just noticed this at pretty much the same time! The problem is that the team doesn't have write-access to all repos. We'll script-fix that as soon as we have @neenjaw's new script for unwatching repos working too.

**Comment by ErikSchierboom** [comment] 2021-08-31 06:06
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Closed by ErikSchierboom** 2021-08-31 06:06 UTC
