### ISSUE TITLE
The "mentor discussion" textbox tries to add bullet points after a horizontal rule

### ISSUE THREAD

**Issue by grantwinney** [exercism/exercism#4201] opened 2018-08-07 16:08 UTC
When I use a horizontal rule to separate parts of my message in the "mentor discussion" textbox, after I type three dashes and hit enter, it auto-inserts a hyphen on each subsequent line, so that I end up with this:

```markdown
some point to the student
---
- 
- 
hmm... another point
```

It makes sense that if you're building a list, when you hit enter it's convenient to get an auto-inserted hyphen so you can just keep adding to the list.

But if several dashes like a horizontal rule, then building a list is not the expected behavior.

**Comment by NobbZ** [comment] 2018-08-07 17:25
Duplicate of #4188

**Closed** 2018-08-07 19:31 UTC
